/**
 * Centralized export utilities for Audit Universe and Risk Management modules.
 * Provides PDF, DOCX, and grouped report generation with SSB branding.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { addSSBHeader, addSSBFooter, getSSBTableConfig, SSB_BRAND } from '@/lib/reportTemplate';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, WidthType, ShadingType, BorderStyle,
  PageNumber, HeadingLevel,
} from 'docx';
import type { ExportColumn } from '@/components/common/ExportDropdown';

// ────────────────────────────────────────────
// Types
// ────────────────────────────────────────────

export interface ExportMetadata {
  title: string;
  generatedDate: string;
  generatedBy?: string;
  filtersApplied: { label: string; value: string }[];
  totalRecords: number;
}

export interface GroupByOption {
  label: string;
  key: string;
}

// ────────────────────────────────────────────
// Metadata helpers
// ────────────────────────────────────────────

export function buildMetadata(
  title: string,
  totalRecords: number,
  filters: { label: string; value: string }[],
  generatedBy?: string,
): ExportMetadata {
  return {
    title,
    generatedDate: new Date().toLocaleDateString(),
    generatedBy,
    filtersApplied: filters.filter(f => f.value && f.value !== 'all'),
    totalRecords,
  };
}

// ────────────────────────────────────────────
// PDF with metadata
// ────────────────────────────────────────────

export function exportPDFWithMetadata(
  columns: { header: string; key: string }[],
  data: Record<string, any>[],
  metadata: ExportMetadata,
  fileName: string,
  orientation: 'portrait' | 'landscape' = 'portrait',
) {
  const doc = new jsPDF({ orientation });

  const additionalInfo: { label: string; value: string }[] = [
    { label: 'Generated', value: metadata.generatedDate },
    { label: 'Total Records', value: String(metadata.totalRecords) },
  ];
  if (metadata.generatedBy) {
    additionalInfo.push({ label: 'Generated By', value: metadata.generatedBy });
  }
  metadata.filtersApplied.forEach(f => {
    additionalInfo.push({ label: f.label, value: f.value });
  });

  const startY = addSSBHeader(doc, {
    title: metadata.title,
    subtitle: `Total Records: ${metadata.totalRecords}`,
    orientation,
    additionalInfo,
  });

  const headers = columns.map(c => c.header);
  const body = data.map(row =>
    columns.map(c => {
      const v = row[c.key];
      if (v === null || v === undefined) return '—';
      if (typeof v === 'number') return v.toLocaleString();
      return String(v);
    })
  );

  autoTable(doc, { head: [headers], body, ...getSSBTableConfig(startY) });
  addSSBFooter(doc);
  doc.save(`${fileName}.pdf`);
}

// ────────────────────────────────────────────
// Grouped PDF
// ────────────────────────────────────────────

export function exportGroupedPDF(
  columns: { header: string; key: string }[],
  data: Record<string, any>[],
  groupByKey: string,
  groupByLabel: string,
  metadata: ExportMetadata,
  fileName: string,
) {
  const doc = new jsPDF({ orientation: 'landscape' });

  const additionalInfo: { label: string; value: string }[] = [
    { label: 'Generated', value: metadata.generatedDate },
    { label: 'Total Records', value: String(metadata.totalRecords) },
    { label: 'Grouped By', value: groupByLabel },
  ];
  metadata.filtersApplied.forEach(f => additionalInfo.push(f));

  let y = addSSBHeader(doc, {
    title: `${metadata.title} — By ${groupByLabel}`,
    subtitle: `Total Records: ${metadata.totalRecords}`,
    orientation: 'landscape',
    additionalInfo,
  });

  // Group data
  const groups: Record<string, any[]> = {};
  data.forEach(row => {
    const gv = row[groupByKey] || 'Unspecified';
    if (!groups[gv]) groups[gv] = [];
    groups[gv].push(row);
  });

  const headers = columns.map(c => c.header);
  let isFirst = true;

  Object.entries(groups).sort((a, b) => a[0].localeCompare(b[0])).forEach(([groupName, groupData]) => {
    if (!isFirst) doc.addPage();
    isFirst = false;

    // Group header
    const pw = doc.internal.pageSize.getWidth();
    doc.setFillColor(248, 250, 252);
    doc.rect(14, y - 2, pw - 28, 10, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 95, 58);
    doc.text(`${groupByLabel}: ${groupName} (${groupData.length} records)`, 16, y + 5);
    y += 14;

    const body = groupData.map(row =>
      columns.map(c => {
        const v = row[c.key];
        if (v === null || v === undefined) return '—';
        return String(v);
      })
    );

    autoTable(doc, {
      head: [headers],
      body,
      ...getSSBTableConfig(y),
    });

    y = (doc as any).lastAutoTable?.finalY + 8 || y + 20;
  });

  addSSBFooter(doc);
  doc.save(`${fileName}.pdf`);
}

// ────────────────────────────────────────────
// Risk Detail PDF
// ────────────────────────────────────────────

export function exportRiskDetailPDF(
  risk: any,
  actions: any[],
  reviews: any[],
  fileName: string,
) {
  const doc = new jsPDF();

  const startY = addSSBHeader(doc, {
    title: 'Risk Detail Report',
    subtitle: risk.risk_title,
    additionalInfo: [
      { label: 'Entity', value: risk.ia_audit_universe?.entity_name || '—' },
      { label: 'Owner', value: risk.risk_owner || '—' },
      { label: 'Status', value: risk.status },
      { label: 'Generated', value: new Date().toLocaleDateString() },
    ],
  });

  // Scoring table
  autoTable(doc, {
    head: [['Metric', 'Likelihood', 'Impact', 'Score', 'Level']],
    body: [
      ['Inherent', String(risk.inherent_likelihood), String(risk.inherent_impact), String(risk.inherent_risk_score), risk.inherent_risk_level],
      ['Residual', String(risk.residual_likelihood), String(risk.residual_impact), String(risk.residual_risk_score), risk.residual_risk_level],
    ],
    ...getSSBTableConfig(startY),
  });

  let y = (doc as any).lastAutoTable?.finalY + 10 || startY + 30;

  // Description
  if (risk.risk_description) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 95, 58);
    doc.text('Description', 14, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(risk.risk_description, 180);
    doc.text(lines, 14, y);
    y += lines.length * 4 + 6;
  }

  // Mitigation actions
  if (actions.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 95, 58);
    doc.text(`Mitigation Actions (${actions.length})`, 14, y);
    y += 4;

    autoTable(doc, {
      head: [['Action', 'Assigned To', 'Due Date', 'Priority', 'Status']],
      body: actions.map(a => [
        a.action_title,
        a.assigned_to || '—',
        a.due_date || '—',
        a.priority,
        a.status,
      ]),
      ...getSSBTableConfig(y),
    });
    y = (doc as any).lastAutoTable?.finalY + 10 || y + 20;
  }

  // Review history
  if (reviews.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 95, 58);
    doc.text(`Review History (${reviews.length})`, 14, y);
    y += 4;

    autoTable(doc, {
      head: [['Date', 'Reviewer', 'Comment', 'Level Change']],
      body: reviews.map(r => [
        r.review_date || '—',
        r.reviewed_by || '—',
        r.comments || '—',
        r.previous_risk_level !== r.new_risk_level ? `${r.previous_risk_level} → ${r.new_risk_level}` : 'No change',
      ]),
      ...getSSBTableConfig(y),
    });
  }

  addSSBFooter(doc);
  doc.save(`${fileName}.pdf`);
}

// ────────────────────────────────────────────
// Mitigation Action Plan PDF
// ────────────────────────────────────────────

export function exportMitigationPlanPDF(
  risks: any[],
  allActions: any[],
  fileName: string,
) {
  const doc = new jsPDF({ orientation: 'landscape' });

  // Summary counts
  const planned = allActions.filter(a => a.status === 'Planned').length;
  const inProgress = allActions.filter(a => a.status === 'In Progress').length;
  const completed = allActions.filter(a => a.status === 'Completed').length;
  const overdue = allActions.filter(a => a.due_date && a.due_date < new Date().toISOString().slice(0, 10) && a.status !== 'Completed').length;

  const startY = addSSBHeader(doc, {
    title: 'Mitigation Action Plan',
    orientation: 'landscape',
    additionalInfo: [
      { label: 'Total Actions', value: String(allActions.length) },
      { label: 'Planned', value: String(planned) },
      { label: 'In Progress', value: String(inProgress) },
      { label: 'Completed', value: String(completed) },
      { label: 'Overdue', value: String(overdue) },
      { label: 'Generated', value: new Date().toLocaleDateString() },
    ],
  });

  // Group by risk
  const grouped: Record<string, { risk: any; actions: any[] }> = {};
  allActions.forEach(a => {
    const riskId = a.risk_id;
    if (!grouped[riskId]) {
      const risk = risks.find(r => r.id === riskId);
      grouped[riskId] = { risk: risk || { risk_title: 'Unknown Risk' }, actions: [] };
    }
    grouped[riskId].actions.push(a);
  });

  let y = startY;
  let isFirst = true;

  Object.values(grouped).forEach(({ risk, actions }) => {
    if (!isFirst && y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = 20;
    }
    isFirst = false;

    const pw = doc.internal.pageSize.getWidth();
    doc.setFillColor(248, 250, 252);
    doc.rect(14, y - 2, pw - 28, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 95, 58);
    doc.text(`Risk: ${risk.risk_title}`, 16, y + 4);
    y += 10;

    autoTable(doc, {
      head: [['Action', 'Assigned To', 'Due Date', 'Priority', 'Status']],
      body: actions.map(a => [a.action_title, a.assigned_to || '—', a.due_date || '—', a.priority, a.status]),
      ...getSSBTableConfig(y),
    });

    y = (doc as any).lastAutoTable?.finalY + 8 || y + 20;
  });

  addSSBFooter(doc);
  doc.save(`${fileName}.pdf`);
}

// ────────────────────────────────────────────
// DOCX Export
// ────────────────────────────────────────────

const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' };
const cellBorders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };

export async function exportDocx(
  columns: ExportColumn[],
  data: Record<string, any>[],
  metadata: ExportMetadata,
  fileName: string,
) {
  // Calculate column widths — distribute evenly across US Letter content width
  const contentWidth = 9360; // US Letter with 1" margins in DXA
  const colWidth = Math.floor(contentWidth / columns.length);
  const columnWidths = columns.map(() => colWidth);

  // Metadata paragraphs
  const metaParagraphs: Paragraph[] = [
    new Paragraph({ spacing: { after: 100 }, children: [
      new TextRun({ text: `Generated: ${metadata.generatedDate}`, size: 18, color: '666666', italics: true }),
      ...(metadata.generatedBy ? [new TextRun({ text: `  |  By: ${metadata.generatedBy}`, size: 18, color: '666666', italics: true })] : []),
    ]}),
    new Paragraph({ spacing: { after: 100 }, children: [
      new TextRun({ text: `Total Records: ${metadata.totalRecords}`, size: 18, color: '666666' }),
    ]}),
  ];

  if (metadata.filtersApplied.length > 0) {
    metaParagraphs.push(new Paragraph({ spacing: { after: 200 }, children: [
      new TextRun({ text: 'Filters: ', size: 18, bold: true, color: '333333' }),
      new TextRun({ text: metadata.filtersApplied.map(f => `${f.label}: ${f.value}`).join(', '), size: 18, color: '666666' }),
    ]}));
  }

  // Header row
  const headerRow = new TableRow({
    children: columns.map((col, i) => new TableCell({
      borders: cellBorders,
      width: { size: columnWidths[i], type: WidthType.DXA },
      shading: { fill: '0E5F3A', type: ShadingType.CLEAR },
      margins: { top: 60, bottom: 60, left: 80, right: 80 },
      children: [new Paragraph({ children: [new TextRun({ text: col.header, bold: true, color: 'FFFFFF', size: 18, font: 'Arial' })] })],
    })),
  });

  // Data rows
  const dataRows = data.map((row, idx) => new TableRow({
    children: columns.map((col, i) => {
      const v = row[col.key];
      const text = v === null || v === undefined ? '—' : String(v);
      return new TableCell({
        borders: cellBorders,
        width: { size: columnWidths[i], type: WidthType.DXA },
        shading: idx % 2 === 1 ? { fill: 'F8FAFC', type: ShadingType.CLEAR } : undefined,
        margins: { top: 40, bottom: 40, left: 80, right: 80 },
        children: [new Paragraph({ children: [new TextRun({ text, size: 18, font: 'Arial' })] })],
      });
    }),
  }));

  const table = new Table({
    width: { size: contentWidth, type: WidthType.DXA },
    columnWidths,
    rows: [headerRow, ...dataRows],
  });

  const doc = new Document({
    styles: {
      default: { document: { run: { font: 'Arial', size: 22 } } },
    },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              spacing: { after: 100 },
              children: [
                new TextRun({ text: SSB_BRAND.name, bold: true, size: 20, color: '0E5F3A', font: 'Arial' }),
              ],
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: `${SSB_BRAND.name} — ${SSB_BRAND.address}  |  Page `, size: 14, color: '999999' }),
                new TextRun({ children: [PageNumber.CURRENT], size: 14, color: '999999' }),
              ],
            }),
          ],
        }),
      },
      children: [
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
          children: [new TextRun({ text: metadata.title, bold: true, size: 28, color: '0E5F3A', font: 'Arial' })],
        }),
        ...metaParagraphs,
        table,
      ],
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  saveAs(new Blob([buffer as unknown as ArrayBuffer], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }), `${fileName}.docx`);
}

// ────────────────────────────────────────────
// Grouped Excel
// ────────────────────────────────────────────

export async function exportGroupedExcel(
  columns: ExportColumn[],
  data: Record<string, any>[],
  groupByKey: string,
  groupByLabel: string,
  metadata: ExportMetadata,
  fileName: string,
) {
  const wb = new ExcelJS.Workbook();

  // Group data
  const groups: Record<string, any[]> = {};
  data.forEach(row => {
    const gv = row[groupByKey] || 'Unspecified';
    if (!groups[gv]) groups[gv] = [];
    groups[gv].push(row);
  });

  Object.entries(groups).sort((a, b) => a[0].localeCompare(b[0])).forEach(([groupName, groupData]) => {
    const sheetName = groupName.slice(0, 31); // Excel max sheet name
    const ws = wb.addWorksheet(sheetName);

    // Header
    ws.columns = columns.map(c => ({ header: c.header, key: c.key, width: c.width || 18 }));

    // Group title row
    ws.spliceRows(1, 0, [`${groupByLabel}: ${groupName} (${groupData.length} records)`]);
    ws.mergeCells(1, 1, 1, columns.length);
    const titleCell = ws.getCell('A1');
    titleCell.font = { bold: true, size: 12, color: { argb: 'FF0E5F3A' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };

    // Column headers (row 2)
    const headerRow = ws.getRow(2);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0E5F3A' } };

    // Data
    groupData.forEach(row => {
      const mapped: Record<string, any> = {};
      columns.forEach(c => { mapped[c.key] = row[c.key] ?? ''; });
      ws.addRow(mapped);
    });

    // Borders
    ws.eachRow(row => {
      row.eachCell(cell => {
        cell.border = { top: { style: 'thin' }, bottom: { style: 'thin' }, left: { style: 'thin' }, right: { style: 'thin' } };
      });
    });
  });

  const buffer = await wb.xlsx.writeBuffer();
  saveAs(new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${fileName}.xlsx`);
}
