project_id = "pruvbfejdpodpalqafcu"

[functions.workflow-notify-approvers]
verify_jwt = false

[functions.meeting-api-handler]
verify_jwt = false

[functions.workflow-action-api]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.public-api-validate-key]
verify_jwt = false

[functions.public-api-execute]
verify_jwt = false
