project_id = "pruvbfejdpodpalqafcu"

[functions.send-email-campaign]
verify_jwt = false

[functions.qa-ai-generator]
verify_jwt = false

[functions.qa-test-runner]
verify_jwt = false

[functions.workflow-notify-approvers]
verify_jwt = false

[functions.meeting-api-handler]
verify_jwt = false

[functions.workflow-action-api]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.public-api-validate-key]
verify_jwt = false

[functions.public-api-execute]
verify_jwt = false

[functions.dms-transfer]
verify_jwt = false

[functions.resolve-auth-email]
verify_jwt = false
