
CREATE TABLE public.migration_analysis_tables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL UNIQUE,
  primary_key_field TEXT NOT NULL DEFAULT 'id',
  category TEXT,
  added_by TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.migration_analysis_tables (table_name, primary_key_field, category) VALUES
  ('app_modules', 'id', 'Configuration'),
  ('roles', 'id', 'Configuration'),
  ('role_permissions', 'id', 'Configuration'),
  ('departments', 'id', 'Organization'),
  ('designations', 'id', 'Organization'),
  ('office_management', 'id', 'Organization'),
  ('workflow_definitions', 'id', 'Workflows'),
  ('workflow_steps', 'id', 'Workflows'),
  ('notification_templates', 'id', 'Notifications'),
  ('tb_payment_type', 'id', 'MasterData'),
  ('tb_country', 'id', 'MasterData'),
  ('tb_parish', 'id', 'MasterData'),
  ('tb_village', 'id', 'MasterData'),
  ('tb_occupation', 'id', 'MasterData'),
  ('tb_industrial_classification', 'id', 'MasterData'),
  ('tb_relation', 'id', 'MasterData'),
  ('tb_sector', 'id', 'MasterData'),
  ('tb_benefit_type', 'id', 'MasterData'),
  ('tb_income_code', 'id', 'MasterData'),
  ('tb_income_category', 'id', 'MasterData'),
  ('c3_config_details', 'id', 'Compliance'),
  ('c3_calculation_config', 'id', 'Compliance'),
  ('c3_bonus_policy_default', 'id', 'Compliance'),
  ('c3_levy_slabs', 'id', 'Compliance'),
  ('sep_contribution_rates', 'id', 'Contributions'),
  ('payment_module_config', 'id', 'Configuration'),
  ('password_policy', 'id', 'Security'),
  ('mfa_settings', 'id', 'Security'),
  ('api_settings', 'id', 'Configuration'),
  ('api_registry', 'id', 'Configuration'),
  ('api_rate_limit_policies', 'id', 'Configuration'),
  ('data_scope_rules', 'id', 'Security'),
  ('field_security_rules', 'id', 'Security'),
  ('document_purposes', 'id', 'Configuration'),
  ('fee_configurations', 'id', 'Configuration'),
  ('security_policy_config', 'id', 'Security'),
  ('ip_access_rules', 'id', 'Security'),
  ('app_lockdown_state', 'id', 'Configuration'),
  ('tb_levy_slab_details', 'id', 'MasterData');
