
-- Reset the identity sequence for cn_payment.payment_sequence_no to avoid collisions
SELECT setval(
  pg_get_serial_sequence('public.cn_payment', 'payment_sequence_no'),
  COALESCE((SELECT MAX(payment_sequence_no) FROM public.cn_payment), 0)
);

-- Recreate public_api_payment_save RPC: remove explicit payment_sequence_no insertion
DROP FUNCTION IF EXISTS public.public_api_payment_save(TEXT, TEXT, JSONB);

CREATE OR REPLACE FUNCTION public.public_api_payment_save(
  p_payer_id TEXT,
  p_payer_type TEXT,
  p_payload JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payment_id BIGINT;
  v_receipt_number TEXT;
  v_receipt_id INTEGER;
  v_mop_code TEXT;
  v_office_code TEXT;
  v_headers JSONB;
  v_header JSONB;
  v_total NUMERIC := 0;
  v_line_count INT := 0;
BEGIN
  v_mop_code := COALESCE(TRIM(p_payload->>'mopCode'), 'ONL');
  v_office_code := COALESCE(TRIM(p_payload->>'officeCode'), '100');
  v_headers := p_payload->'paymentHeaders';

  IF v_headers IS NULL OR jsonb_array_length(v_headers) = 0 THEN
    RETURN jsonb_build_object('error', 'paymentHeaders array is required');
  END IF;

  -- Acquire advisory lock to safely generate next payment_id
  PERFORM pg_advisory_xact_lock(7839202);

  -- Generate numeric payment_id matching the internal pattern
  SELECT COALESCE(MAX(payment_id), 0) + 1 INTO v_payment_id FROM cn_payment_header;

  -- Generate text-based receipt number
  v_receipt_number := 'RCP-' || TO_CHAR(NOW(), 'YYYY') || '-' || LPAD(
    COALESCE(
      (SELECT COUNT(*) + 1 FROM cn_receipt WHERE receipt_number LIKE 'RCP-' || TO_CHAR(NOW(), 'YYYY') || '-%')::TEXT,
      '1'
    ), 6, '0'
  );

  -- Insert payment header
  INSERT INTO cn_payment_header (payment_id, payer_id, payer_type, batch_number, date_received, status)
  VALUES (v_payment_id, TRIM(p_payer_id), TRIM(p_payer_type), v_office_code || '-' || TO_CHAR(NOW(), 'YYYYMMDD-HH24MISS'), NOW(), 'P');

  -- Insert payment line items (payment_sequence_no is auto-generated by identity)
  FOR v_header IN SELECT * FROM jsonb_array_elements(v_headers)
  LOOP
    IF (v_header->>'paymentAmount')::NUMERIC > 0 THEN
      INSERT INTO cn_payment (
        payment_id, fund_code, payment_code,
        mop_code, payment_amount, payment_date, period
      ) VALUES (
        v_payment_id,
        TRIM(v_header->>'fundCode'),
        TRIM(v_header->>'paymentCode'),
        v_mop_code,
        (v_header->>'paymentAmount')::NUMERIC,
        NOW(),
        date_trunc('month', NOW())::DATE
      );
      v_total := v_total + (v_header->>'paymentAmount')::NUMERIC;
      v_line_count := v_line_count + 1;
    END IF;
  END LOOP;

  -- Insert receipt (receipt_id is GENERATED ALWAYS AS IDENTITY)
  INSERT INTO cn_receipt (payment_id, receipt_number, receipt_total, status, total_number_of_payments, created_by)
  VALUES (v_payment_id, v_receipt_number, v_total, 'A', v_line_count, 'API')
  RETURNING receipt_id INTO v_receipt_id;

  RETURN jsonb_build_object(
    'paymentId', v_payment_id,
    'receiptId', v_receipt_id,
    'receiptNumber', v_receipt_number,
    'receiptTotal', v_total,
    'message', 'Payment processed successfully'
  );
END;
$$;
