// EPIC CH-TRACE-2 — Universal trace stage model (edge mirror).
// Keep in sync with src/platform/communication-hub/trace/traceStages.ts.

export const TRACE_STAGES = [
  "EVENT_INITIATED",
  "SOURCE_CONTEXT_CAPTURED",
  "RECIPIENT_RESOLUTION_STARTED",
  "RECIPIENT_RESOLVED",
  "AUTOMATION_CHECKED",
  "DUPLICATE_CHECKED",
  "TYPED_CONFIRMATION_CHECKED",
  "ENQUEUE_RECEIVED",
  "PAYLOAD_VALIDATED",
  "LIVE_SEND_ENTERED",
  "LIVE_PREFLIGHT_CHECKED",
  "SEND_POLICY_CHECKED",
  "REVIEW_POLICY_CHECKED",
  "DB_POLICY_GUARD_CHECKED",
  "TEMPLATE_MAPPING_CHECKED",
  "TEMPLATE_RESOLVED",
  "TEMPLATE_RENDERED",
  "SENDER_RESOLUTION_STARTED",
  "SENDER_RESOLVED",
  "REQUEST_CREATE_ATTEMPTED",
  "REQUEST_CREATED",
  "RECIPIENT_CREATE_ATTEMPTED",
  "RECIPIENT_CREATED",
  "MESSAGE_CREATE_ATTEMPTED",
  "MESSAGE_CREATED",
  "MESSAGE_QUEUED",
  "DISPATCH_INVOKED",
  "DISPATCH_CLAIM_ATTEMPTED",
  "DISPATCH_CLAIMED",
  "CONTROL_GATES_CHECKED",
  "LIVE_WINDOW_CHECKED",
  "EVENT_LIVE_STATUS_CHECKED",
  "RECIPIENT_ALLOWLIST_CHECKED",
  "ENV_ALLOWLIST_CHECKED",
  "PROVIDER_LOOKUP_STARTED",
  "PROVIDER_SELECTED",
  "PROVIDER_SEND_ATTEMPTED",
  "PROVIDER_ACCEPTED",
  "PROVIDER_FAILED",
  "DELIVERY_ATTEMPT_RECORDED",
  "REQUEST_STATUS_RECOMPUTED",
  "COMPLETED",
  "BLOCKED",
  "SUPPRESSED",
  "FAILED",
] as const;

export type TraceStage = (typeof TRACE_STAGES)[number];

export type TraceStepStatus =
  | "passed"
  | "warning"
  | "blocked"
  | "skipped"
  | "failed"
  | "info";
