import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { toast } from "sonner";
import { AlertTriangle, FileText, Plus, Send, Printer, CheckCircle2, XCircle, Eye } from "lucide-react";
import {
  LgDataGrid,
  LgStatusBadge,
  type LgColumnDef,
} from "@/components/legal/grid";
import type { BNRowAction } from "@/components/bn/grid/types";

import {
  useLgNotices,
  useLgReference,
  useApproveLgNotice,
  useSubmitLgNoticeForApproval,
  useDispatchLgNotice,
  useCancelLgNotice,
} from "@/hooks/legal/useLgCases";
import { useUserCode } from "@/hooks/useUserCode";
import { useLgAccess } from "@/hooks/legal/useLgAccess";
import type { LgNotice } from "@/services/legal/lgCaseService";

/**
 * Legal Notices & Letters — Register.
 *
 * Central list of every notice generated by the Legal module. Powered by the
 * shared `LgDataGrid` (same toolbar/paging/filters as every other Legal
 * listing), reads directly from `lg_notice`, and drives the full lifecycle:
 *
 *   DRAFT → PENDING_APPROVAL → APPROVED → SENT → (ACKNOWLEDGED)
 *
 * All lifecycle transitions go through capability-gated hooks that also write
 * `lg_case_activity` audit rows (see `useApproveLgNotice`,
 * `useSubmitLgNoticeForApproval`, `useDispatchLgNotice`, `useCancelLgNotice`).
 *
 * No dummy data — the previous mock arrays that used to live in this module
 * have been removed.
 */

const CHANNELS = [
  { code: "EMAIL", label: "Email" },
  { code: "POST", label: "Registered Post" },
  { code: "COURIER", label: "Courier" },
  { code: "IN_PERSON", label: "Personal Service" },
  { code: "PORTAL", label: "Portal / Download" },
];

export default function LgNoticeRegister() {
  const navigate = useNavigate();
  const { userCode } = useUserCode();
  const access = useLgAccess();

  const { data: notices = [], isLoading, error, refetch } = useLgNotices();
  const { data: noticeTypes = [] } = useLgReference("LG_NOTICE_TYPE");

  const submitForApproval = useSubmitLgNoticeForApproval();
  const approve = useApproveLgNotice();
  const dispatch = useDispatchLgNotice();
  const cancel = useCancelLgNotice();

  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewNotice, setPreviewNotice] = useState<LgNotice | null>(null);
  const [dispatchOpen, setDispatchOpen] = useState(false);
  const [dispatchNotice, setDispatchNotice] = useState<LgNotice | null>(null);
  const [dispatchChannel, setDispatchChannel] = useState<string>("EMAIL");

  const typeLabel = (code: string) => noticeTypes.find((t) => t.code === code)?.label ?? code;

  const canApprove = access.can("approveNotice");
  const canDispatch = access.can("sendNotice") || access.can("generateNotice");


  const openPreview = (n: LgNotice) => { setPreviewNotice(n); setPreviewOpen(true); };
  const openDispatch = (n: LgNotice) => {
    if (n.status !== "APPROVED" && n.status !== "DRAFT") {
      toast.error("Notice cannot be dispatched", { description: `Status is ${n.status}. Approve it first.` });
      return;
    }
    setDispatchNotice(n);
    setDispatchChannel(n.delivery_channel || "EMAIL");
    setDispatchOpen(true);
  };
  const runPrint = (n: LgNotice) => {
    // Deferred print: open preview and use browser print.
    setPreviewNotice(n);
    setPreviewOpen(true);
    setTimeout(() => window.print(), 300);
  };

  const columns: LgColumnDef<LgNotice>[] = useMemo(
    () => [
      { accessorKey: "notice_no", header: "Notice No", meta: { label: "Notice No", pinLeft: true, width: 160 } },
      {
        accessorKey: "notice_type_code", header: "Type", meta: { label: "Type" },
        cell: ({ row }) => typeLabel(row.original.notice_type_code),
      },
      { accessorKey: "subject", header: "Subject", meta: { label: "Subject" } },
      {
        accessorKey: "status", header: "Status", meta: { label: "Status", width: 150 },
        cell: ({ row }) => <LgStatusBadge status={row.original.status} />,
      },
      { accessorKey: "delivery_channel", header: "Channel", meta: { label: "Channel", width: 120 },
        cell: ({ row }) => row.original.delivery_channel ?? "—" },
      { accessorKey: "issued_date", header: "Issued", meta: { label: "Issued", width: 120 },
        cell: ({ row }) => row.original.issued_date ?? "—" },
      { accessorKey: "response_due_date", header: "Response Due", meta: { label: "Response Due", width: 130 },
        cell: ({ row }) => row.original.response_due_date ?? "—" },
      { accessorKey: "sent_at", header: "Sent", meta: { label: "Sent", width: 160 },
        cell: ({ row }) => row.original.sent_at ? new Date(row.original.sent_at).toLocaleString() : "—" },
      { accessorKey: "created_at", header: "Created", meta: { label: "Created", width: 160 },
        cell: ({ row }) => new Date(row.original.created_at).toLocaleString() },
    ],
    [noticeTypes],
  );

  const rowActions = useMemo(
    () =>
      buildLgRowActions<LgNotice>({
        actions: [
          { label: "Preview", icon: Eye, onSelect: openPreview },
          {
            label: "Open Case",
            icon: FileText,
            onSelect: (n) => navigate(`/legal/lg/cases/${n.lg_case_id}`),
          },
          {
            label: "Submit for Approval",
            icon: CheckCircle2,
            disabled: (n) => n.status !== "DRAFT",
            onSelect: (n) => submitForApproval.mutate(
              { id: n.id, caseId: n.lg_case_id, userCode: userCode ?? null, noticeNo: n.notice_no },
              { onSuccess: () => toast.success("Sent for approval") },
            ),
          },
          {
            label: "Approve",
            icon: CheckCircle2,
            disabled: (n) => !canApprove || !["DRAFT", "PENDING_APPROVAL"].includes(n.status),
            onSelect: (n) => approve.mutate(
              { id: n.id, caseId: n.lg_case_id, userCode: userCode ?? null, noticeNo: n.notice_no },
              { onSuccess: () => toast.success("Notice approved") },
            ),
          },
          {
            label: "Dispatch",
            icon: Send,
            disabled: (n) => !canDispatch || n.status === "SENT" || n.status === "CANCELLED",
            onSelect: openDispatch,
          },
          {
            label: "Print",
            icon: Printer,
            onSelect: runPrint,
          },
          {
            label: "Cancel",
            icon: XCircle,
            destructive: true,
            disabled: (n) => n.status === "SENT" || n.status === "CANCELLED",
            onSelect: (n) => cancel.mutate(
              { id: n.id, caseId: n.lg_case_id, userCode: userCode ?? null, noticeNo: n.notice_no },
              { onSuccess: () => toast.success("Notice cancelled") },
            ),
          },
        ],
      }),
    [canApprove, canDispatch, userCode],
  );

  const summary = useMemo(() => {
    const s = { total: notices.length, draft: 0, pending: 0, approved: 0, sent: 0, cancelled: 0 };
    for (const n of notices) {
      if (n.status === "DRAFT") s.draft++;
      else if (n.status === "PENDING_APPROVAL") s.pending++;
      else if (n.status === "APPROVED") s.approved++;
      else if (n.status === "SENT") s.sent++;
      else if (n.status === "CANCELLED") s.cancelled++;
    }
    return s;
  }, [notices]);

  return (
    <div className="container mx-auto p-6 space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2"><FileText className="h-6 w-6 text-primary" /> Legal Notices &amp; Letters</h1>
          <p className="text-sm text-muted-foreground">Register of every notice and letter generated by Legal. Approve, dispatch and print from here.</p>
        </div>
        <Button onClick={() => navigate("/legal/notices/generate")} disabled={!access.can("generateNotice")}>
          <Plus className="h-4 w-4 mr-1" /> Generate Notice
        </Button>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>Failed to load notices. <button className="underline" onClick={() => refetch()}>Retry</button></AlertDescription>
        </Alert>
      )}

      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        {[
          { label: "Total", value: summary.total },
          { label: "Draft", value: summary.draft },
          { label: "Pending Approval", value: summary.pending },
          { label: "Approved", value: summary.approved },
          { label: "Sent", value: summary.sent },
        ].map((c) => (
          <Card key={c.label}><CardContent className="p-4">
            <div className="text-xs text-muted-foreground">{c.label}</div>
            <div className="text-2xl font-semibold">{c.value}</div>
          </CardContent></Card>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Notices Register</CardTitle>
          <CardDescription>Standardised Legal grid — filter, sort, export, bulk-select from the toolbar.</CardDescription>
        </CardHeader>
        <CardContent>
          <LgDataGrid
            id="notices.register"
            data={notices}
            columns={columns}
            loading={isLoading}
            rowActions={rowActions}
            exportFilename="legal-notices"
          />
        </CardContent>
      </Card>

      {/* Preview dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>{previewNotice?.notice_no} — {previewNotice?.subject || "(no subject)"}</DialogTitle>
            <DialogDescription>
              <Badge variant="outline" className="mr-2">{typeLabel(previewNotice?.notice_type_code ?? "")}</Badge>
              <LgStatusBadge status={previewNotice?.status ?? ""} />
            </DialogDescription>
          </DialogHeader>
          <div className="max-h-[60vh] overflow-auto border rounded p-4 bg-background whitespace-pre-wrap text-sm">
            {previewNotice?.body || "(empty body)"}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPreviewOpen(false)}>Close</Button>
            <Button variant="outline" onClick={() => window.print()}><Printer className="h-4 w-4 mr-1" />Print</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Dispatch dialog */}
      <Dialog open={dispatchOpen} onOpenChange={setDispatchOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Dispatch Notice {dispatchNotice?.notice_no}</DialogTitle>
            <DialogDescription>Choose the delivery channel. The notice will be recorded as SENT and audited.</DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <div>
              <Label>Delivery Channel</Label>
              <Select value={dispatchChannel} onValueChange={setDispatchChannel}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {CHANNELS.map((c) => <SelectItem key={c.code} value={c.code}>{c.label}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDispatchOpen(false)}>Cancel</Button>
            <Button
              disabled={dispatch.isPending || !dispatchNotice}
              onClick={() => {
                if (!dispatchNotice) return;
                dispatch.mutate(
                  {
                    id: dispatchNotice.id,
                    caseId: dispatchNotice.lg_case_id,
                    channel: dispatchChannel,
                    userCode: userCode ?? null,
                    noticeNo: dispatchNotice.notice_no,
                  },
                  {
                    onSuccess: () => {
                      toast.success(`Notice dispatched via ${dispatchChannel}`);
                      setDispatchOpen(false);
                    },
                    onError: (e: any) => toast.error("Dispatch failed", { description: e?.message }),
                  },
                );
              }}
            >
              <Send className="h-4 w-4 mr-1" /> Dispatch
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
