/**
 * BN Risk Management (Fraud/Error/Risk) — Canonical state machine.
 */

export type BnRiskStatus =
  | 'DETECTED'                 // Signal generated by rule engine
  | 'TRIAGED'                  // Human triage complete
  | 'ENHANCED_VERIFICATION'    // Additional evidence being collected
  | 'INVESTIGATION'            // Full investigation open
  | 'PAYMENT_HELD'             // Payments held pending investigation
  | 'SYSTEM_ERROR_CONFIRMED'   // Root cause: system error
  | 'CLAIM_CORRECTED'          // Underlying claim corrected
  | 'OVERPAYMENT_AVOIDED'      // Prevented overpayment (positive outcome)
  | 'REFERRED_TO_LEGAL'        // Escalated to Legal (fraud)
  | 'CLEARED'                  // No fraud/error found
  | 'HOLD_RELEASED'            // Payment hold released
  | 'CLOSED';

export type BnRiskSignalSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type BnRiskEventCode =
  | 'SIGNAL_DETECTED'
  | 'TRIAGED'
  | 'VERIFICATION_ENHANCED'
  | 'INVESTIGATION_OPENED'
  | 'PAYMENT_HELD'
  | 'SYSTEM_ERROR_CONFIRMED'
  | 'CLAIM_CORRECTED'
  | 'OVERPAYMENT_AVOIDED'
  | 'REFERRED_TO_LEGAL'
  | 'CLEARED'
  | 'HOLD_RELEASED'
  | 'CLOSED';

export const BN_RISK_TRANSITIONS: Readonly<Record<BnRiskStatus, readonly BnRiskStatus[]>> = {
  DETECTED: ['TRIAGED', 'CLEARED'],
  TRIAGED: ['ENHANCED_VERIFICATION', 'INVESTIGATION', 'PAYMENT_HELD', 'CLEARED'],
  ENHANCED_VERIFICATION: ['INVESTIGATION', 'SYSTEM_ERROR_CONFIRMED', 'CLEARED', 'PAYMENT_HELD'],
  INVESTIGATION: ['SYSTEM_ERROR_CONFIRMED', 'PAYMENT_HELD', 'REFERRED_TO_LEGAL', 'CLEARED'],
  PAYMENT_HELD: ['INVESTIGATION', 'HOLD_RELEASED', 'REFERRED_TO_LEGAL', 'CLEARED'],
  SYSTEM_ERROR_CONFIRMED: ['CLAIM_CORRECTED'],
  CLAIM_CORRECTED: ['OVERPAYMENT_AVOIDED', 'HOLD_RELEASED', 'CLOSED'],
  OVERPAYMENT_AVOIDED: ['HOLD_RELEASED', 'CLOSED'],
  REFERRED_TO_LEGAL: ['CLOSED'],
  CLEARED: ['HOLD_RELEASED', 'CLOSED'],
  HOLD_RELEASED: ['CLOSED'],
  CLOSED: [],
};

export function canTransition(from: BnRiskStatus, to: BnRiskStatus): boolean {
  return BN_RISK_TRANSITIONS[from]?.includes(to) ?? false;
}
export function isTerminal(status: BnRiskStatus): boolean {
  return status === 'CLOSED';
}
