/**
 * BN Risk — Canonical risk categories and control actions (Slice 1).
 *
 * These enums are the single source of truth used by rule authors,
 * reporting, and the UI legend. Extending this list requires a data
 * migration for the category lookup table.
 */

export type BnRiskCategory =
  | 'CLAIMANT_MISREPRESENTATION'
  | 'IDENTITY_MISMATCH'
  | 'DUPLICATE_CLAIM'
  | 'OVERLAPPING_BENEFIT'
  | 'DUPLICATE_BANK_ACCOUNT'
  | 'UNUSUAL_BANK_ACCOUNT_CHANGE'
  | 'PAYMENT_REDIRECTION'
  | 'DEATH_DATE_CONFLICT'
  | 'PAYMENT_AFTER_DEATH'
  | 'ALTERED_OR_REUSED_EVIDENCE'
  | 'CONTRIBUTION_INCONSISTENCY'
  | 'EMPLOYER_INCONSISTENCY'
  | 'UNDECLARED_MEANS_TEST_INCOME'
  | 'ASSET_INCONSISTENCY'
  | 'UNUSUAL_MANUAL_OVERRIDE'
  | 'REPEATED_OFFICER_OVERRIDE'
  | 'BACKDATED_CLAIM_PATTERN'
  | 'HIGH_VALUE_PAYMENT_ANOMALY'
  | 'MULTIPLE_FAILED_PAYMENTS'
  | 'SYSTEM_CALCULATION_ERROR'
  | 'PRODUCT_CONFIGURATION_ERROR'
  | 'STAFF_PROCESSING_ERROR'
  | 'DATA_MIGRATION_ERROR'
  | 'SUSPECTED_COLLUSION'
  | 'OTHER';

export const BN_RISK_CATEGORIES: readonly BnRiskCategory[] = [
  'CLAIMANT_MISREPRESENTATION',
  'IDENTITY_MISMATCH',
  'DUPLICATE_CLAIM',
  'OVERLAPPING_BENEFIT',
  'DUPLICATE_BANK_ACCOUNT',
  'UNUSUAL_BANK_ACCOUNT_CHANGE',
  'PAYMENT_REDIRECTION',
  'DEATH_DATE_CONFLICT',
  'PAYMENT_AFTER_DEATH',
  'ALTERED_OR_REUSED_EVIDENCE',
  'CONTRIBUTION_INCONSISTENCY',
  'EMPLOYER_INCONSISTENCY',
  'UNDECLARED_MEANS_TEST_INCOME',
  'ASSET_INCONSISTENCY',
  'UNUSUAL_MANUAL_OVERRIDE',
  'REPEATED_OFFICER_OVERRIDE',
  'BACKDATED_CLAIM_PATTERN',
  'HIGH_VALUE_PAYMENT_ANOMALY',
  'MULTIPLE_FAILED_PAYMENTS',
  'SYSTEM_CALCULATION_ERROR',
  'PRODUCT_CONFIGURATION_ERROR',
  'STAFF_PROCESSING_ERROR',
  'DATA_MIGRATION_ERROR',
  'SUSPECTED_COLLUSION',
  'OTHER',
] as const;

/** Source modules that can emit signals into Benefits Risk. */
export type BnRiskSourceModule =
  | 'BN_CLAIM'
  | 'BN_AWARD'
  | 'BN_PAYMENT'
  | 'BN_MEANS_TEST'
  | 'BN_MORTALITY'
  | 'BN_OVERPAYMENT'
  | 'IP'
  | 'EMPLOYER'
  | 'MANUAL'
  | 'OTHER';

/** Operational recommendations available to a risk assessment. */
export type BnRiskControlAction =
  | 'NO_ACTION'
  | 'ENHANCED_VERIFICATION'
  | 'REQUEST_DOCUMENTS'
  | 'SUPERVISOR_REVIEW'
  | 'TEMPORARY_PAYMENT_HOLD'
  | 'PREVENT_PROFILE_CHANGE'
  | 'RECALCULATE_CLAIM'
  | 'CREATE_OVERPAYMENT_REVIEW'
  | 'CORRECT_SYSTEM_ERROR'
  | 'CORRECT_STAFF_ERROR'
  | 'REFER_TO_LEGAL'
  | 'REFER_TO_INVESTIGATION';

export const BN_RISK_CONTROL_ACTIONS: readonly BnRiskControlAction[] = [
  'NO_ACTION',
  'ENHANCED_VERIFICATION',
  'REQUEST_DOCUMENTS',
  'SUPERVISOR_REVIEW',
  'TEMPORARY_PAYMENT_HOLD',
  'PREVENT_PROFILE_CHANGE',
  'RECALCULATE_CLAIM',
  'CREATE_OVERPAYMENT_REVIEW',
  'CORRECT_SYSTEM_ERROR',
  'CORRECT_STAFF_ERROR',
  'REFER_TO_LEGAL',
  'REFER_TO_INVESTIGATION',
] as const;

/** Benefit-affecting actions that must require approval (maker-checker). */
export const BN_RISK_BENEFIT_AFFECTING_ACTIONS: readonly BnRiskControlAction[] = [
  'TEMPORARY_PAYMENT_HOLD',
  'PREVENT_PROFILE_CHANGE',
  'RECALCULATE_CLAIM',
  'CREATE_OVERPAYMENT_REVIEW',
  'CORRECT_SYSTEM_ERROR',
  'CORRECT_STAFF_ERROR',
  'REFER_TO_LEGAL',
  'REFER_TO_INVESTIGATION',
];

export function isBenefitAffectingAction(a: BnRiskControlAction): boolean {
  return BN_RISK_BENEFIT_AFFECTING_ACTIONS.includes(a);
}
