/**
 * Recommended Rule Group templates per benefit product type.
 * Used by Product Catalogue → Eligibility "Add from Rule Group" to surface
 * the canonical bundles for the current product.
 */
export const RECOMMENDED_GROUPS_BY_PRODUCT: Record<string, string[]> = {
  SICKNESS: ['COMMON_ELIGIBILITY','EMPLOYMENT_CHECKS','CONTRIBUTION_SHORT_TERM','MEDICAL_DOCUMENT_CHECKS','TIMING_CHECKS','SICKNESS_ELIGIBILITY'],
  MATERNITY: ['COMMON_ELIGIBILITY','EMPLOYMENT_CHECKS','CONTRIBUTION_SHORT_TERM','TIMING_CHECKS','MATERNITY_ELIGIBILITY'],
  EMPLOYMENT_INJURY: ['COMMON_ELIGIBILITY','EMPLOYMENT_CHECKS','EMPLOYMENT_INJURY_CHECKS','MEDICAL_DOCUMENT_CHECKS','TIMING_CHECKS'],
  INJURY: ['COMMON_ELIGIBILITY','EMPLOYMENT_CHECKS','EMPLOYMENT_INJURY_CHECKS','MEDICAL_DOCUMENT_CHECKS','TIMING_CHECKS'],
  AGE: ['COMMON_ELIGIBILITY','AGE_RULES','CONTRIBUTION_LONG_TERM'],
  PENSION: ['COMMON_ELIGIBILITY','AGE_RULES','CONTRIBUTION_LONG_TERM'],
  INVALIDITY: ['COMMON_ELIGIBILITY','AGE_RULES','CONTRIBUTION_LONG_TERM','MEDICAL_DOCUMENT_CHECKS','MEDICAL_BOARD_CHECKS'],
  FUNERAL: ['COMMON_ELIGIBILITY','DECEASED_CONTRIBUTION','DEATH_DOCUMENT_CHECKS','FUNERAL_EVIDENCE','TIMING_CHECKS'],
  SURVIVORS: ['COMMON_ELIGIBILITY','DECEASED_CONTRIBUTION','DEATH_DOCUMENT_CHECKS','SURVIVOR_DEPENDENCY'],
  SURVIVOR: ['COMMON_ELIGIBILITY','DECEASED_CONTRIBUTION','DEATH_DOCUMENT_CHECKS','SURVIVOR_DEPENDENCY'],
  ASSISTANCE: ['COMMON_ELIGIBILITY','MEANS_TEST_ELIGIBILITY'],
  NON_CONTRIBUTORY: ['COMMON_ELIGIBILITY','MEANS_TEST_ELIGIBILITY'],
};

/** Heuristic match — accepts product codes like "SICKNESS-2026", "MAT_BEN", etc. */
export function recommendedGroupsForProduct(productCode?: string | null): string[] {
  if (!productCode) return [];
  const code = productCode.toUpperCase();
  for (const [key, groups] of Object.entries(RECOMMENDED_GROUPS_BY_PRODUCT)) {
    if (code.includes(key)) return groups;
  }
  return [];
}
