import { supabase } from "@/integrations/supabase/client";
import { coreDmsService } from "./coreDmsService";

export type DmsTestStatus = "pending" | "running" | "pass" | "fail" | "skip";

export interface DmsTestResult {
  id: string;
  name: string;
  api: string;
  status: DmsTestStatus;
  ms?: number;
  error?: string;
  fix?: string;
  details?: any;
}

export interface DmsTestContext {
  userId: string;
  userCode: string;
  testCaseId?: string;
  uploadedLinkId?: string;
  uploadedDmsDocId?: string;
}

const TEST_FILE_TXT = "DMS-TEST-FILE\nGenerated by dmsApiTestService.\n";

function makeTestBlob(): Blob {
  return new Blob([TEST_FILE_TXT], { type: "text/plain" });
}

async function timed<T>(fn: () => Promise<T>): Promise<{ ms: number; value?: T; error?: any }> {
  const t0 = performance.now();
  try {
    const value = await fn();
    return { ms: Math.round(performance.now() - t0), value };
  } catch (error) {
    return { ms: Math.round(performance.now() - t0), error };
  }
}

export const dmsApiTestService = {
  async runAll(onUpdate: (r: DmsTestResult) => void): Promise<DmsTestResult[]> {
    const results: DmsTestResult[] = [];
    const push = (r: DmsTestResult) => { results.push(r); onUpdate(r); };

    const ctx: DmsTestContext = { userId: "", userCode: "TEST" };
    const { data: au } = await supabase.auth.getUser();
    ctx.userId = au?.user?.id || "";
    ctx.userCode = (au?.user?.email || "TEST").slice(0, 32);

    // 0. Config / connectivity
    {
      const t = await timed(() => coreDmsService.validateConfig());
      if (t.value?.ok) {
        push({ id: "config", name: "DMS config + connectivity", api: "coreDmsService.validateConfig", status: "pass", ms: t.ms, details: t.value });
      } else {
        push({
          id: "config", name: "DMS config + connectivity", api: "coreDmsService.validateConfig",
          status: "fail", ms: t.ms, error: t.value?.reason || String(t.error?.message || t.error),
          fix: "Set api_settings.setting_key='dms_service' with base_url and active=true.",
        });
        return results; // can't continue meaningfully
      }
    }

    // 1. Seed a temporary test case so we have an lg_case_id to link to.
    {
      const t = await timed(async () => {
        const lg_case_no = `TEST-DMS-${Date.now()}`;
        const { data, error } = await (supabase as any).from("lg_case").insert({
          lg_case_no, case_type_code: "CONTRIBUTION_RECOVERY", status_code: "OPEN",
          current_stage_code: "INTAKE", priority_code: "NORMAL",
          opened_date: new Date().toISOString().split("T")[0], is_legacy: false,
          source_mode: "MANUAL", summary: "DMS API harness", created_by: ctx.userCode,
        }).select("id").single();
        if (error) throw error;
        return data;
      });
      if (t.value) {
        ctx.testCaseId = t.value.id;
        push({ id: "seed", name: "Seed temporary lg_case", api: "supabase.lg_case.insert", status: "pass", ms: t.ms, details: t.value });
      } else {
        push({ id: "seed", name: "Seed temporary lg_case", api: "supabase.lg_case.insert", status: "fail", ms: t.ms, error: String(t.error?.message || t.error), fix: "Verify lg_case schema and required defaults." });
        return results;
      }
    }

    // 2. Upload raw bytes
    {
      const t = await timed(() => coreDmsService.uploadFile({
        file: makeTestBlob(),
        file_name: `dms-test-${Date.now()}.txt`,
        mime_type: "text/plain",
        user_code: ctx.userCode,
        link: {
          module_code: "LEGAL",
          lg_case_id: ctx.testCaseId!,
          document_category_code: "EVIDENCE",
          document_type_code: "SUPPORTING_EVIDENCE",
          title: "Harness upload",
        },
      }));
      if (t.value?.success) {
        ctx.uploadedLinkId = t.value.link_id || undefined;
        ctx.uploadedDmsDocId = t.value.dms_document_id || undefined;
        push({ id: "upload", name: "Upload raw file → DMS + create link", api: "core-dms-upload (raw)", status: "pass", ms: t.ms, details: t.value });
      } else {
        push({ id: "upload", name: "Upload raw file → DMS + create link", api: "core-dms-upload (raw)", status: "fail", ms: t.ms, error: String(t.error?.message || t.error), fix: "Check api_settings dms_service credentials and remote DMS reachability." });
      }
    }

    // 3. Upload with extra metadata (confidential + court_filed)
    {
      const t = await timed(() => coreDmsService.uploadFile({
        file: makeTestBlob(), file_name: `dms-test-meta-${Date.now()}.txt`, mime_type: "text/plain",
        user_code: ctx.userCode,
        link: {
          module_code: "LEGAL", lg_case_id: ctx.testCaseId!,
          document_category_code: "COURT", document_type_code: "COURT_FILING",
          title: "Harness metadata upload", confidential: true, court_filed: true,
          filed_date: new Date().toISOString().split("T")[0],
        },
      }));
      push({
        id: "upload_meta", name: "Upload with metadata (confidential + court_filed)", api: "core-dms-upload (metadata)",
        status: t.value?.success ? "pass" : "fail", ms: t.ms,
        error: t.value?.success ? undefined : String(t.error?.message || t.error),
        details: t.value,
      });
    }

    // 4. Get link by id
    if (ctx.uploadedLinkId) {
      const t = await timed(() => coreDmsService.getLinkById(ctx.uploadedLinkId!));
      push({ id: "get", name: "Get document link by id", api: "coreDmsService.getLinkById", status: t.value ? "pass" : "fail", ms: t.ms, error: t.error?.message, details: t.value });
    } else push({ id: "get", name: "Get document link by id", api: "coreDmsService.getLinkById", status: "skip" });

    // 5. Download/view URL
    if (ctx.uploadedLinkId) {
      const t = await timed(() => coreDmsService.viewByLink(ctx.uploadedLinkId!));
      push({ id: "view", name: "Resolve download/view URL", api: "coreDmsService.viewByLink", status: t.value ? "pass" : "fail", ms: t.ms, error: t.error?.message, details: t.value });
    } else push({ id: "view", name: "Resolve download/view URL", api: "coreDmsService.viewByLink", status: "skip" });

    // 6. Filter search
    {
      const t = await timed(() => coreDmsService.searchLinks({ lg_case_id: ctx.testCaseId!, limit: 10 }));
      push({ id: "search_filter", name: "Search by entity (lg_case_id)", api: "coreDmsService.searchLinks", status: (t.value?.length ?? 0) > 0 ? "pass" : "fail", ms: t.ms, error: t.error?.message, details: { count: t.value?.length } });
    }

    // 7. Text search
    {
      const t = await timed(() => coreDmsService.searchByText("Harness", ctx.testCaseId!));
      push({ id: "search_text", name: "Search by title/text", api: "coreDmsService.searchByText", status: (t.value?.length ?? 0) > 0 ? "pass" : "fail", ms: t.ms, error: t.error?.message, details: { count: t.value?.length } });
    }

    // 8. Version history
    if (ctx.uploadedDmsDocId) {
      const t = await timed(() => coreDmsService.getVersionHistory(ctx.uploadedDmsDocId!));
      push({ id: "versions", name: "Version history lookup", api: "coreDmsService.getVersionHistory", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message, details: { count: t.value?.length } });
    } else push({ id: "versions", name: "Version history lookup", api: "coreDmsService.getVersionHistory", status: "skip" });

    // 9. Link existing DMS document
    if (ctx.uploadedDmsDocId && ctx.testCaseId) {
      const t = await timed(() => coreDmsService.linkExistingToLegal({
        dms_document_id: ctx.uploadedDmsDocId!,
        user_code: ctx.userCode,
        file_name: "harness-existing-link.txt", mime_type: "text/plain",
        link: { module_code: "LEGAL", lg_case_id: ctx.testCaseId!, document_category_code: "EVIDENCE", document_type_code: "SUPPORTING_EVIDENCE", title: "Existing DMS link" },
      }));
      push({ id: "link_existing", name: "Link existing DMS document to case", api: "coreDmsService.linkExistingToLegal", status: t.value ? "pass" : "fail", ms: t.ms, error: t.error?.message, details: { id: t.value?.id } });
    } else push({ id: "link_existing", name: "Link existing DMS document to case", api: "coreDmsService.linkExistingToLegal", status: "skip" });

    // 10. Mark court filed
    if (ctx.uploadedLinkId) {
      const t = await timed(() => coreDmsService.markCourtFiled(ctx.uploadedLinkId!, true));
      push({ id: "court_filed", name: "Mark court filed", api: "coreDmsService.markCourtFiled", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message });
    } else push({ id: "court_filed", name: "Mark court filed", api: "coreDmsService.markCourtFiled", status: "skip" });

    // 11. Mark confidential
    if (ctx.uploadedLinkId) {
      const t = await timed(() => coreDmsService.setConfidential(ctx.uploadedLinkId!, true));
      push({ id: "confidential", name: "Mark confidential", api: "coreDmsService.setConfidential", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message });
    } else push({ id: "confidential", name: "Mark confidential", api: "coreDmsService.setConfidential", status: "skip" });

    // 12. Permission check
    {
      const t = await timed(() => coreDmsService.canViewConfidential(ctx.userId));
      push({ id: "perm", name: "Confidential view permission check", api: "coreDmsService.canViewConfidential", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message, details: { allowed: t.value } });
    }

    // 13. Audit trail visibility
    if (ctx.testCaseId) {
      const t = await timed(() => coreDmsService.getAuditForCase(ctx.testCaseId!, 20));
      push({ id: "audit", name: "Audit trail rows for test case", api: "system_audit_trail", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message, details: { count: t.value?.length } });
    } else push({ id: "audit", name: "Audit trail rows for test case", api: "system_audit_trail", status: "skip" });

    // 14. Archive link
    if (ctx.uploadedLinkId) {
      const t = await timed(() => coreDmsService.archiveLink(ctx.uploadedLinkId!));
      push({ id: "archive", name: "Archive (soft-delete) link", api: "coreDmsService.archiveLink", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message });
    } else push({ id: "archive", name: "Archive (soft-delete) link", api: "coreDmsService.archiveLink", status: "skip" });

    // 15. Unlink + cleanup
    if (ctx.testCaseId) {
      const t = await timed(async () => {
        const all = await coreDmsService.searchLinks({ lg_case_id: ctx.testCaseId!, limit: 50 });
        for (const row of all) {
          try { await coreDmsService.unlink(row.id, ctx.userCode); } catch { /* ignore */ }
        }
        await (supabase as any).from("lg_case").delete().eq("id", ctx.testCaseId);
      });
      push({ id: "cleanup", name: "Unlink test docs + delete test case", api: "coreDmsService.unlink + lg_case.delete", status: t.error ? "fail" : "pass", ms: t.ms, error: t.error?.message });
    } else push({ id: "cleanup", name: "Unlink test docs + delete test case", api: "coreDmsService.unlink", status: "skip" });

    return results;
  },
};
