import {
  Heart,
  Settings,
  FileText,
  ClipboardList,
  Users,
  Calculator,
  Globe,
  Inbox,
  GitBranch,
  Tag,
  AlertTriangle,
  Layers,
  MapPin,
  CreditCard,
  BookOpen,
  Monitor,
  FolderOpen,
  ClipboardCheck,
  Shield,
  CalendarDays,
  Package,
  Banknote,
  ListChecks,
  History,
  LayoutDashboard,
  UserCircle,
  Stethoscope,
  HeartHandshake,
  Wallet,
  BadgeCheck,
  PauseCircle,
  Wrench,
} from "lucide-react";
import { filterMenuByFeatures } from "@/lib/bn/featureToggles";

const _bnMenuItemsRaw = [
  {
    title: "Benefit Operations",
    icon: Heart,
    subItems: [
      {
        title: "Dashboard",
        url: "/bn/dashboard",
        icon: LayoutDashboard,
        requiresPermission: "benefits_management",
        description: "Benefits operations overview",
      },
      {
        title: "Register / Assist Application",
        url: "/bn/intake/register",
        icon: FileText,
        requiresPermission: "benefits_management",
        description: "Register or assist a new benefit application",
      },
      {
        title: "Person 360",
        url: "/bn/person-360",
        icon: UserCircle,
        requiresPermission: "benefits_management",
        description: "Unified claimant view",
      },
      {
        title: "Claim Worklist",
        url: "/bn/claims",
        icon: ClipboardList,
        requiresPermission: "benefits_management",
      },
      {
        title: "Claim Queue",
        url: "/bn/queue",
        icon: Inbox,
        requiresPermission: "benefits_management",
      },
      {
        title: "Approval Console",
        url: "/bn/approval",
        icon: ClipboardCheck,
        requiresPermission: "benefits_management",
        description: "Review and approve benefit decisions",
      },
      {
        title: "Historical Inquiry",
        url: "/bn/history",
        icon: History,
        requiresPermission: "benefits_management",
        description: "Search legacy claims and disbursement history",
      },
    ],
  },
  {
    title: "Benefit Payments",
    icon: Wallet,
    subItems: [
      {
        title: "Entitlements",
        url: "/bn/entitlements",
        icon: Shield,
        requiresPermission: "benefits_management",
        description: "Manage approved benefit rights and lifecycle",
      },
      {
        title: "Payables Queue",
        url: "/bn/payables",
        icon: CreditCard,
        requiresPermission: "benefits_management",
        description: "Manage payable instructions before payment issue",
      },
      {
        title: "Payment Schedules",
        url: "/bn/schedules",
        icon: CalendarDays,
        requiresPermission: "benefits_management",
        description: "Plan one-time and recurring benefit disbursements",
      },
      {
        title: "Batch Operations",
        url: "/bn/batches",
        icon: Package,
        requiresPermission: "benefits_management",
        description: "Group payables into controlled payment batches",
      },
      {
        title: "Payment Issue",
        url: "/bn/issue",
        icon: Banknote,
        requiresPermission: "benefits_management",
        description: "Issue outbound benefit disbursements",
      },
      {
        title: "Post-Issue Review",
        url: "/bn/post-issue",
        icon: ListChecks,
        requiresPermission: "benefits_management",
        description: "Complete claim-side updates after payment issue",
      },
      {
        title: "Payment History",
        url: "/bn/payment-history",
        icon: History,
        requiresPermission: "benefits_management",
        description: "Search disbursement history",
      },
    ],
  },
  {
    title: "Benefit Servicing",
    icon: HeartHandshake,
    subItems: [
      {
        title: "Life Certificates",
        url: "/bn/life-certificates",
        icon: BadgeCheck,
        requiresPermission: "benefits_management",
      },
      {
        title: "Medical Reviews",
        url: "/bn/medical-reviews",
        icon: Stethoscope,
        requiresPermission: "benefits_management",
      },
      {
        title: "Overpayments",
        url: "/bn/overpayments",
        icon: AlertTriangle,
        requiresPermission: "benefits_management",
      },
      {
        title: "Award Suspension",
        url: "/bn/award-suspension",
        icon: PauseCircle,
        requiresPermission: "benefits_management",
      },
      {
        title: "Survivors Processing",
        url: "/bn/survivors",
        icon: Users,
        requiresPermission: "benefits_management",
      },
    ],
  },
  {
    title: "Benefit Configuration",
    icon: Settings,
    subItems: [
      {
        title: "Product Catalog",
        url: "/bn/config/products",
        icon: Globe,
        requiresPermission: "benefits_management",
        description: "Main configuration centre: products, versions, rules, documents, workflow, screens",
      },
      {
        title: "Configuration Validation",
        url: "/bn/config/validation",
        icon: ClipboardCheck,
        requiresPermission: "benefits_management",
        description: "Validate product setup across all layers",
      },
      {
        title: "Formula Library",
        url: "/bn/config/formulas",
        icon: Calculator,
        requiresPermission: "benefits_management",
        description: "Reusable calculation formulas",
      },
      {
        title: "Document Library",
        url: "/bn/config/document-setup",
        icon: FolderOpen,
        requiresPermission: "benefits_management",
        description: "Reusable document types and profiles",
      },
      {
        title: "Rule Group Library",
        url: "/bn/config/rules",
        icon: BookOpen,
        requiresPermission: "benefits_management",
        description: "Classification of product rules",
      },
      {
        title: "Rule Version Governance",
        url: "/bn/config/rules-admin",
        icon: Shield,
        requiresPermission: "benefits_management",
        description: "Approve, publish, retire, and audit rule versions",
      },
      {
        title: "Screen & Fields",
        url: "/bn/config/screen-setup",
        icon: Monitor,
        requiresPermission: "benefits_management",
        description: "Screen templates and field metadata",
      },
      {
        title: "Transition Matrix",
        url: "/bn/config/transitions",
        icon: GitBranch,
        requiresPermission: "benefits_management",
        description: "Claim status transition rules",
      },
      {
        title: "Workbaskets",
        url: "/bn/config/workbaskets",
        icon: Layers,
        requiresPermission: "benefits_management",
        description: "Claim queues and workload distribution",
      },
      {
        title: "Reason Codes",
        url: "/bn/config/reason-codes",
        icon: Tag,
        requiresPermission: "benefits_management",
        description: "Denial, suspension, and escalation reasons",
      },
      {
        title: "Escalation Policies",
        url: "/bn/config/escalation",
        icon: AlertTriangle,
        requiresPermission: "benefits_management",
        description: "SLA breach and manual escalation rules",
      },
      {
        title: "Country Pack",
        url: "/bn/config/country",
        icon: MapPin,
        requiresPermission: "benefits_management",
        description: "Country-specific configuration pack",
      },
    ],
  },
];

export const bnMenuItems = filterMenuByFeatures(_bnMenuItemsRaw as any);
