import {
  Heart,
  Settings,
  FileText,
  ClipboardList,
  Users,
  Calculator,
  Globe,
  Inbox,
  FlaskConical,
  GitBranch,
  Tag,
  AlertTriangle,
  Layers,
  FileCheck,
  MapPin,
  CreditCard,
  Scale,
  Flag,
  BookOpen,
  Monitor,
  FolderOpen,
  TestTube2,
  ClipboardCheck,
  Shield,
  CalendarDays,
  Package,
  Banknote,
  ListChecks,
  History,
} from "lucide-react";
import { filterMenuByFeatures } from "@/lib/bn/featureToggles";

const _bnMenuItemsRaw = [
  {
    title: "Benefit Management",
    icon: Heart,
    subItems: [
      {
        title: "Claim Worklist",
        url: "/bn/claims",
        icon: ClipboardList,
        requiresPermission: "benefits_management",
      },
      {
        title: "Claim Queue",
        url: "/bn/queue",
        icon: Inbox,
        requiresPermission: "benefits_management",
      },
      {
        title: "Approval Console",
        url: "/bn/approval",
        icon: ClipboardCheck,
        requiresPermission: "benefits_management",
        description: "Review and approve benefit decisions",
      },
      {
        title: "Entitlements",
        url: "/bn/entitlements",
        icon: Shield,
        requiresPermission: "benefits_management",
        description: "Manage approved benefit rights and lifecycle",
      },
      {
        title: "Payables Queue",
        url: "/bn/payables",
        icon: CreditCard,
        requiresPermission: "benefits_management",
        description: "Manage payable instructions before payment issue",
      },
      {
        title: "Payment Schedules",
        url: "/bn/schedules",
        icon: CalendarDays,
        requiresPermission: "benefits_management",
        description: "Plan one-time and recurring benefit disbursements",
      },
      {
        title: "Batch Operations",
        url: "/bn/batches",
        icon: Package,
        requiresPermission: "benefits_management",
        description: "Group payables into controlled payment batches",
      },
      {
        title: "Payment Issue",
        url: "/bn/issue",
        icon: Banknote,
        requiresPermission: "benefits_management",
        description: "Issue outbound benefit disbursements to cl_cheques",
      },
      {
        title: "Post-Issue Review",
        url: "/bn/post-issue",
        icon: ListChecks,
        requiresPermission: "benefits_management",
        description: "Complete claim-side updates after payment issue",
      },
      {
        title: "Historical Inquiry",
        url: "/bn/history",
        icon: History,
        requiresPermission: "benefits_management",
        description: "Search and view legacy claims and disbursement history",
      },
      {
        title: "Register New Claim",
        url: "/bn/intake/register",
        icon: FileText,
        requiresPermission: "benefits_management",
      },
      {
        title: "Configuration",
        icon: Settings,
        requiresPermission: "benefits_management",
        subItems: [
          {
            title: "Product Catalog",
            url: "/bn/config/products",
            icon: Globe,
            requiresPermission: "benefits_management",
            description: "Configure benefit products, versions, rules, documents, workflow, and application requirements",
          },
          {
            title: "Rule Group Library",
            url: "/bn/config/rules",
            icon: BookOpen,
            requiresPermission: "benefits_management",
            description: "Reusable categories for organizing product rules",
          },
          {
            title: "Rule Version Governance",
            url: "/bn/config/rules-admin",
            icon: Shield,
            requiresPermission: "benefits_management",
            description: "Approve, publish, retire, and audit product rule versions",
          },
          {
            title: "Formula Templates",
            url: "/bn/config/formulas",
            icon: Calculator,
            requiresPermission: "benefits_management",
            description: "Reusable calculation formula library",
          },
          {
            title: "Document Setup",
            url: "/bn/config/document-setup",
            icon: FolderOpen,
            requiresPermission: "benefits_management",
            description: "Reusable document type and profile library",
          },
          {
            title: "Screen & Fields",
            url: "/bn/config/screen-setup",
            icon: Monitor,
            requiresPermission: "benefits_management",
            description: "Screen templates and field metadata",
          },
          {
            title: "Calculation Engine",
            url: "/bn/engine",
            icon: FlaskConical,
            requiresPermission: "benefits_management",
            description: "Run, simulate, and audit benefit calculations",
          },
          {
            title: "Transition Matrix",
            url: "/bn/config/transitions",
            icon: GitBranch,
            requiresPermission: "benefits_management",
            description: "Claim status transition rules",
          },
          {
            title: "Reason Codes",
            url: "/bn/config/reason-codes",
            icon: Tag,
            requiresPermission: "benefits_management",
            description: "Denial, suspension, and escalation reasons",
          },
          {
            title: "Workbaskets",
            url: "/bn/config/workbaskets",
            icon: Layers,
            requiresPermission: "benefits_management",
            description: "Claim queues and workload distribution",
          },
          {
            title: "Escalation Policies",
            url: "/bn/config/escalation",
            icon: AlertTriangle,
            requiresPermission: "benefits_management",
            description: "SLA breach and manual escalation rules",
          },
          {
            title: "Service Doc Types",
            url: "/bn/config/service-doc-types",
            icon: FileCheck,
            requiresPermission: "benefits_management",
            description: "Special document types for claims",
          },
        ],
      },
      {
        title: "Country Packs",
        icon: Flag,
        subItems: [
          {
            title: "Pack Overview",
            url: "/bn/config/country",
            icon: Globe,
            requiresPermission: "benefits_management",
            description: "Country pack completeness dashboard",
          },
          {
            title: "ID / SSN Rules",
            url: "/bn/config/country/id-rules",
            icon: FileCheck,
            requiresPermission: "benefits_management",
            description: "Country-specific ID validation rules",
          },
          {
            title: "Address Model",
            url: "/bn/config/country/address-model",
            icon: MapPin,
            requiresPermission: "benefits_management",
            description: "Country-specific address fields",
          },
          {
            title: "Participant Types",
            url: "/bn/config/country/participant-types",
            icon: Users,
            requiresPermission: "benefits_management",
            description: "Claimant and beneficiary types",
          },
          {
            title: "Payment Config",
            url: "/bn/config/country/payment-config",
            icon: CreditCard,
            requiresPermission: "benefits_management",
            description: "Payment methods and calendars",
          },
          {
            title: "Legal References",
            url: "/bn/config/country/legal-refs",
            icon: Scale,
            requiresPermission: "benefits_management",
            description: "Governing legislation with versioning",
          },
        ],
      },
      {
        title: "Simulation Engine",
        url: "/bn/simulation",
        icon: TestTube2,
        requiresPermission: "benefits_management",
        description: "Test benefit products in an isolated sandbox",
      },
    ],
  },
];

export const bnMenuItems = filterMenuByFeatures(_bnMenuItemsRaw as any);

