import {
  Shield,
  LayoutDashboard,
  FolderOpen,
  Calendar,
  MapPin,
  Bell,
  HandshakeIcon,
  FileText,
  TrendingUp,
  Settings,
  Scale,
  Users,
  ClipboardCheck,
  DollarSign,
  BarChart3,
  AlertTriangle,
  Building2,
  Gavel,
  ShieldAlert,
  Cog,
  Timer,
  Search,
  Target,
  Zap,
  Hash,
  ListChecks,
  Eye,
  Briefcase,
  UserCheck,
  Map,
  Network,
  ArrowRightLeft,
  Route,
  Activity,
  Hammer,
  HelpCircle,
} from "lucide-react";

export const complianceMenuItems = [
  {
    title: "Compliance & Enforcement",
    icon: Shield,
    subItems: [
      // ── 1. Workbench — dashboards, monitoring, queues ──
      {
        title: "Workbench",
        icon: LayoutDashboard,
        requiresPermission: "manage_compliance",
        description: "Dashboards, monitoring, and operational queues",
        subItems: [
          {
            title: "Manager Dashboard",
            url: "/compliance/workbench/manager",
            icon: LayoutDashboard,
            requiresPermission: "manage_compliance",
            description: "Overview of all compliance metrics and KPIs",
          },
          {
            title: "Inspector Dashboard",
            url: "/compliance/workbench/inspector",
            icon: UserCheck,
            requiresPermission: "manage_compliance",
            description: "Field inspector workload and assignments",
          },
          {
            title: "Legal Dashboard",
            url: "/compliance/workbench/legal",
            icon: Gavel,
            requiresPermission: "manage_compliance",
            description: "Legal escalation pipeline and court tracking",
          },
          {
            title: "Analytics",
            url: "/compliance/workbench/analytics",
            icon: TrendingUp,
            requiresPermission: "manage_compliance",
            description: "Enterprise-wide compliance performance and trends",
          },
          {
            title: "Monitoring",
            url: "/compliance/workbench/monitoring",
            icon: Activity,
            requiresPermission: "manage_compliance",
            description: "Live compliance monitoring and alerts",
          },
          {
            title: "Assignment Queues",
            url: "/compliance/workbench/queues",
            icon: Users,
            requiresPermission: "manage_compliance",
            description: "View and manage all assignment queues across zones",
          },
          {
            title: "Review Queue",
            url: "/compliance/workbench/review-queue",
            icon: Eye,
            requiresPermission: "manage_compliance",
            description: "Violations assigned for supervisor evaluation",
          },
          {
            title: "Reassign / Workload",
            url: "/compliance/workbench/reassignment",
            icon: ArrowRightLeft,
            requiresPermission: "manage_compliance",
            description: "Officer workload distribution and reassignment",
          },
        ],
      },

      // ── 2. Violations ──
      {
        title: "Violations",
        icon: AlertTriangle,
        requiresPermission: "manage_compliance",
        description: "Manage compliance violations",
        subItems: [
          {
            title: "All Violations",
            url: "/compliance/violations",
            icon: FolderOpen,
            requiresPermission: "manage_compliance",
            description: "View and manage all compliance violations",
          },
          {
            title: "Manual Violation Entry",
            url: "/compliance/violations/manual-entry",
            icon: AlertTriangle,
            requiresPermission: "manage_compliance",
            description: "Create violations from field observations or scouting",
          },
        ],
      },

      // ── 3. Cases ──
      {
        title: "Cases",
        icon: Briefcase,
        requiresPermission: "manage_compliance",
        description: "Case management with full lifecycle",
        subItems: [
          {
            title: "Case Management",
            url: "/compliance/cases",
            icon: Briefcase,
            requiresPermission: "manage_compliance",
            description: "View and manage all compliance cases",
          },
          {
            title: "Case Queue",
            url: "/compliance/cases/queue",
            icon: ListChecks,
            requiresPermission: "manage_compliance",
            description: "Prioritized queue of cases requiring action",
          },
          {
            title: "Penalties",
            url: "/compliance/cases/penalties",
            icon: Hammer,
            requiresPermission: "manage_compliance",
            description: "Issue and manage compliance penalties",
          },
        ],
      },

      // ── 4. Field — planning, execution, inspections, employer views ──
      {
        title: "Field",
        icon: MapPin,
        requiresPermission: "manage_compliance",
        description: "Field planning, execution, inspections, and employer views",
        subItems: [
          {
            title: "Plan Builder",
            url: "/compliance/field/plan-builder",
            icon: Calendar,
            requiresPermission: "create_weekly_plan",
            description: "Create and manage weekly audit plans",
          },
          {
            title: "My Plans",
            url: "/compliance/field/my-plans",
            icon: Calendar,
            requiresPermission: "manage_compliance",
            description: "View my weekly plans and status",
          },
          {
            title: "Review & Approve Plans",
            url: "/compliance/field/pending-review",
            icon: ClipboardCheck,
            requiresPermission: "approve_weekly_plan",
            description: "Review and approve submitted inspector plans",
          },
          {
            title: "Field Execution",
            url: "/compliance/field/execution",
            icon: MapPin,
            requiresPermission: "conduct_inspections",
            description: "Check-in, execute visits, collect evidence",
          },
          {
            title: "Field Operations",
            url: "/compliance/field/operations",
            icon: Search,
            requiresPermission: "manage_compliance",
            description: "Ad-hoc field work and standalone visits",
          },
          {
            title: "Inspections",
            url: "/compliance/field/inspections",
            icon: ClipboardCheck,
            requiresPermission: "manage_compliance",
            description: "Schedule and manage inspections",
          },
          {
            title: "Audit Management",
            url: "/compliance/field/audit-management",
            icon: ClipboardCheck,
            requiresPermission: "manage_compliance",
            description: "Manage audit assignments and case-based audits",
          },
          {
            title: "Employer Findings",
            url: "/compliance/field/findings",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "View all findings for employers",
          },
          {
            title: "Employer 360°",
            url: "/compliance/field/employer-360",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "Comprehensive employer profile and compliance view",
          },
          {
            title: "Employer Statements",
            url: "/compliance/field/employer-statements",
            icon: FileText,
            requiresPermission: "view_financial_data",
            description: "Generate as-of-date employer statements",
          },
          {
            title: "Weekly Report Submission",
            url: "/compliance/field/weekly-report",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "Submit weekly inspection reports",
          },
          {
            title: "Weekly Reports",
            url: "/compliance/field/weekly-reports",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "View submitted weekly reports",
          },
          {
            title: "All Weekly Reports",
            url: "/compliance/field/all-reports",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "Supervisor view of all officer weekly reports",
          },
          {
            title: "Weekly Report Review",
            url: "/compliance/field/weekly-report-review",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "Supervisor review of submitted weekly reports",
          },
          {
            title: "My Upcoming Audits",
            url: "/compliance/field/my-upcoming",
            icon: Calendar,
            requiresPermission: "manage_compliance",
            description: "View upcoming audit assignments",
          },
          {
            title: "Sampling Dashboard",
            url: "/compliance/field/sampling",
            icon: Target,
            requiresPermission: "manage_compliance",
            description: "Audit sampling dashboard and candidate selection",
          },
          {
            title: "Monthly Candidates",
            url: "/compliance/field/sampling/candidates",
            icon: Target,
            requiresPermission: "manage_compliance",
            description: "Monthly audit candidate shortlist",
          },
        ],
      },

      // ── 5. Enforcement — legal, notices, arrangements, waivers ──
      {
        title: "Enforcement",
        icon: Scale,
        requiresPermission: "manage_compliance",
        description: "Legal escalation, notices, arrangements, and waivers",
        subItems: [
          {
            title: "Legal Recommendation Queue",
            url: "/compliance/enforcement/recommendation-queue",
            icon: ListChecks,
            requiresPermission: "manage_compliance",
            description: "Cases recommended for legal escalation, pending approval",
          },
          {
            title: "Legal Queue",
            url: "/compliance/enforcement/legal-queue",
            icon: Scale,
            requiresPermission: "manage_compliance",
            description: "Cases already escalated to legal",
          },
          {
            title: "Legal Proceedings",
            url: "/compliance/enforcement/proceedings",
            icon: Gavel,
            requiresPermission: "manage_compliance",
            description: "Active legal cases and court tracking",
          },
          {
            title: "Notices",
            url: "/compliance/enforcement/notices",
            icon: Bell,
            requiresPermission: "manage_compliance",
            description: "Send and track compliance notices",
          },
          {
            title: "Payment Arrangements",
            url: "/compliance/enforcement/arrangements",
            icon: HandshakeIcon,
            requiresPermission: "manage_compliance",
            description: "View and manage payment arrangements",
          },
          {
            title: "Breach Monitoring",
            url: "/compliance/enforcement/breaches",
            icon: ShieldAlert,
            requiresPermission: "manage_compliance",
            description: "Automatic breach detection and tracking",
          },
          {
            title: "Waivers & Overrides",
            url: "/compliance/enforcement/waivers",
            icon: FileText,
            requiresPermission: "manage_compliance",
            description: "Waiver requests and approval workflow",
          },
        ],
      },

      // ── 6. Reports ──
      {
        title: "Reports",
        icon: BarChart3,
        requiresPermission: "generate_reports",
        description: "Compliance analytics and performance reports",
        subItems: [
          {
            title: "Violations Reports",
            icon: FileText,
            requiresPermission: "generate_reports",
            description: "Violation analytics, trends, and status tracking",
            subItems: [
              { title: "Violations by Status", url: "/compliance/reports/violations-analytics", icon: FileText, requiresPermission: "generate_reports" },
              { title: "Violations by Type", url: "/compliance/reports/violations-analytics", icon: FileText, requiresPermission: "generate_reports" },
              { title: "Violation Resolution Time", url: "/compliance/reports/violations-analytics", icon: FileText, requiresPermission: "generate_reports" },
              { title: "Violations by Zone", url: "/compliance/reports/violations-analytics", icon: FileText, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Inspector Performance",
            icon: Users,
            requiresPermission: "generate_reports",
            description: "Field activity, plan compliance, and productivity metrics",
            subItems: [
              { title: "Weekly Plan Compliance", url: "/compliance/reports/inspector-performance", icon: Users, requiresPermission: "generate_reports" },
              { title: "Field Activities Summary", url: "/compliance/reports/inspector-performance", icon: Users, requiresPermission: "generate_reports" },
              { title: "Check-In/Check-Out Audit", url: "/compliance/reports/inspector-performance", icon: Users, requiresPermission: "generate_reports" },
              { title: "Violations Handled by Inspector", url: "/compliance/reports/inspector-performance", icon: Users, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "C3 Compliance Reports",
            icon: ClipboardCheck,
            requiresPermission: "generate_reports",
            description: "C3 submission rates, timeliness, and employer compliance",
            subItems: [
              { title: "On-Time vs Late Submissions", url: "/compliance/reports/c3-compliance", icon: ClipboardCheck, requiresPermission: "generate_reports" },
              { title: "Missing C3 Submissions", url: "/compliance/reports/c3-compliance", icon: ClipboardCheck, requiresPermission: "generate_reports" },
              { title: "C3 Without Payment", url: "/compliance/reports/c3-compliance", icon: ClipboardCheck, requiresPermission: "generate_reports" },
              { title: "Compliance Rate by Zone", url: "/compliance/reports/c3-compliance", icon: ClipboardCheck, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Arrears & Collections",
            icon: DollarSign,
            requiresPermission: "generate_reports",
            description: "Outstanding balances, payment trends, and recovery metrics",
            subItems: [
              { title: "Total Arrears by Zone", url: "/compliance/reports/arrears", icon: DollarSign, requiresPermission: "generate_reports" },
              { title: "Arrears Aging Analysis", url: "/compliance/reports/arrears", icon: DollarSign, requiresPermission: "generate_reports" },
              { title: "Collections Over Time", url: "/compliance/reports/arrears", icon: DollarSign, requiresPermission: "generate_reports" },
              { title: "Top 50 Arrears Employers", url: "/compliance/reports/arrears", icon: DollarSign, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Audit & Inspection Reports",
            icon: BarChart3,
            requiresPermission: "generate_reports",
            description: "Audit findings, inspection results, and risk assessments",
            subItems: [
              { title: "Audit Completion Rate", url: "/compliance/reports/audit", icon: BarChart3, requiresPermission: "generate_reports" },
              { title: "Findings by Severity", url: "/compliance/reports/audit", icon: BarChart3, requiresPermission: "generate_reports" },
              { title: "Inspection Coverage by Zone", url: "/compliance/reports/audit", icon: BarChart3, requiresPermission: "generate_reports" },
              { title: "Risk-Based Audit Results", url: "/compliance/reports/audit", icon: BarChart3, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Payment Arrangements",
            icon: HandshakeIcon,
            requiresPermission: "generate_reports",
            description: "Active arrangements, defaults, and compliance tracking",
            subItems: [
              { title: "Active Arrangements", url: "/compliance/reports/arrangements", icon: HandshakeIcon, requiresPermission: "generate_reports" },
              { title: "Defaulted Arrangements", url: "/compliance/reports/arrangements", icon: HandshakeIcon, requiresPermission: "generate_reports" },
              { title: "Arrangement Success Rate", url: "/compliance/reports/arrangements", icon: HandshakeIcon, requiresPermission: "generate_reports" },
              { title: "Installment Payment Trends", url: "/compliance/reports/arrangements", icon: HandshakeIcon, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Legal Escalation",
            icon: Scale,
            requiresPermission: "generate_reports",
            description: "Cases escalated to legal, court proceedings, and outcomes",
            subItems: [
              { title: "Violations Escalated to Legal", url: "/compliance/reports/legal", icon: Scale, requiresPermission: "generate_reports" },
              { title: "Legal Stage Distribution", url: "/compliance/reports/legal", icon: Scale, requiresPermission: "generate_reports" },
              { title: "Court Proceedings Status", url: "/compliance/reports/legal", icon: Scale, requiresPermission: "generate_reports" },
              { title: "Judgements & Enforcement", url: "/compliance/reports/legal", icon: Scale, requiresPermission: "generate_reports" },
            ],
          },
          {
            title: "Trend Analysis",
            icon: TrendingUp,
            requiresPermission: "generate_reports",
            description: "Historical trends and predictive analytics",
            subItems: [
              { title: "Compliance Trends (12 months)", url: "/compliance/reports/trends", icon: TrendingUp, requiresPermission: "generate_reports" },
              { title: "Violation Creation Trends", url: "/compliance/reports/trends", icon: TrendingUp, requiresPermission: "generate_reports" },
              { title: "Resolution Rate Trends", url: "/compliance/reports/trends", icon: TrendingUp, requiresPermission: "generate_reports" },
              { title: "Financial Recovery Trends", url: "/compliance/reports/trends", icon: TrendingUp, requiresPermission: "generate_reports" },
            ],
          },
        ],
      },

      // ── 7. Admin — policy, automation, ledger, org, diagnostics ──
      {
        title: "Admin",
        icon: Settings,
        requiresPermission: "manage_compliance",
        description: "Policy, automation, ledger, organization, and diagnostics",
        subItems: [
          // ── 7.1 Policy & Rules ──
          {
            title: "Policy & Rules",
            icon: Scale,
            requiresPermission: "manage_compliance",
            description: "Detection rules, violation types, risk policies, and templates",
            subItems: [
              { title: "Rule Engine", url: "/compliance/admin/settings/rule-engine", icon: Cog, requiresPermission: "manage_compliance", description: "Configure detection, calculation, and escalation rules" },
              { title: "Violation Types", url: "/compliance/admin/settings/violation-types", icon: AlertTriangle, requiresPermission: "manage_compliance", description: "Configure violation type definitions" },
              { title: "Assignment Routing", url: "/compliance/admin/settings/assignment-routing", icon: Route, requiresPermission: "manage_compliance", description: "Rules for routing violations to queues" },
              { title: "Risk & Escalation Policy", url: "/compliance/admin/settings/risk-policy", icon: TrendingUp, requiresPermission: "manage_compliance", description: "Risk factors, weights, bands, and legal escalation thresholds" },
              { title: "Sampling Settings", url: "/compliance/admin/settings/sampling", icon: Target, requiresPermission: "manage_compliance", description: "Risk sampling parameters and configuration" },
              { title: "Reference Numbering", url: "/compliance/admin/settings/number-templates", icon: Hash, requiresPermission: "manage_compliance", description: "Auto-numbering schemes for violations, cases, notices" },
              { title: "Templates", url: "/compliance/admin/settings/templates", icon: FileText, requiresPermission: "manage_compliance", description: "Manage compliance notification templates" },
            ],
          },
          // ── 7.2 Automation & Jobs ──
          {
            title: "Automation & Jobs",
            icon: Zap,
            requiresPermission: "manage_compliance",
            description: "Scheduled compliance automation jobs",
            subItems: [
              { title: "Job Configuration", url: "/compliance/admin/automation/jobs", icon: Cog, requiresPermission: "manage_compliance", description: "Configure and manage automation jobs" },
              { title: "Job History", url: "/compliance/admin/automation/history", icon: Timer, requiresPermission: "manage_compliance", description: "View job execution history and logs" },
              { title: "Employer Compliance Jobs", url: "/compliance/admin/automation/employer-jobs", icon: Zap, requiresPermission: "manage_compliance", description: "Employer-specific compliance scan jobs" },
            ],
          },
          // ── 7.3 Integrations & Ledger ──
          {
            title: "Integrations & Ledger",
            icon: ArrowRightLeft,
            requiresPermission: "manage_compliance",
            description: "Ledger synchronization, posting framework, and operations",
            subItems: [
              { title: "C3 Ledger Sync", url: "/compliance/admin/settings/c3-ledger-sync", icon: ClipboardCheck, requiresPermission: "manage_compliance", description: "Sync C3 ledger data" },
              { title: "Payment Ledger Sync", url: "/compliance/admin/settings/payment-ledger-sync", icon: DollarSign, requiresPermission: "manage_compliance", description: "Sync payment ledger data" },
              { title: "Ledger Administration", url: "/compliance/admin/settings/ledger-admin", icon: Settings, requiresPermission: "manage_compliance", description: "Ledger administration and reconciliation" },
              { title: "Ledger Posting Framework", url: "/compliance/admin/settings/ledger-posting", icon: Activity, requiresPermission: "manage_compliance", description: "Incremental posting, reconciliation, backfill, and rebuild" },
              { title: "Ledger Operations", url: "/compliance/admin/settings/ledger-operations", icon: Eye, requiresPermission: "manage_compliance", description: "Operational dashboard for posting health and manual reruns" },
              { title: "Ledger Help & SOP", url: "/compliance/admin/settings/ledger-help", icon: HelpCircle, requiresPermission: "manage_compliance", description: "Role-based SOPs, help manual, and troubleshooting" },
            ],
          },
          // ── 7.4 Organization & Routing ──
          {
            title: "Geography",
            icon: Map,
            requiresPermission: "manage_compliance",
            description: "Zone and territory configuration",
            subItems: [
              { title: "Zones", url: "/compliance/admin/geography/zones", icon: Map, requiresPermission: "manage_compliance", description: "Enterprise compliance zone definitions" },
              { title: "Office-to-Zone Mapping", url: "/compliance/admin/geography/office-zone-mapping", icon: Building2, requiresPermission: "manage_compliance", description: "Map SSB office codes to compliance zones" },
              { title: "Village-to-Zone Mapping", url: "/compliance/admin/geography/village-zone-mapping", icon: MapPin, requiresPermission: "manage_compliance", description: "Granular village-level routing" },
            ],
          },
          {
            title: "Staff",
            icon: UserCheck,
            requiresPermission: "manage_compliance",
            description: "Officer management and supervisor hierarchy",
            subItems: [
              { title: "Officers / Inspectors", url: "/compliance/admin/staff/officers", icon: UserCheck, requiresPermission: "manage_compliance", description: "Compliance officers and field inspectors" },
              { title: "Queue Members", url: "/compliance/admin/staff/queue-members", icon: Users, requiresPermission: "manage_compliance", description: "Officers enrolled in assignment queues" },
              { title: "Supervisor Hierarchy", url: "/compliance/admin/staff/supervisors", icon: Network, requiresPermission: "manage_compliance", description: "Inspector-to-supervisor reporting structure" },
              { title: "Link Legacy Inspectors", url: "/compliance/admin/staff/link-legacy", icon: UserCheck, requiresPermission: "manage_compliance", description: "Map legacy inspector records to system profiles" },
            ],
          },
          // ── 7.5 Testing & Diagnostics ──
          {
            title: "Testing & Diagnostics",
            icon: Search,
            requiresPermission: "manage_compliance",
            description: "Simulators, diagnostics, and schema tools",
            subItems: [
              { title: "Rule Simulator", url: "/compliance/admin/tools/rule-simulator", icon: Zap, requiresPermission: "manage_compliance", description: "Dry-run simulation of detection, calculation, and escalation rules" },
              { title: "Risk Simulator", url: "/compliance/admin/tools/risk-simulator", icon: Zap, requiresPermission: "manage_compliance", description: "Test employer risk scoring with what-if scenarios" },
              { title: "DB Diagram", url: "/db-diagram", icon: Network, requiresPermission: "manage_compliance", description: "Visual schema diagram for compliance tables" },
            ],
          },
        ],
      },
    ],
  },
];
