import { useState, useMemo } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { RichTextEditor } from "@/components/ui/rich-text-editor";
import { Plus, Pencil, Trash2, Search, ChevronDown, ChevronRight } from "lucide-react";
import { useTextBlocks, useSaveTextBlock, useDeleteTextBlock, previewNextTextBlockCode, type TextBlock } from "@/hooks/org/useTextBlock";
import { useAppModules } from "@/hooks/org/useAppModules";

const CATEGORIES = ["disclaimer", "footer", "instruction", "notice", "warning", "header", "consent", "other"];

const KNOWN_SEED_PREFIXES = [
  "GLOBAL.", "PAY.", "C3.", "CE.", "BN.", "ER.", "IP.", "SE.", "OA.", "MT.", "NOTIF.", "LG.",
];

function isSeed(b: TextBlock) {
  if (!KNOWN_SEED_PREFIXES.some((p) => b.text_block_code.startsWith(p))) return false;
  // Treat untouched seeds (created==updated within 5s) as Seed
  const c = new Date(b.created_at).getTime();
  const u = new Date(b.updated_at).getTime();
  return Math.abs(u - c) < 5000;
}

export default function TextBlocksPage() {
  const { data: blocks = [], isLoading } = useTextBlocks();
  const { data: modules = [] } = useAppModules({ enabledOnly: true, rootOnly: true });
  const save = useSaveTextBlock();
  const del = useDeleteTextBlock();

  const [search, setSearch] = useState("");
  const [moduleFilter, setModuleFilter] = useState<string>("__all");
  const [categoryFilter, setCategoryFilter] = useState<string>("__all");
  const [editing, setEditing] = useState<Partial<TextBlock> | null>(null);
  const [codePreview, setCodePreview] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});

  // Refresh the auto-generated code preview whenever the module scope changes on a NEW block.
  useMemo(() => {
    if (editing && !editing.id) {
      previewNextTextBlockCode(editing.module_code).then(setCodePreview);
    } else {
      setCodePreview(null);
    }
  }, [editing?.module_code, editing?.id]);


  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return blocks.filter((b) => {
      if (moduleFilter !== "__all" && (b.module_code ?? "__none") !== moduleFilter) return false;
      if (categoryFilter !== "__all" && (b.category ?? "__none") !== categoryFilter) return false;
      if (!q) return true;
      return (
        b.text_block_code.toLowerCase().includes(q) ||
        b.name.toLowerCase().includes(q) ||
        (b.category ?? "").toLowerCase().includes(q) ||
        (b.content_text ?? "").toLowerCase().includes(q)
      );
    });
  }, [blocks, search, moduleFilter, categoryFilter]);

  const grouped = useMemo(() => {
    const map = new Map<string, TextBlock[]>();
    for (const b of filtered) {
      const key = b.module_code ?? "__shared";
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(b);
    }
    return Array.from(map.entries())
      .map(([key, items]) => ({
        key,
        label: key === "__shared" ? "Shared / Unscoped" : (modules.find((m) => m.name === key)?.display_name ?? key),
        items: items.sort((a, b) =>
          (a.category ?? "").localeCompare(b.category ?? "") ||
          a.text_block_code.localeCompare(b.text_block_code),
        ),
      }))
      .sort((a, b) => a.label.localeCompare(b.label));
  }, [filtered, modules]);

  const handleSave = async () => {
    if (!editing?.name) return;
    // On create, text_block_code is auto-generated by the hook via core_generate_number.
    await save.mutateAsync({
      ...editing,
      language_code: editing.language_code ?? "en",
      version_no: editing.version_no ?? 1,
      is_active: editing.is_active ?? true,
    });
    setEditing(null);
  };


  return (
    <div className="min-h-screen w-full bg-muted/30">
      <div className="max-w-7xl mx-auto p-6 space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Text Blocks</h1>
            <p className="text-sm text-muted-foreground mt-1">
              Reusable content (disclaimers, notices, instructions, footers). Templates, documents and notices reference these by code.
            </p>
          </div>
          <Button onClick={() => setEditing({ language_code: "en", version_no: 1, is_active: true })}>
            <Plus className="h-4 w-4 mr-2" /> New Text Block
          </Button>
        </div>

        <div className="flex flex-wrap gap-2 items-center">
          <div className="relative flex-1 min-w-[240px]">
            <Search className="h-4 w-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search code, name, content…"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>
          <Select value={moduleFilter} onValueChange={setModuleFilter}>
            <SelectTrigger className="w-[200px]"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="__all">All modules</SelectItem>
              <SelectItem value="__none">— Shared / Unscoped —</SelectItem>
              {modules.map((m) => (
                <SelectItem key={m.id} value={m.name}>{m.display_name ?? m.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="w-[180px]"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="__all">All categories</SelectItem>
              {CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>

        {isLoading ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : grouped.length === 0 ? (
          <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">
            No text blocks match your filters.
          </CardContent></Card>
        ) : (
          <div className="space-y-4">
            {grouped.map((group) => {
              const isCollapsed = collapsed[group.key];
              return (
                <div key={group.key} className="space-y-2">
                  <button
                    type="button"
                    onClick={() => setCollapsed((s) => ({ ...s, [group.key]: !isCollapsed }))}
                    className="flex items-center gap-2 text-sm font-semibold w-full text-left"
                  >
                    {isCollapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                    <span>{group.label}</span>
                    <Badge variant="secondary" className="text-xs">{group.items.length}</Badge>
                  </button>
                  {!isCollapsed && (
                    <div className="grid gap-2">
                      {group.items.map((b) => (
                        <Card key={b.id} className="hover:border-primary transition-colors">
                          <CardContent className="py-3 flex items-start justify-between gap-4">
                            <div className="min-w-0 flex-1">
                              <div className="flex items-center gap-2 flex-wrap">
                                <h3 className="font-medium truncate text-sm">{b.name}</h3>
                                <code className="text-[11px] bg-muted px-1.5 py-0.5 rounded">{b.text_block_code}</code>
                                {b.category && <Badge variant="outline" className="text-[10px] capitalize">{b.category}</Badge>}
                                <Badge variant="outline" className="text-[10px]">v{b.version_no}</Badge>
                                <Badge variant="outline" className="text-[10px]">{b.language_code}</Badge>
                                {isSeed(b) && <Badge variant="secondary" className="text-[10px]">Seed</Badge>}
                                {!b.is_active && <Badge variant="destructive" className="text-[10px]">Inactive</Badge>}
                              </div>
                              <p className="text-xs text-muted-foreground mt-1 line-clamp-2">
                                {b.content_text ?? b.content_html?.replace(/<[^>]+>/g, "") ?? "(no content)"}
                              </p>
                            </div>
                            <div className="flex gap-1 shrink-0">
                              <Button size="sm" variant="ghost" onClick={() => setEditing(b)}>
                                <Pencil className="h-4 w-4" />
                              </Button>
                              <Button size="sm" variant="ghost" onClick={() => {
                                if (confirm(`Delete "${b.name}"?`)) del.mutate(b.id);
                              }}>
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </div>
                          </CardContent>
                        </Card>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}

        <Dialog open={!!editing} onOpenChange={(o) => !o && setEditing(null)}>
          <DialogContent className="max-w-3xl">
            <DialogHeader>
              <DialogTitle>{editing?.id ? "Edit" : "New"} Text Block</DialogTitle>
            </DialogHeader>
            <div className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs">Code *</Label>
                  <Input
                    value={editing?.text_block_code ?? ""}
                    disabled={!!editing?.id}
                    onChange={(e) => setEditing({ ...editing, text_block_code: e.target.value.toUpperCase() })}
                    placeholder="MODULE.NAME"
                  />
                </div>
                <div>
                  <Label className="text-xs">Name *</Label>
                  <Input
                    value={editing?.name ?? ""}
                    onChange={(e) => setEditing({ ...editing, name: e.target.value })}
                  />
                </div>
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <Label className="text-xs">Category</Label>
                  <Select value={editing?.category ?? ""} onValueChange={(v) => setEditing({ ...editing, category: v })}>
                    <SelectTrigger><SelectValue placeholder="—" /></SelectTrigger>
                    <SelectContent>
                      {CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-xs">Module</Label>
                  <Select value={editing?.module_code ?? "__none"} onValueChange={(v) => setEditing({ ...editing, module_code: v === "__none" ? null : v })}>
                    <SelectTrigger><SelectValue placeholder="Shared" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="__none">Shared / All modules</SelectItem>
                      {modules.map((m) => <SelectItem key={m.id} value={m.name}>{m.display_name ?? m.name}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-xs">Language</Label>
                  <Input
                    value={editing?.language_code ?? "en"}
                    onChange={(e) => setEditing({ ...editing, language_code: e.target.value })}
                  />
                </div>
              </div>
              <div>
                <Label className="text-xs">Content (rich text)</Label>
                <RichTextEditor
                  value={editing?.content_html ?? ""}
                  onChange={(html) => {
                    const tmp = document.createElement("div");
                    tmp.innerHTML = html;
                    setEditing({ ...editing, content_html: html, content_text: tmp.textContent ?? "" });
                  }}
                />
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <Label className="text-xs">Effective From</Label>
                  <Input type="date" value={editing?.effective_from ?? ""} onChange={(e) => setEditing({ ...editing, effective_from: e.target.value || null })} />
                </div>
                <div>
                  <Label className="text-xs">Effective To</Label>
                  <Input type="date" value={editing?.effective_to ?? ""} onChange={(e) => setEditing({ ...editing, effective_to: e.target.value || null })} />
                </div>
                <div>
                  <Label className="text-xs">Version</Label>
                  <Input type="number" value={editing?.version_no ?? 1} onChange={(e) => setEditing({ ...editing, version_no: Number(e.target.value) || 1 })} />
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="ghost" onClick={() => setEditing(null)}>Cancel</Button>
              <Button onClick={handleSave} disabled={save.isPending}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}
