// Centralised catalog for the Official Communication Templates designer.
// Categories, document types, tokens, content blocks and design defaults.

export interface TemplateCategoryGroup {
  category: string;
  description: string;
  subcategories: string[];
}

export const TEMPLATE_CATEGORIES: TemplateCategoryGroup[] = [
  {
    category: "Official Letters",
    description: "General correspondence carrying the SSB letterhead.",
    subcategories: [
      "Standard Letter",
      "Legal Letter",
      "Benefits Letter",
      "Compliance Letter",
      "Internal Memo",
      "Board Communication",
    ],
  },
  {
    category: "Certificates",
    description: "Issued certificates used as proof of status, contribution or benefit.",
    subcategories: [
      "Certificate",
      "Employer Certificate",
      "Contribution Certificate",
      "Benefit Certificate",
    ],
  },
  {
    category: "Statements",
    description: "Periodic financial and contribution statements.",
    subcategories: ["Employer Statement", "Member Statement", "Receipt", "Payment Advice"],
  },
  {
    category: "Notifications",
    description: "Action-oriented notices and decisions sent to stakeholders.",
    subcategories: [
      "Demand Notice",
      "Employer Notice",
      "Member Notice",
      "Approval Letter",
      "Rejection Letter",
      "Appeal Decision",
      "Hearing Notice",
    ],
  },
];

export interface TokenDef {
  token: string;
  label: string;
  sample: string;
}
export interface TokenGroup {
  group: string;
  tokens: TokenDef[];
}

export const TOKEN_CATALOG: TokenGroup[] = [
  { group: "Organization", tokens: [
    { token: "{organization_name}", label: "Organization Name", sample: "Social Security Board" },
    { token: "{organization_tagline}", label: "Tagline", sample: "Securing your future" },
    { token: "{organization_registration_no}", label: "Reg. No.", sample: "SSB-001" },
  ]},
  { group: "Department", tokens: [
    { token: "{department_name}", label: "Department", sample: "Benefits Department" },
    { token: "{department_head}", label: "Department Head", sample: "Dr. R. Phillip" },
  ]},
  { group: "Branch / Location", tokens: [
    { token: "{branch_name}", label: "Branch", sample: "Head Office" },
    { token: "{branch_address}", label: "Branch Address", sample: "Basseterre, St. Kitts" },
    { token: "{branch_phone}", label: "Phone", sample: "+1 869 465 2535" },
    { token: "{branch_email}", label: "Email", sample: "info@ssb.gov.kn" },
    { token: "{branch_website}", label: "Website", sample: "www.socialsecurity.kn" },
  ]},
  { group: "Employer", tokens: [
    { token: "{employer_name}", label: "Employer Name", sample: "ACME Industries Ltd." },
    { token: "{employer_regno}", label: "Employer Reg No.", sample: "ER-002145" },
  ]},
  { group: "Insured Person", tokens: [
    { token: "{member_name}", label: "Member Name", sample: "Jane A. Doe" },
    { token: "{member_number}", label: "Member No.", sample: "100245" },
  ]},
  { group: "Case / Document", tokens: [
    { token: "{case_number}", label: "Case No.", sample: "CASE-2026-018" },
    { token: "{claim_number}", label: "Claim No.", sample: "CL-2026-001234" },
    { token: "{reference_number}", label: "Reference No.", sample: "SSB/BEN/2026/0042" },
    { token: "{document_title}", label: "Document Title", sample: "Sickness Benefit Decision" },
  ]},
  { group: "Payment / Contribution", tokens: [
    { token: "{contribution_period}", label: "Contribution Period", sample: "May 2026" },
    { token: "{amount}", label: "Amount", sample: "EC$ 1,250.00" },
    { token: "{due_date}", label: "Due Date", sample: "30/06/2026" },
  ]},
  { group: "Benefit / Compliance / Legal", tokens: [
    { token: "{benefit_type}", label: "Benefit Type", sample: "Sickness" },
    { token: "{violation_code}", label: "Violation Code", sample: "VC-014" },
    { token: "{legal_act_reference}", label: "Legal Reference", sample: "Social Security Act §17(2)" },
  ]},
  { group: "Officer / System / Date", tokens: [
    { token: "{officer_name}", label: "Officer Name", sample: "M. Williams" },
    { token: "{officer_designation}", label: "Officer Designation", sample: "Senior Claims Officer" },
    { token: "{generated_date}", label: "Generated Date", sample: new Date().toLocaleDateString() },
    { token: "{generated_by}", label: "Generated By", sample: "system" },
    { token: "{version}", label: "Template Version", sample: "v1" },
  ]},
];

export const TOKEN_SAMPLES: Record<string, string> = Object.fromEntries(
  TOKEN_CATALOG.flatMap((g) => g.tokens.map((t) => [t.token, t.sample])),
);

export function applyTokens(input: string): string {
  if (!input) return "";
  return input.replace(/\{[a-z_]+\}/g, (m) => TOKEN_SAMPLES[m] ?? m);
}

export interface ContentBlock {
  key: string;
  label: string;
  body: string;
}

export const CONTENT_BLOCKS: ContentBlock[] = [
  { key: "legal_disclaimer", label: "Legal Disclaimer",
    body: "This communication is issued under the authority of the Social Security Act and is legally binding." },
  { key: "benefit_disclaimer", label: "Benefit Disclaimer",
    body: "Benefit determinations are subject to verification of contributions and supporting documents." },
  { key: "compliance_disclaimer", label: "Compliance Disclaimer",
    body: "Failure to comply within the stated period may result in penalties and legal action." },
  { key: "appeal_instructions", label: "Appeal Instructions",
    body: "You may appeal this decision within 21 days by writing to the Appeals Tribunal." },
  { key: "payment_instructions", label: "Payment Instructions",
    body: "Payments may be made at any SSB office or via approved banking partners using the reference number above." },
  { key: "office_hours", label: "Office Hours",
    body: "Office hours: Monday–Friday, 08:00–16:00, excluding public holidays." },
  { key: "confidentiality", label: "Confidentiality Notice",
    body: "This document contains confidential information. Unauthorized disclosure is prohibited." },
];

// ---------- Design config schema ----------

export type PaperSize = "A4" | "Letter" | "Legal";
export type Orientation = "portrait" | "landscape";
export type Corner = "top_left" | "top_right" | "top_center" | "bottom_left" | "bottom_right" | "bottom_center" | "center" | "none";

export type SignatureSource =
  | "NONE"
  | "FIXED_ASSET"
  | "CASE_OWNER"
  | "DEPARTMENT_MANAGER"
  | "APPROVER"
  | "SELECT_AT_GENERATION";

export type SignatureAppearOn = "FIRST_PAGE" | "LAST_PAGE" | "EVERY_PAGE" | "SPECIFIC_SECTION";
export type SignaturePlacement = "bottom_left" | "bottom_center" | "bottom_right" | "custom";
export type SignaturePlacementMode = "inline_after_signer" | "flow_end_of_content" | "absolute_fixed";

export const SIGNER_BLOCK_TOKEN = "{{signer_block}}";

export interface SignatureBlockConfig {
  show_signature: boolean;
  signature_source: SignatureSource;
  signature_asset_id: string | null;
  show_stamp: boolean;
  stamp_asset_id: string | null;
  show_seal: boolean;
  seal_asset_id: string | null;
  show_approval_stamp: boolean;
  approval_stamp_asset_id: string | null;
  /** How signature/stamp is placed on the page. */
  placement_mode: SignaturePlacementMode;
  /** Used only when placement_mode === "absolute_fixed". */
  placement: SignaturePlacement;
  width_mm: number;
  height_mm: number;
  x_mm: number;
  y_mm: number;
  appear_on: SignatureAppearOn;
  specific_section: string | null;
  require_approval_before_final: boolean;
  reason_required: boolean;
  signature_caption: string;
  /** Sign-off phrase shown above signature in inline modes (e.g. "Sincerely,"). */
  sign_off_phrase: string;
  /** Stamp overlaps signature image (wet-stamp look) in inline modes. */
  stamp_overlap: boolean;
  /** Stamp nudge relative to signature, mm, inline modes only. */
  stamp_offset_x_mm: number;
  stamp_offset_y_mm: number;
}

export interface DesignConfig {
  layout: {
    paper_size: PaperSize;
    orientation: Orientation;
    margin_mm: { top: number; right: number; bottom: number; left: number };
    header_height_mm: number;
    footer_height_mm: number;
    logo_position: Corner;
    seal_position: Corner;
    signature_position: Corner;
    qr_position: Corner;
    watermark_position: Corner;
  };
  branding: {
    logo_asset_id: string | null;
    seal_asset_id: string | null;
    stamp_asset_id: string | null;
    watermark_asset_id: string | null;
    primary_color: string;
    secondary_color: string;
    font_family: string;
    font_size_pt: number;
  };
  header: {
    show_logo: boolean;
    show_qr: boolean;
    show_seal: boolean;
    show_department: boolean;
    organization_name: string;
    department_name: string;
    office_address: string;
    phone: string;
    email: string;
    website: string;
    registration_number: string;
    tagline: string;
    social_media: string;
  };
  footer: {
    footer_text: string;
    contact_details: string;
    website: string;
    confidentiality: string;
    show_page_number: boolean;
    show_generated_date: boolean;
    show_generated_by: boolean;
    show_version: boolean;
  };
  content: {
    body_html: string;
    blocks: string[];
  };
  signature_block: SignatureBlockConfig;
}

export const DEFAULT_SIGNATURE_BLOCK: SignatureBlockConfig = {
  show_signature: false,
  signature_source: "NONE",
  signature_asset_id: null,
  show_stamp: false,
  stamp_asset_id: null,
  show_seal: false,
  seal_asset_id: null,
  show_approval_stamp: false,
  approval_stamp_asset_id: null,
  placement: "bottom_right",
  width_mm: 50,
  height_mm: 20,
  x_mm: 0,
  y_mm: 0,
  appear_on: "LAST_PAGE",
  specific_section: null,
  require_approval_before_final: true,
  reason_required: false,
  signature_caption: "Authorized Signature",
};


export const DEFAULT_DESIGN: DesignConfig = {
  layout: {
    paper_size: "A4",
    orientation: "portrait",
    margin_mm: { top: 20, right: 20, bottom: 20, left: 20 },
    header_height_mm: 30,
    footer_height_mm: 18,
    logo_position: "top_left",
    seal_position: "bottom_right",
    signature_position: "bottom_right",
    qr_position: "bottom_left",
    watermark_position: "center",
  },
  branding: {
    logo_asset_id: null,
    seal_asset_id: null,
    stamp_asset_id: null,
    watermark_asset_id: null,
    primary_color: "#0b3b8c",
    secondary_color: "#6b7280",
    font_family: "Inter, system-ui, Arial, sans-serif",
    font_size_pt: 11,
  },
  header: {
    show_logo: true,
    show_qr: false,
    show_seal: false,
    show_department: true,
    organization_name: "{organization_name}",
    department_name: "{department_name}",
    office_address: "{branch_address}",
    phone: "{branch_phone}",
    email: "{branch_email}",
    website: "{branch_website}",
    registration_number: "{organization_registration_no}",
    tagline: "{organization_tagline}",
    social_media: "",
  },
  footer: {
    footer_text: "This is a system generated document from the Social Security Board.",
    contact_details: "{branch_phone}  ·  {branch_email}",
    website: "{branch_website}",
    confidentiality: "Confidential — for the addressee only.",
    show_page_number: true,
    show_generated_date: true,
    show_generated_by: false,
    show_version: true,
  },
  content: {
    body_html:
      "<p>Dear {member_name},</p>\n<p>This is a sample body paragraph used only for previewing the template. The actual document body is supplied by the originating module when generating real correspondence.</p>\n<p>Sincerely,<br/>{officer_name}<br/>{officer_designation}</p>",
    blocks: [],
  },
  signature_block: DEFAULT_SIGNATURE_BLOCK,
};

export function mergeDesign(partial: any): DesignConfig {
  const p = partial ?? {};
  return {
    layout: { ...DEFAULT_DESIGN.layout, ...(p.layout ?? {}), margin_mm: { ...DEFAULT_DESIGN.layout.margin_mm, ...((p.layout ?? {}).margin_mm ?? {}) } },
    branding: { ...DEFAULT_DESIGN.branding, ...(p.branding ?? {}) },
    header: { ...DEFAULT_DESIGN.header, ...(p.header ?? {}) },
    footer: { ...DEFAULT_DESIGN.footer, ...(p.footer ?? {}) },
    content: { ...DEFAULT_DESIGN.content, ...(p.content ?? {}) },
    signature_block: { ...DEFAULT_SIGNATURE_BLOCK, ...(p.signature_block ?? {}) },
  };
}


export const PAPER_SIZE_MM: Record<PaperSize, { w: number; h: number }> = {
  A4: { w: 210, h: 297 },
  Letter: { w: 216, h: 279 },
  Legal: { w: 216, h: 356 },
};
