/**
 * OM-9.7.6 — Reusable Text-Block Seed Catalogue.
 *
 * These text-block codes are used across many templates and are seeded into
 * `core_text_block`. Legally sensitive blocks are marked `is_placeholder`
 * until final legal wording is approved.
 */
export interface CommTextBlockSeed {
  code: string;
  label: string;
  body_text: string;
  body_html: string;
  is_placeholder: boolean;
}

const B = (
  code: string, label: string, body_text: string,
  is_placeholder = false,
): CommTextBlockSeed => ({
  code, label, body_text,
  body_html: `<p>${body_text.replace(/\n/g, '<br/>')}</p>`,
  is_placeholder,
});

export const COMM_TEXT_BLOCK_SEEDS: CommTextBlockSeed[] = [
  B('STANDARD_CONTACT_INSTRUCTION',           'Standard Contact Instruction',
    'Please contact {{office.name}} at {{office.phone}} or {{office.email}} for any questions.'),
  B('STANDARD_RECORD_CORRECTION_INSTRUCTION', 'Standard Record Correction Instruction',
    'If any information shown here is incorrect, please contact us using the details above.'),
  B('STANDARD_CONFIDENTIALITY_NOTICE',        'Standard Confidentiality Notice',
    'This communication is confidential and intended solely for the addressee.', true),
  B('STANDARD_DISCLAIMER',                    'Standard Disclaimer',
    'This document is generated by the {{organization.name}} system and does not constitute legal advice.', true),
  B('STANDARD_APPEAL_RIGHTS_PLACEHOLDER',     'Standard Appeal Rights (Placeholder)',
    'Placeholder — appeal rights wording pending legal approval.', true),
  B('STANDARD_PAYMENT_NOTE',                  'Standard Payment Note',
    'Please quote reference {{reference.number}} on all payments and correspondence.'),
  B('STANDARD_PORTAL_LOGIN_HELP',             'Standard Portal Login Help',
    'You can sign in to the online portal at {{portal.loginUrl}} using your registered credentials.'),
  B('STANDARD_OFFICE_VISIT_INSTRUCTION',      'Standard Office Visit Instruction',
    'Please bring valid identification when visiting {{office.name}} at {{office.address}}.'),
  B('STANDARD_SYSTEM_GENERATED_NOTICE',       'Standard System-Generated Notice',
    'This notice was generated by the {{organization.name}} system on {{current.date}}.'),
  B('STANDARD_DATA_PRIVACY_NOTICE',           'Standard Data Privacy Notice',
    'Your personal information is handled in accordance with the Data Protection Act.', true),
  B('STANDARD_SMS_FOOTER',                    'Standard SMS Footer',
    '{{organization.name}}. Do not reply.'),
  B('STANDARD_EMAIL_FOOTER_NOTE',             'Standard Email Footer Note',
    'You are receiving this email from {{organization.name}}. For help, contact {{support.email}}.'),
  B('STANDARD_WORKFLOW_ACTION_NOTE',          'Standard Workflow Action Note',
    'Please sign in to {{portal.loginUrl}} to review task {{workflow.instanceNumber}}.'),
];
