// Mock Fee Definitions for Development

import { FeeDefinition } from '@/types/feeConfiguration';

export const MOCK_FEE_DEFINITIONS: FeeDefinition[] = [
  // Legal - Case Initiation Fees
  {
    feeId: 'FEE-LEG-001',
    feeCode: 'LEG_FIL_001',
    feeName: 'Legal Case Filing Fee',
    description: 'Fee for filing a new legal case',
    category: 'Legal',
    subCategory: 'CaseInitiation',
    feeType: 'Fixed',
    fixedAmount: 150.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnLegalCaseCreated'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-001',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-002',
    feeCode: 'LEG_PREP_001',
    feeName: 'Case Preparation Fee',
    description: 'Administrative fee for case preparation',
    category: 'Legal',
    subCategory: 'CaseInitiation',
    feeType: 'Fixed',
    fixedAmount: 75.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnLegalCaseCreated'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-002',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Legal - Summons Fees
  {
    feeId: 'FEE-LEG-003',
    feeCode: 'LEG_SUM_001',
    feeName: 'Summons Preparation Fee',
    description: 'Fee for preparing summons documents',
    category: 'Legal',
    subCategory: 'Summons',
    feeType: 'Fixed',
    fixedAmount: 50.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnSummonsIssued'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-003',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-004',
    feeCode: 'LEG_SUM_002',
    feeName: 'Summons Filing Fee',
    description: 'Court filing fee for summons',
    category: 'Legal',
    subCategory: 'Summons',
    feeType: 'Fixed',
    fixedAmount: 100.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: false,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnSummonsFiled'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-004',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-005',
    feeCode: 'LEG_SUM_003',
    feeName: 'Summons Service Fee',
    description: 'Fee for serving summons to respondent',
    category: 'Legal',
    subCategory: 'Summons',
    feeType: 'Fixed',
    fixedAmount: 65.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnSummonsServed'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-005',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Legal - Judgment Fees
  {
    feeId: 'FEE-LEG-006',
    feeCode: 'LEG_JUD_001',
    feeName: 'Judgment Entry Fee',
    description: 'Fee for entering judgment in court records',
    category: 'Legal',
    subCategory: 'Judgment',
    feeType: 'Fixed',
    fixedAmount: 125.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: false,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnJudgmentRecorded'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-006',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-007',
    feeCode: 'LEG_JUD_002',
    feeName: 'Court Cost Recovery Fee',
    description: 'Recovery of court costs',
    category: 'Legal',
    subCategory: 'Judgment',
    feeType: 'Percentage',
    percentageRate: 2.5,
    baseType: 'JudgmentAmount',
    minAmount: 50.00,
    maxAmount: 500.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnJudgmentRecorded'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-007',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-008',
    feeCode: 'LEG_JUD_003',
    feeName: 'Execution Preparation Fee',
    description: 'Fee for preparing execution documents',
    category: 'Legal',
    subCategory: 'Judgment',
    feeType: 'Fixed',
    fixedAmount: 85.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: false,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnExecutionStarted'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-008',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Legal - Enforcement Fees
  {
    feeId: 'FEE-LEG-009',
    feeCode: 'LEG_WRIT_001',
    feeName: 'Writ of Execution Fee',
    description: 'Fee for issuing writ of execution',
    category: 'Legal',
    subCategory: 'Enforcement',
    feeType: 'Fixed',
    fixedAmount: 200.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: false,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnWritIssued'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-009',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-010',
    feeCode: 'LEG_WAR_001',
    feeName: 'Warrant Fee',
    description: 'Fee for issuing warrant',
    category: 'Legal',
    subCategory: 'Enforcement',
    feeType: 'Fixed',
    fixedAmount: 175.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: false,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnWarrantIssued'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-010',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-011',
    feeCode: 'LEG_BAI_001',
    feeName: 'Bailiff Service Fee',
    description: 'Fee for bailiff/sheriff service',
    category: 'Legal',
    subCategory: 'Enforcement',
    feeType: 'Fixed',
    fixedAmount: 150.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnExecutionStarted'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-011',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Legal - Post-Judgment Fees
  {
    feeId: 'FEE-LEG-012',
    feeCode: 'LEG_MON_001',
    feeName: 'Monthly Monitoring Fee',
    description: 'Recurring monthly monitoring fee after judgment',
    category: 'Legal',
    subCategory: 'PostJudgment',
    feeType: 'Fixed',
    fixedAmount: 25.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    triggerType: 'Scheduled',
    scheduleExpression: '0 0 1 * *', // First day of each month
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-012',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-013',
    feeCode: 'LEG_PAY_001',
    feeName: 'Payment Arrangement Admin Fee',
    description: 'Administrative fee for setting up payment arrangement',
    category: 'Legal',
    subCategory: 'PostJudgment',
    feeType: 'Fixed',
    fixedAmount: 40.00,
    isTaxApplicable: false,
    isCompoundable: true,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal'],
    applicabilityRules: {
      events: ['OnPaymentArrangement'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-013',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Legal - Administrative Fees
  {
    feeId: 'FEE-LEG-014',
    feeCode: 'LEG_DOC_001',
    feeName: 'Document Reproduction Fee',
    description: 'Fee per page for document reproduction',
    category: 'Legal',
    subCategory: 'Administrative',
    feeType: 'Fixed',
    fixedAmount: 2.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: false,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal', 'Admin'],
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-014',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    feeId: 'FEE-LEG-015',
    feeCode: 'LEG_FIL_002',
    feeName: 'File Retrieval Fee',
    description: 'Fee for retrieving archived files',
    category: 'Legal',
    subCategory: 'Administrative',
    feeType: 'Fixed',
    fixedAmount: 15.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: false,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Legal', 'Admin'],
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-001',
    glCodeCredit: '4100-015',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Compliance Fees
  {
    feeId: 'FEE-COM-001',
    feeCode: 'COM_INSP_001',
    feeName: 'Inspection Fee',
    description: 'Fee for conducting compliance inspection',
    category: 'Compliance',
    feeType: 'Fixed',
    fixedAmount: 100.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: true,
    allowManualOverride: true,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Compliance'],
    applicabilityRules: {
      events: ['OnInspectionCompleted'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-002',
    glCodeCredit: '4200-001',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },

  // Benefits Fees
  {
    feeId: 'FEE-BEN-001',
    feeCode: 'BEN_APP_001',
    feeName: 'Benefit Application Processing Fee',
    description: 'Administrative fee for processing benefit application',
    category: 'Benefits',
    feeType: 'Fixed',
    fixedAmount: 50.00,
    isTaxApplicable: false,
    isCompoundable: false,
    isAutoApplied: true,
    allowManualOverride: false,
    allowWaiver: true,
    requiresApproval: false,
    applicableModules: ['Benefits'],
    applicabilityRules: {
      events: ['OnBenefitApplicationSubmitted'],
    },
    effectiveFrom: '2024-01-01',
    glCodeDebit: '1200-003',
    glCodeCredit: '4300-001',
    currency: 'XCD',
    status: 'Active',
    createdAt: '2024-01-01T00:00:00Z',
    createdBy: 'system',
  },
];
