import { FeeWaiverConfiguration, FeeWaiverRequest, FeeWaiverApproval } from '@/types/feeWaiver';

export const feeWaiverConfigurations: FeeWaiverConfiguration[] = [
  {
    configId: 'FWC001',
    feeCategory: 'Legal',
    feeCode: 'LGL-001',
    feeName: 'Court Filing Fee',
    allowWaiver: true,
    maxWaiverPercentage: 50,
    maxWaiverAmount: 500,
    requiresJustification: true,
    allowedInitiators: ['Officer', 'Supervisor', 'Manager'],
    minimumApprovalLevel: 'Manager',
    effectiveFrom: '2024-01-01',
    isActive: true,
    createdBy: 'Admin',
    createdOn: '2024-01-01T00:00:00',
  },
  {
    configId: 'FWC002',
    feeCategory: 'Compliance',
    feeCode: 'CMP-001',
    feeName: 'Late Submission Penalty',
    allowWaiver: true,
    maxWaiverPercentage: 75,
    maxWaiverAmount: 1000,
    requiresJustification: true,
    allowedInitiators: ['Officer', 'Supervisor', 'Manager', 'Director'],
    minimumApprovalLevel: 'Director',
    effectiveFrom: '2024-01-01',
    isActive: true,
    createdBy: 'Admin',
    createdOn: '2024-01-01T00:00:00',
  },
  {
    configId: 'FWC003',
    feeCategory: 'Service',
    feeCode: 'SVC-001',
    feeName: 'Certificate Issuance Fee',
    allowWaiver: true,
    maxWaiverPercentage: 100,
    maxWaiverAmount: 50,
    requiresJustification: true,
    allowedInitiators: ['Officer', 'Supervisor'],
    minimumApprovalLevel: 'Supervisor',
    effectiveFrom: '2024-01-01',
    isActive: true,
    createdBy: 'Admin',
    createdOn: '2024-01-01T00:00:00',
  },
  {
    configId: 'FWC004',
    feeCategory: 'Admin',
    feeCode: 'ADM-001',
    feeName: 'Document Processing Fee',
    allowWaiver: true,
    maxWaiverPercentage: 100,
    maxWaiverAmount: 100,
    requiresJustification: true,
    allowedInitiators: ['Officer', 'Supervisor', 'Manager'],
    minimumApprovalLevel: 'Supervisor',
    effectiveFrom: '2024-01-01',
    isActive: true,
    createdBy: 'Admin',
    createdOn: '2024-01-01T00:00:00',
  },
  {
    configId: 'FWC005',
    feeCategory: 'Finance',
    feeCode: 'FIN-001',
    feeName: 'Payment Processing Fee',
    allowWaiver: false,
    maxWaiverPercentage: 0,
    maxWaiverAmount: 0,
    requiresJustification: true,
    allowedInitiators: ['Director'],
    minimumApprovalLevel: 'Board',
    effectiveFrom: '2024-01-01',
    isActive: true,
    createdBy: 'Admin',
    createdOn: '2024-01-01T00:00:00',
  },
];

export const feeWaiverRequests: FeeWaiverRequest[] = [
  {
    waiverRequestId: 'FWR001',
    waiverNumber: 'WVR-2024-001',
    feeCategory: 'Legal',
    feeCode: 'LGL-001',
    feeName: 'Court Filing Fee',
    originalFeeAmount: 500,
    waiverType: 'Percentage',
    waiverPercentage: 50,
    calculatedWaiverAmount: 250,
    amountAfterWaiver: 250,
    contextModule: 'Legal',
    contextEntityType: 'LegalCase',
    contextEntityId: 'CASE001',
    contextReference: 'LGL-2024-001',
    initiatorType: 'Officer',
    initiatorId: 'EMP001',
    initiatorName: 'John Doe',
    initiatorPosition: 'Legal Officer',
    initiatedOn: '2024-11-01T09:00:00',
    payerType: 'Employer',
    payerId: 'EMP12345',
    payerName: 'ABC Construction Ltd',
    payerIdentification: 'TIN-123456',
    waiverReason: 'Financial Hardship',
    justificationDetails: 'Employer facing financial difficulties due to recent economic downturn. Multiple employees affected. Request waiver to facilitate continued operations and payment arrangement.',
    supportingDocuments: [
      {
        documentId: 'DOC001',
        documentName: 'Financial_Statement_2024.pdf',
        documentType: 'Financial Statement',
        uploadedBy: 'John Doe',
        uploadedOn: '2024-11-01T09:15:00',
      },
      {
        documentId: 'DOC002',
        documentName: 'Hardship_Letter.pdf',
        documentType: 'Supporting Letter',
        uploadedBy: 'John Doe',
        uploadedOn: '2024-11-01T09:20:00',
      },
    ],
    status: 'UnderReview',
    currentApprovalLevel: 'Manager',
    approvalHistory: [
      {
        approvalId: 'APV001',
        waiverRequestId: 'FWR001',
        approvalLevel: 'Supervisor',
        approverType: 'Position',
        approverPositionId: 'POS002',
        approverUserId: 'USER002',
        approverName: 'Jane Smith',
        approvalAction: 'Approved',
        approvalDate: '2024-11-02T10:30:00',
        comments: 'Justification adequate. Recommend approval.',
        sequenceOrder: 1,
      },
    ],
    financialImpact: {
      lostRevenue: 250,
      affectedGLAccount: '4010-Legal-Fees',
      financialYear: '2024',
      posted: false,
    },
    createdBy: 'John Doe',
    createdOn: '2024-11-01T09:00:00',
    submittedOn: '2024-11-01T10:00:00',
    reviewedBy: 'Jane Smith',
    reviewedOn: '2024-11-02T10:30:00',
    internalNotes: 'Priority case - employer has payment plan active',
  },
  {
    waiverRequestId: 'FWR002',
    waiverNumber: 'WVR-2024-002',
    feeCategory: 'Compliance',
    feeCode: 'CMP-001',
    feeName: 'Late Submission Penalty',
    originalFeeAmount: 800,
    waiverType: 'Amount',
    waiverAmount: 400,
    calculatedWaiverAmount: 400,
    amountAfterWaiver: 400,
    contextModule: 'Compliance',
    contextEntityType: 'ComplianceCase',
    contextEntityId: 'CMP001',
    contextReference: 'CMP-2024-045',
    initiatorType: 'Supervisor',
    initiatorId: 'EMP002',
    initiatorName: 'Jane Smith',
    initiatorPosition: 'Compliance Supervisor',
    initiatedOn: '2024-11-05T14:00:00',
    payerType: 'Employer',
    payerId: 'EMP67890',
    payerName: 'XYZ Hotel & Resort',
    payerIdentification: 'TIN-789012',
    waiverReason: 'First-Time Offender',
    justificationDetails: 'First late submission in 10 years of operation. Employer has excellent compliance history. Delay due to change in management personnel.',
    supportingDocuments: [
      {
        documentId: 'DOC003',
        documentName: 'Compliance_History.pdf',
        documentType: 'Compliance Record',
        uploadedBy: 'Jane Smith',
        uploadedOn: '2024-11-05T14:15:00',
      },
    ],
    status: 'Approved',
    currentApprovalLevel: 'Director',
    approvalHistory: [
      {
        approvalId: 'APV002',
        waiverRequestId: 'FWR002',
        approvalLevel: 'Manager',
        approverType: 'Position',
        approverPositionId: 'POS003',
        approverUserId: 'USER003',
        approverName: 'Michael Johnson',
        approvalAction: 'Approved',
        approvalDate: '2024-11-06T11:00:00',
        comments: 'Excellent compliance track record supports waiver request.',
        sequenceOrder: 1,
      },
      {
        approvalId: 'APV003',
        waiverRequestId: 'FWR002',
        approvalLevel: 'Director',
        approverType: 'Position',
        approverPositionId: 'POS001',
        approverUserId: 'USER001',
        approverName: 'Sarah Williams',
        approvalAction: 'Approved',
        approvalDate: '2024-11-07T09:30:00',
        comments: 'Approved based on strong compliance history. Goodwill gesture warranted.',
        sequenceOrder: 2,
      },
    ],
    financialImpact: {
      lostRevenue: 400,
      affectedGLAccount: '4020-Compliance-Penalties',
      financialYear: '2024',
      posted: true,
      postedOn: '2024-11-07T10:00:00',
    },
    createdBy: 'Jane Smith',
    createdOn: '2024-11-05T14:00:00',
    submittedOn: '2024-11-05T15:00:00',
    reviewedBy: 'Michael Johnson',
    reviewedOn: '2024-11-06T11:00:00',
    approvedBy: 'Sarah Williams',
    approvedOn: '2024-11-07T09:30:00',
  },
  {
    waiverRequestId: 'FWR003',
    waiverNumber: 'WVR-2024-003',
    feeCategory: 'Service',
    feeCode: 'SVC-001',
    feeName: 'Certificate Issuance Fee',
    originalFeeAmount: 30,
    waiverType: 'Percentage',
    waiverPercentage: 100,
    calculatedWaiverAmount: 30,
    amountAfterWaiver: 0,
    contextModule: 'Benefits',
    contextEntityType: 'BenefitClaim',
    contextEntityId: 'BEN001',
    contextReference: 'BEN-2024-123',
    initiatorType: 'Officer',
    initiatorId: 'EMP004',
    initiatorName: 'Robert Brown',
    initiatorPosition: 'Benefits Officer',
    initiatedOn: '2024-11-10T08:30:00',
    payerType: 'InsuredPerson',
    payerId: 'IP12345',
    payerName: 'Mary Johnson',
    payerIdentification: 'SSN-456789',
    waiverReason: 'Indigent Applicant',
    justificationDetails: 'Applicant is elderly pensioner with limited income. Certificate required for medical benefits application. Social hardship case.',
    supportingDocuments: [
      {
        documentId: 'DOC004',
        documentName: 'Social_Assessment.pdf',
        documentType: 'Social Worker Report',
        uploadedBy: 'Robert Brown',
        uploadedOn: '2024-11-10T08:45:00',
      },
    ],
    status: 'Submitted',
    currentApprovalLevel: 'Supervisor',
    approvalHistory: [],
    financialImpact: {
      lostRevenue: 30,
      affectedGLAccount: '4030-Service-Fees',
      financialYear: '2024',
      posted: false,
    },
    createdBy: 'Robert Brown',
    createdOn: '2024-11-10T08:30:00',
    submittedOn: '2024-11-10T09:00:00',
    internalNotes: 'Expedite review - medical urgency',
  },
];
