-- Create cn_payment_header table (referenced by other tables)
CREATE TABLE public.cn_payment_header (
    payer_id varchar(6) NOT NULL,
    payer_type varchar(3) NOT NULL,
    payment_id bigint GENERATED BY DEFAULT AS IDENTITY,
    batch_number varchar(25) NOT NULL,
    date_received timestamp(3),
    remarks varchar(61),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT pk_cn_payment_header PRIMARY KEY (payer_id)
);

-- Create cn_payment table
CREATE TABLE public.cn_payment (
    payment_sequence_no bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_code varchar(3) NOT NULL,
    mop_code varchar(3) NOT NULL,
    payment_id bigint NOT NULL,
    fund_code varchar(3) NOT NULL,
    bank_code varchar(3),
    credit_card_code varchar(3),
    payment_date timestamp(3),
    payment_amount numeric(10, 2),
    mop_number varchar(18),
    mop_account_number varchar(18),
    cheque_date timestamp(3),
    mop_transit_number varchar(18),
    mop_notes1 varchar(60),
    expiration_date timestamp(3),
    bank_lodgement_code varchar(3),
    period timestamp(3),
    created_at timestamp with time zone DEFAULT now()
);

-- Create cn_receipt table
CREATE TABLE public.cn_receipt (
    receipt_id varchar(8) NOT NULL,
    payment_id bigint NOT NULL,
    receipt_total numeric(10, 2),
    status varchar(3),
    total_number_of_payments int,
    reprint_times int,
    cancel_reason varchar(40),
    cancel_date timestamp(3),
    cancel_user varchar(8),
    update_control smallint,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT pk_cn_receipt PRIMARY KEY (receipt_id, payment_id)
);

-- Enable RLS on all tables
ALTER TABLE public.cn_payment_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cn_payment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cn_receipt ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users to access these tables
CREATE POLICY "Authenticated users can view payment headers"
ON public.cn_payment_header FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert payment headers"
ON public.cn_payment_header FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update payment headers"
ON public.cn_payment_header FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view payments"
ON public.cn_payment FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert payments"
ON public.cn_payment FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update payments"
ON public.cn_payment FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view receipts"
ON public.cn_receipt FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert receipts"
ON public.cn_receipt FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update receipts"
ON public.cn_receipt FOR UPDATE TO authenticated USING (true);

-- Add indexes for common lookups
CREATE INDEX idx_cn_payment_payment_id ON public.cn_payment(payment_id);
CREATE INDEX idx_cn_receipt_payment_id ON public.cn_receipt(payment_id);