-- Create er_commence table
CREATE TABLE public.er_commence (
    commence_seq_no bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regno varchar(6) NOT NULL,
    date_commenced timestamp(3),
    date_ceased timestamp(3),
    date_modified timestamp(3),
    modified_by varchar(30)
);

-- Create er_last_regno table
CREATE TABLE public.er_last_regno (
    regno varchar(6) PRIMARY KEY,
    date_issued timestamp(3) NOT NULL
);

-- Create er_locations table
CREATE TABLE public.er_locations (
    regno varchar(6) NOT NULL,
    location_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trade_name varchar(40),
    loc_addr1 varchar(25),
    loc_addr2 varchar(25),
    activity_type varchar(50),
    PRIMARY KEY (regno, location_id)
);

-- Create er_master table
CREATE TABLE public.er_master (
    regno varchar(6) PRIMARY KEY,
    name varchar(40) NOT NULL,
    trade_name varchar(40),
    phone varchar(10),
    fax varchar(10),
    hq_addr1 varchar(25),
    hq_addr2 varchar(25),
    office_code varchar(3) DEFAULT 'STK',
    activity_type varchar(50),
    industrial_code varchar(4) DEFAULT '0000',
    maddr1 varchar(25),
    maddr2 varchar(25),
    village_code varchar(3) DEFAULT '000',
    sector_code char(1) DEFAULT 'O',
    males_employed double precision,
    females_employed double precision,
    arrears varchar(1),
    legal_action char(1),
    exp_mthly_income numeric(10,2),
    registration_date timestamp(3),
    date_wages_first_paid timestamp(3),
    date_of_closure timestamp(3),
    application_date timestamp(3),
    date_of_entry timestamp(3),
    date_of_issue timestamp(3),
    date_modified timestamp(3),
    date_verified timestamp(3),
    entered_by varchar(5),
    modified_by varchar(5),
    verified_by varchar(5),
    ownership_code varchar(3),
    previous_owner varchar(40),
    prev_owner_addr1 varchar(25),
    prev_owner_addr2 varchar(25),
    date_of_acquisition timestamp(3),
    date_incorporated timestamp(3),
    computer_payroll varchar(1),
    make_model varchar(30),
    disk_tape varchar(30),
    acquired_code varchar(1),
    estim_arrears_ss numeric(10,2),
    estim_arrears_lv numeric(10,2),
    estim_arrears_pe numeric(10,2),
    estim_wages_ss numeric(10,2),
    estim_wages_lv numeric(10,2),
    estim_wages_pe numeric(10,2),
    status char(1),
    inspector_code varchar(3) DEFAULT 'UNK',
    parent_regno varchar(6),
    re_registration_date timestamp(3),
    registry_num varchar(30),
    mobile varchar(10),
    email varchar(40)
);

-- Create er_notes table
CREATE TABLE public.er_notes (
    regno varchar(6) NOT NULL,
    note_date timestamp(3) NOT NULL,
    seq_no bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note varchar(100),
    user_id varchar(5),
    PRIMARY KEY (regno, note_date, seq_no)
);

-- Create er_notification table
CREATE TABLE public.er_notification (
    eventid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code varchar(3),
    userid varchar(30),
    event_date timestamp(3),
    name varchar(25),
    amount numeric(10,2),
    comment varchar(100)
);

-- Create er_owner table
CREATE TABLE public.er_owner (
    regno varchar(6) NOT NULL,
    location_id bigint,
    owner_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(40),
    title varchar(25),
    phone varchar(10),
    mobile varchar(10),
    email varchar(30),
    ssn varchar(6),
    PRIMARY KEY (regno, location_id, owner_id)
);

-- Create er_suit table
CREATE TABLE public.er_suit (
    suit_identifier bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regno varchar(6) NOT NULL,
    suit_type varchar(3),
    suit_year varchar(4),
    suit_no varchar(4),
    suit_status char(1),
    suit_amount numeric(10,2) DEFAULT 0.0,
    scheme_code varchar(2),
    initial_suit_year varchar(4),
    initial_suit_no varchar(4),
    jds_year varchar(4),
    jds_no varchar(4),
    date_of_filing timestamp(3),
    date_of_hearing timestamp(3),
    awarded_amount numeric(10,2) DEFAULT 0.0,
    awarded_cost numeric(10,2) DEFAULT 0.0,
    outcome_code varchar(3),
    remarks varchar(255),
    remarks2 varchar(255),
    date_of_entry timestamp(3),
    date_modified timestamp(3),
    date_verified timestamp(3),
    entered_by varchar(5),
    modified_by varchar(5),
    verified_by varchar(5),
    beginperiod timestamp(3),
    endperiod timestamp(3),
    date_pay_by timestamp(3)
);

-- Create er_visit table
CREATE TABLE public.er_visit (
    regno varchar(6) NOT NULL,
    location_id bigint,
    date_of_visit timestamp(3) NOT NULL,
    inspector_code varchar(3),
    time_start timestamp(3),
    time_end timestamp(3),
    work_code char(1),
    outcome_code varchar(3),
    number_of_jobs int,
    operation_code varchar(3),
    PRIMARY KEY (regno, location_id, date_of_visit)
);

-- Enable RLS on all tables
ALTER TABLE public.er_commence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_last_regno ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_notification ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_owner ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_suit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.er_visit ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for authenticated users
CREATE POLICY "Authenticated users can view er_commence" ON public.er_commence FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_commence" ON public.er_commence FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_commence" ON public.er_commence FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_commence" ON public.er_commence FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_last_regno" ON public.er_last_regno FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_last_regno" ON public.er_last_regno FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_last_regno" ON public.er_last_regno FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_last_regno" ON public.er_last_regno FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_locations" ON public.er_locations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_locations" ON public.er_locations FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_locations" ON public.er_locations FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_locations" ON public.er_locations FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_master" ON public.er_master FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_master" ON public.er_master FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_master" ON public.er_master FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_master" ON public.er_master FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_notes" ON public.er_notes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_notes" ON public.er_notes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_notes" ON public.er_notes FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_notes" ON public.er_notes FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_notification" ON public.er_notification FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_notification" ON public.er_notification FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_notification" ON public.er_notification FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_notification" ON public.er_notification FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_owner" ON public.er_owner FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_owner" ON public.er_owner FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_owner" ON public.er_owner FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_owner" ON public.er_owner FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_suit" ON public.er_suit FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_suit" ON public.er_suit FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_suit" ON public.er_suit FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_suit" ON public.er_suit FOR DELETE TO authenticated USING (true);

CREATE POLICY "Authenticated users can view er_visit" ON public.er_visit FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert er_visit" ON public.er_visit FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update er_visit" ON public.er_visit FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete er_visit" ON public.er_visit FOR DELETE TO authenticated USING (true);

-- Create indexes for foreign key relationships
CREATE INDEX idx_er_commence_regno ON public.er_commence(regno);
CREATE INDEX idx_er_locations_regno ON public.er_locations(regno);
CREATE INDEX idx_er_notes_regno ON public.er_notes(regno);
CREATE INDEX idx_er_owner_regno ON public.er_owner(regno);
CREATE INDEX idx_er_suit_regno ON public.er_suit(regno);
CREATE INDEX idx_er_visit_regno ON public.er_visit(regno);
CREATE INDEX idx_er_master_status ON public.er_master(status);
CREATE INDEX idx_er_master_parent ON public.er_master(parent_regno);