-- Epic OM-3: Seed audit event types for Organisation Management mutations.
-- Idempotent via ON CONFLICT(event_code). Follows the shape used by earlier OM
-- seeding migrations. Every OM mutation surface in OM-3 references one of
-- these codes via src/platform/audit/auditEventTypes.ts.

INSERT INTO public.core_audit_event_type
  (event_code, event_name, module_code, domain_code, event_category,
   default_severity, default_risk_level,
   is_admin_event, is_security_event, is_migration_event,
   is_pii_event, is_financial_event, requires_before_after)
VALUES
  -- Organisation profile / locations / departments / modules / mappings
  ('ORG_PROFILE_UPDATED',                 'Organisation Profile Updated',        'CORE','ORGANIZATION','CONFIGURATION','INFO','MEDIUM', true,false,false,false,false,true),
  ('ORG_LOCATION_CREATED',                'Location Created',                    'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_LOCATION_UPDATED',                'Location Updated',                    'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_LOCATION_DEACTIVATED',            'Location Deactivated',                'CORE','ORGANIZATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('ORG_LOCATION_REACTIVATED',            'Location Reactivated',                'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,false),
  ('ORG_DEPARTMENT_PROFILE_CREATED',      'Department Profile Created',          'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_DEPARTMENT_PROFILE_UPDATED',      'Department Profile Updated',          'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_DEPARTMENT_PROFILE_DEACTIVATED',  'Department Profile Deactivated',      'CORE','ORGANIZATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('ORG_DEPARTMENT_PROFILE_REACTIVATED',  'Department Profile Reactivated',      'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,false),
  ('ORG_MODULE_PROFILE_CREATED',          'Module Profile Created',              'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_MODULE_PROFILE_UPDATED',          'Module Profile Updated',              'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_MODULE_PROFILE_DEACTIVATED',      'Module Profile Deactivated',          'CORE','ORGANIZATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('ORG_MODULE_PROFILE_REACTIVATED',      'Module Profile Reactivated',          'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,false),
  ('ORG_DEPARTMENT_MAPPING_CREATED',      'Department Mapping Created',          'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_DEPARTMENT_MAPPING_UPDATED',      'Department Mapping Updated',          'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,true),
  ('ORG_DEPARTMENT_MAPPING_DEACTIVATED',  'Department Mapping Deactivated',      'CORE','ORGANIZATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('ORG_DEPARTMENT_MAPPING_REACTIVATED',  'Department Mapping Reactivated',      'CORE','ORGANIZATION','CONFIGURATION','INFO','LOW',    true,false,false,false,false,false),
  -- Communication assets
  ('COMM_MEDIA_ASSET_CREATED',            'Media Asset Created',                 'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_MEDIA_ASSET_UPDATED',            'Media Asset Updated',                 'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_MEDIA_ASSET_DEACTIVATED',        'Media Asset Deactivated',             'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_MEDIA_ASSET_REACTIVATED',        'Media Asset Reactivated',             'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_LETTERHEAD_CREATED',             'Letterhead Created',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_LETTERHEAD_UPDATED',             'Letterhead Updated',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_LETTERHEAD_DEACTIVATED',         'Letterhead Deactivated',              'CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,false),
  ('COMM_LETTERHEAD_REACTIVATED',         'Letterhead Reactivated',              'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_LETTERHEAD_PUBLISHED',           'Letterhead Published',                'CORE','COMMUNICATION','CONFIGURATION','INFO','HIGH',  true,false,false,false,false,true),
  ('COMM_LETTERHEAD_UNPUBLISHED',         'Letterhead Unpublished',              'CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,true),
  ('COMM_SIGNATURE_CREATED',              'Signature Created',                   'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_SIGNATURE_UPDATED',              'Signature Updated',                   'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_SIGNATURE_DEACTIVATED',          'Signature Deactivated',               'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_SIGNATURE_REACTIVATED',          'Signature Reactivated',               'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_HEADER_FOOTER_CREATED',          'Header/Footer Created',               'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_HEADER_FOOTER_UPDATED',          'Header/Footer Updated',               'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_HEADER_FOOTER_DEACTIVATED',      'Header/Footer Deactivated',           'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_HEADER_FOOTER_REACTIVATED',      'Header/Footer Reactivated',           'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_DISCLAIMER_CREATED',             'Disclaimer Created',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_DISCLAIMER_UPDATED',             'Disclaimer Updated',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_DISCLAIMER_DEACTIVATED',         'Disclaimer Deactivated',              'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_DISCLAIMER_REACTIVATED',         'Disclaimer Reactivated',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_PORTAL_BRANDING_UPDATED',        'Portal Branding Updated',             'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_DOCUMENT_ASSET_CREATED',         'Document Asset Created',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_DOCUMENT_ASSET_UPDATED',         'Document Asset Updated',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_DOCUMENT_ASSET_DEACTIVATED',     'Document Asset Deactivated',          'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_DOCUMENT_ASSET_REACTIVATED',     'Document Asset Reactivated',          'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_ASSET_CATEGORY_CREATED',         'Asset Category Created',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_ASSET_CATEGORY_UPDATED',         'Asset Category Updated',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_ASSET_CATEGORY_DEACTIVATED',     'Asset Category Deactivated',          'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_ASSET_CATEGORY_REACTIVATED',     'Asset Category Reactivated',          'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  -- Templates
  ('COMM_TEMPLATE_CREATED',               'Template Created',                    'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_TEMPLATE_UPDATED',               'Template Updated',                    'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_TEMPLATE_DEACTIVATED',           'Template Deactivated',                'CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,false),
  ('COMM_TEMPLATE_REACTIVATED',           'Template Reactivated',                'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_TEMPLATE_PUBLISHED',             'Template Published',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','HIGH',  true,false,false,false,false,true),
  ('COMM_TEMPLATE_UNPUBLISHED',           'Template Unpublished',                'CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,true),
  ('COMM_NOTIFICATION_TEMPLATE_CREATED',  'Notification Template Created',       'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_NOTIFICATION_TEMPLATE_UPDATED',  'Notification Template Updated',       'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,true),
  ('COMM_NOTIFICATION_TEMPLATE_DEACTIVATED','Notification Template Deactivated', 'CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,false),
  ('COMM_NOTIFICATION_TEMPLATE_REACTIVATED','Notification Template Reactivated', 'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_TEXT_BLOCK_CREATED',             'Text Block Created',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_TEXT_BLOCK_UPDATED',             'Text Block Updated',                  'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_TEXT_BLOCK_DEACTIVATED',         'Text Block Deactivated',              'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_TEXT_BLOCK_REACTIVATED',         'Text Block Reactivated',              'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_TOKEN_CREATED',                  'Token Created',                       'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_TOKEN_UPDATED',                  'Token Updated',                       'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_TOKEN_DEACTIVATED',              'Token Deactivated',                   'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_TOKEN_REACTIVATED',              'Token Reactivated',                   'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_CHANNEL_CREATED',                'Channel Created',                     'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_CHANNEL_UPDATED',                'Channel Updated',                     'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_CHANNEL_DEACTIVATED',            'Channel Deactivated',                 'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_CHANNEL_REACTIVATED',            'Channel Reactivated',                 'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_LANGUAGE_CREATED',               'Language Created',                    'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_LANGUAGE_UPDATED',               'Language Updated',                    'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,true),
  ('COMM_LANGUAGE_DEACTIVATED',           'Language Deactivated',                'CORE','COMMUNICATION','CONFIGURATION','WARNING','MEDIUM',true,false,false,false,false,false),
  ('COMM_LANGUAGE_REACTIVATED',           'Language Reactivated',                'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  -- Configuration Center
  ('COMM_CONFIGURATION_ASSIGNMENT_CREATED',    'Configuration Assignment Created',    'CORE','COMMUNICATION','CONFIGURATION','INFO','HIGH', true,false,false,false,false,true),
  ('COMM_CONFIGURATION_ASSIGNMENT_UPDATED',    'Configuration Assignment Updated',    'CORE','COMMUNICATION','CONFIGURATION','INFO','HIGH', true,false,false,false,false,true),
  ('COMM_CONFIGURATION_ASSIGNMENT_DEACTIVATED','Configuration Assignment Deactivated','CORE','COMMUNICATION','CONFIGURATION','WARNING','HIGH',true,false,false,false,false,false),
  ('COMM_CONFIGURATION_ASSIGNMENT_REACTIVATED','Configuration Assignment Reactivated','CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_CONFIGURATION_TEST_RESOLVE_RUN',      'Configuration Test Resolve Run',      'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  -- Validation / impact / export
  ('COMM_USAGE_VALIDATION_RUN',           'Communication Usage Validation Run',  'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_IMPACT_ANALYSIS_RUN',            'Communication Impact Analysis Run',   'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_BROKEN_REFERENCE_SCAN_RUN',      'Broken Reference Scan Run',           'CORE','COMMUNICATION','CONFIGURATION','INFO','MEDIUM',true,false,false,false,false,false),
  ('COMM_HEALTH_CHECK_RUN',               'Enterprise Health Check Run',         'CORE','COMMUNICATION','CONFIGURATION','INFO','LOW',   true,false,false,false,false,false),
  ('COMM_EXPORT_CREATED',                 'Communication Export Created',        'CORE','COMMUNICATION','EXPORT',       'INFO','HIGH',  true,true, false,false,false,false),
  -- OM-3 governance verification marker
  ('ORG_MANAGEMENT_MUTATION_SWEEP_VERIFIED','OM-3 Mutation Sweep Verified',      'CORE','ORGANIZATION','CONFIGURATION','INFO','MEDIUM', true,false,false,false,false,false)
ON CONFLICT (event_code) DO UPDATE
SET event_name = EXCLUDED.event_name,
    module_code = EXCLUDED.module_code,
    domain_code = EXCLUDED.domain_code,
    event_category = EXCLUDED.event_category,
    default_severity = EXCLUDED.default_severity,
    default_risk_level = EXCLUDED.default_risk_level,
    is_admin_event = EXCLUDED.is_admin_event,
    is_security_event = EXCLUDED.is_security_event,
    is_migration_event = EXCLUDED.is_migration_event,
    is_pii_event = EXCLUDED.is_pii_event,
    is_financial_event = EXCLUDED.is_financial_event,
    requires_before_after = EXCLUDED.requires_before_after,
    is_active = true;
