
CREATE OR REPLACE FUNCTION public.cancel_comm_hub_message(
  p_message_id uuid,
  p_reason text,
  p_actor_user_id uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_msg communication_message%ROWTYPE;
  v_old jsonb;
  v_new jsonb;
BEGIN
  IF p_actor_user_id IS NULL THEN
    RAISE EXCEPTION 'actor_user_id required';
  END IF;
  IF NOT public.has_role(p_actor_user_id, 'Admin'::app_role) THEN
    RAISE EXCEPTION 'forbidden: admin required';
  END IF;
  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'reason required';
  END IF;

  SELECT * INTO v_msg FROM public.communication_message WHERE id = p_message_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'message not found: %', p_message_id;
  END IF;
  IF COALESCE(v_msg.origin, '') <> 'comm_hub' THEN
    RAISE EXCEPTION 'refusing to cancel: message origin=% (comm_hub only)', v_msg.origin;
  END IF;
  IF v_msg.status NOT IN ('queued','sending') THEN
    RAISE EXCEPTION 'refusing to cancel: status=% (only queued/sending)', v_msg.status;
  END IF;

  v_old := jsonb_build_object(
    'status', v_msg.status,
    'test_mode', v_msg.test_mode,
    'provider_message_id', v_msg.provider_message_id,
    'request_id', v_msg.request_id,
    'locked_at', v_msg.locked_at,
    'locked_by', v_msg.locked_by,
    'error_code', v_msg.error_code,
    'error_message', v_msg.error_message
  );

  UPDATE public.communication_message
     SET status='cancelled', error_code='STALE_LIVE_PILOT_CANCELLED',
         error_message=left(p_reason, 1000),
         locked_at=NULL, locked_by=NULL, updated_at=now()
   WHERE id = p_message_id;

  v_new := jsonb_build_object(
    'status', 'cancelled',
    'error_code', 'STALE_LIVE_PILOT_CANCELLED',
    'error_message', left(p_reason, 1000),
    'cancelled_by', p_actor_user_id,
    'cancelled_at', now()
  );

  INSERT INTO public.communication_event_log
    (message_id, request_id, event_type, source, payload, actor_user_id)
  VALUES
    (v_msg.id, v_msg.request_id, 'cancelled', 'cancel_comm_hub_message',
     jsonb_build_object('stage','MESSAGE_CANCELLED_BY_ADMIN','reason',p_reason,'actor',p_actor_user_id),
     p_actor_user_id);

  INSERT INTO public.communication_hub_control_audit
    (setting_key, old_value, new_value, reason, changed_by, source)
  VALUES
    ('message_cancelled:' || p_message_id::text, v_old, v_new, p_reason, p_actor_user_id, 'cancel_comm_hub_message');

  BEGIN
    PERFORM public.recompute_communication_request_status(v_msg.request_id);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  RETURN jsonb_build_object(
    'ok', true,
    'message_id', p_message_id,
    'request_id', v_msg.request_id,
    'previous_status', v_msg.status,
    'new_status', 'cancelled'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.cancel_comm_hub_message(uuid, text, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_comm_hub_message(uuid, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_comm_hub_message(uuid, text, uuid) TO service_role;

INSERT INTO public.communication_hub_event_live_control
  (module_code, event_code, status, risk_level, reason)
VALUES
  ('EMPLOYER_REGISTRATION', 'INTERNAL_ACKNOWLEDGEMENT_NOTICE', 'dry_run_only', 'low',
   'Initial business-module dry-run onboarding candidate.')
ON CONFLICT (module_code, event_code) DO NOTHING;

DO $seed$
DECLARE
  v_tpl_id uuid;
  v_ver_id uuid;
BEGIN
  SELECT id INTO v_tpl_id FROM public.core_template
   WHERE code = 'EMPLOYER_REGISTRATION_INTERNAL_ACK_EMAIL';

  IF v_tpl_id IS NULL THEN
    INSERT INTO public.core_template
      (code, name, description, module_code, template_type, template_category,
       status, is_active, scope, owner_scope)
    VALUES
      ('EMPLOYER_REGISTRATION_INTERNAL_ACK_EMAIL',
       'Employer Registration — Internal Acknowledgement (Dry-Run)',
       'Internal dry-run acknowledgement used to validate business-module Communication Hub onboarding. Not for external customer/employer/claimant use.',
       'EMPLOYER_REGISTRATION', 'EMAIL', 'INTERNAL_DRY_RUN',
       'ACTIVE', true, 'GLOBAL', 'GLOBAL')
    RETURNING id INTO v_tpl_id;
  END IF;

  SELECT id INTO v_ver_id FROM public.core_template_version
   WHERE template_id = v_tpl_id AND version_no = 1;

  IF v_ver_id IS NULL THEN
    INSERT INTO public.core_template_version
      (template_id, version_no, status, subject, body_html, body_text, body_metadata, published_at)
    VALUES
      (v_tpl_id, 1, 'PUBLISHED',
       'Employer Registration Internal Acknowledgement — {{reference_no}}',
       $html$<div style="font-family:Arial,sans-serif;font-size:14px;color:#111">
<p><strong>INTERNAL DRY-RUN / ADMIN VALIDATION</strong></p>
<p>Hello {{recipient_name}},</p>
<p>This is an <em>internal</em> Communication Hub onboarding acknowledgement generated by the Generic Event Pilot. It is not a customer notification.</p>
<table style="border-collapse:collapse;font-size:13px">
  <tr><td style="padding:4px 8px;color:#555">Employer</td><td style="padding:4px 8px"><strong>{{employer_name}}</strong></td></tr>
  <tr><td style="padding:4px 8px;color:#555">Reference No</td><td style="padding:4px 8px"><code>{{reference_no}}</code></td></tr>
  <tr><td style="padding:4px 8px;color:#555">Hub Request No</td><td style="padding:4px 8px"><code>{{request_no}}</code></td></tr>
  <tr><td style="padding:4px 8px;color:#555">Generated At</td><td style="padding:4px 8px">{{generated_at}}</td></tr>
</table>
<p style="color:#888;font-size:11px;margin-top:16px">Communication Hub — EMPLOYER_REGISTRATION / INTERNAL_ACKNOWLEDGEMENT_NOTICE (dry-run only)</p>
</div>$html$,
       'INTERNAL DRY-RUN / ADMIN VALIDATION' || E'\n\nHello {{recipient_name}},\n\nInternal Communication Hub onboarding acknowledgement (not a customer notification).\n\nEmployer: {{employer_name}}\nReference No: {{reference_no}}\nHub Request No: {{request_no}}\nGenerated At: {{generated_at}}\n',
       jsonb_build_object(
         'module_code','EMPLOYER_REGISTRATION',
         'event_code','INTERNAL_ACKNOWLEDGEMENT_NOTICE',
         'channel','EMAIL',
         'required_tokens', jsonb_build_array('recipient_name','employer_name','reference_no','request_no','generated_at')
       ),
       now())
    RETURNING id INTO v_ver_id;
  END IF;

  UPDATE public.core_template
     SET active_version_id=v_ver_id, is_active=true, status='ACTIVE', updated_at=now()
   WHERE id = v_tpl_id AND (active_version_id IS DISTINCT FROM v_ver_id OR is_active IS DISTINCT FROM true);
END;
$seed$;
