/**
 * Canonical audit event codes used across the platform.
 * Always import from here instead of hardcoding strings in pages/services.
 */
export const AUDIT_EVENTS = {
  adminRoute: {
    created: 'ADMIN_ROUTE_CREATED',
    updated: 'ADMIN_ROUTE_UPDATED',
    deactivated: 'ADMIN_ROUTE_DEACTIVATED',
    reactivated: 'ADMIN_ROUTE_REACTIVATED',
  },
  tableRegistry: {
    created: 'TABLE_REGISTRY_CREATED',
    updated: 'TABLE_REGISTRY_UPDATED',
    deactivated: 'TABLE_REGISTRY_DEACTIVATED',
    reactivated: 'TABLE_REGISTRY_REACTIVATED',
  },
  legacyMapping: {
    tableCreated: 'LEGACY_TABLE_MAP_CREATED',
    tableUpdated: 'LEGACY_TABLE_MAP_UPDATED',
    tableDeactivated: 'LEGACY_TABLE_MAP_DEACTIVATED',
    tableReactivated: 'LEGACY_TABLE_MAP_REACTIVATED',
    approved: 'LEGACY_TABLE_MAP_APPROVED',
    columnCreated: 'LEGACY_COLUMN_MAP_CREATED',
    columnUpdated: 'LEGACY_COLUMN_MAP_UPDATED',
    columnDeactivated: 'LEGACY_COLUMN_MAP_DEACTIVATED',
    valueCreated: 'LEGACY_VALUE_MAP_CREATED',
    valueUpdated: 'LEGACY_VALUE_MAP_UPDATED',
    valueDeactivated: 'LEGACY_VALUE_MAP_DEACTIVATED',
  },
  referenceGovernance: {
    sourceCreated: 'REFERENCE_SOURCE_CREATED',
    sourceUpdated: 'REFERENCE_SOURCE_UPDATED',
    sourceDeactivated: 'REFERENCE_SOURCE_DEACTIVATED',
    sourceReactivated: 'REFERENCE_SOURCE_REACTIVATED',
    consumerCreated: 'REFERENCE_CONSUMER_CREATED',
    consumerUpdated: 'REFERENCE_CONSUMER_UPDATED',
    consumerDeactivated: 'REFERENCE_CONSUMER_DEACTIVATED',
    consumerReactivated: 'REFERENCE_CONSUMER_REACTIVATED',
    dependencyCreated: 'REFERENCE_DEPENDENCY_CREATED',
    dependencyUpdated: 'REFERENCE_DEPENDENCY_UPDATED',
    dependencyDeactivated: 'REFERENCE_DEPENDENCY_DEACTIVATED',
    dependencyReactivated: 'REFERENCE_DEPENDENCY_REACTIVATED',
    policyCreated: 'REFERENCE_POLICY_CREATED',
    policyUpdated: 'REFERENCE_POLICY_UPDATED',
    policyDeactivated: 'REFERENCE_POLICY_DEACTIVATED',
    policyReactivated: 'REFERENCE_POLICY_REACTIVATED',
  },
  permissionRegistry: {
    created: 'PERMISSION_REGISTRY_CREATED',
    updated: 'PERMISSION_REGISTRY_UPDATED',
    deactivated: 'PERMISSION_REGISTRY_DEACTIVATED',
    reactivated: 'PERMISSION_REGISTRY_REACTIVATED',
    syncStarted: 'PERMISSION_REGISTRY_SYNC_STARTED',
    syncCompleted: 'PERMISSION_REGISTRY_SYNC_COMPLETED',
    syncFailed: 'PERMISSION_REGISTRY_SYNC_FAILED',
  },
  identity: {
    userProfileUpdated: 'USER_PROFILE_UPDATED',
    staffProfileCreated: 'STAFF_PROFILE_CREATED',
    staffProfileUpdated: 'STAFF_PROFILE_UPDATED',
    staffAssignmentCreated: 'STAFF_ASSIGNMENT_CREATED',
    staffAssignmentUpdated: 'STAFF_ASSIGNMENT_UPDATED',
    staffAssignmentDeactivated: 'STAFF_ASSIGNMENT_DEACTIVATED',
    staffAssignmentReactivated: 'STAFF_ASSIGNMENT_REACTIVATED',
    staffAssignmentSetPrimary: 'STAFF_ASSIGNMENT_SET_PRIMARY',
    userSecurityStateUpdated: 'USER_SECURITY_STATE_UPDATED',
    userLocked: 'USER_LOCKED',
    userUnlocked: 'USER_UNLOCKED',
    userSuspended: 'USER_SUSPENDED',
    userDisabled: 'USER_DISABLED',
    userEnabled: 'USER_ENABLED',
    passwordResetRequired: 'USER_PASSWORD_RESET_REQUIRED',
    delegationCreated: 'USER_DELEGATION_CREATED',
    delegationUpdated: 'USER_DELEGATION_UPDATED',
    delegationRevoked: 'USER_DELEGATION_REVOKED',
    roleAssigned: 'USER_ROLE_ASSIGNED',
    roleRemoved: 'USER_ROLE_REMOVED',
  },
  organization: {
    officeCreated: 'OFFICE_CREATED',
    officeUpdated: 'OFFICE_UPDATED',
    officeDeactivated: 'OFFICE_DEACTIVATED',
    officeReactivated: 'OFFICE_REACTIVATED',
    departmentCreated: 'DEPARTMENT_CREATED',
    departmentUpdated: 'DEPARTMENT_UPDATED',
    departmentDeactivated: 'DEPARTMENT_DEACTIVATED',
    departmentReactivated: 'DEPARTMENT_REACTIVATED',
    designationCreated: 'DESIGNATION_CREATED',
    designationUpdated: 'DESIGNATION_UPDATED',
    designationDeactivated: 'DESIGNATION_DEACTIVATED',
    designationReactivated: 'DESIGNATION_REACTIVATED',
    profileUpdated: 'ORGANIZATION_PROFILE_UPDATED',
    officeLocationCreated: 'OFFICE_LOCATION_CREATED',
    officeLocationUpdated: 'OFFICE_LOCATION_UPDATED',
    officeLocationDeactivated: 'OFFICE_LOCATION_DEACTIVATED',
    officeLocationReactivated: 'OFFICE_LOCATION_REACTIVATED',
    holidayCreated: 'CALENDAR_HOLIDAY_CREATED',
    holidayUpdated: 'CALENDAR_HOLIDAY_UPDATED',
    holidayDeactivated: 'CALENDAR_HOLIDAY_DEACTIVATED',
    holidayReactivated: 'CALENDAR_HOLIDAY_REACTIVATED',
    // Epic OM-2 governance setup events
    routeRegistered: 'ORG_MANAGEMENT_ROUTE_REGISTERED',
    permissionRegistered: 'ORG_MANAGEMENT_PERMISSION_REGISTERED',
    permissionAssigned: 'ORG_MANAGEMENT_PERMISSION_ASSIGNED',
    menuRegistered: 'ORG_MANAGEMENT_MENU_REGISTERED',
    permissionWrapperAdded: 'ORG_MANAGEMENT_PERMISSION_WRAPPER_ADDED',
    governanceVerified: 'ORG_MANAGEMENT_GOVERNANCE_VERIFIED',
  },
  security: {
    loginSuccess: 'LOGIN_SUCCESS',
    loginFailure: 'LOGIN_FAILURE',
    accessDenied: 'ACCESS_DENIED',
    sensitiveDataViewed: 'SENSITIVE_DATA_VIEWED',
    exportCreated: 'EXPORT_CREATED',
    reportViewed: 'REPORT_VIEWED',
  },
  employer: {
    registry: {
      created: 'EMPLOYER_REGISTRY_CREATED',
      updated: 'EMPLOYER_REGISTRY_UPDATED',
      deactivated: 'EMPLOYER_REGISTRY_DEACTIVATED',
      reactivated: 'EMPLOYER_REGISTRY_REACTIVATED',
      statusChanged: 'EMPLOYER_STATUS_CHANGED',
      sensitiveViewed: 'EMPLOYER_SENSITIVE_VIEWED',
      exportCreated: 'EMPLOYER_EXPORT_CREATED',
      legacyMappingUsed: 'EMPLOYER_LEGACY_MAPPING_USED',
    },
  },
  // Epic OM-3 — Organisation Management mutation sweep event codes.
  // Kept as an object here so pages/services can import strings without
  // sprinkling literals. The registry rows live in core_audit_event_type.
  orgManagement: {
    profileUpdated: 'ORG_PROFILE_UPDATED',
    locationCreated: 'ORG_LOCATION_CREATED',
    locationUpdated: 'ORG_LOCATION_UPDATED',
    locationDeactivated: 'ORG_LOCATION_DEACTIVATED',
    locationReactivated: 'ORG_LOCATION_REACTIVATED',
    departmentProfileCreated: 'ORG_DEPARTMENT_PROFILE_CREATED',
    departmentProfileUpdated: 'ORG_DEPARTMENT_PROFILE_UPDATED',
    departmentProfileDeactivated: 'ORG_DEPARTMENT_PROFILE_DEACTIVATED',
    departmentProfileReactivated: 'ORG_DEPARTMENT_PROFILE_REACTIVATED',
    moduleProfileCreated: 'ORG_MODULE_PROFILE_CREATED',
    moduleProfileUpdated: 'ORG_MODULE_PROFILE_UPDATED',
    moduleProfileDeactivated: 'ORG_MODULE_PROFILE_DEACTIVATED',
    moduleProfileReactivated: 'ORG_MODULE_PROFILE_REACTIVATED',
    deptMappingCreated: 'ORG_DEPARTMENT_MAPPING_CREATED',
    deptMappingUpdated: 'ORG_DEPARTMENT_MAPPING_UPDATED',
    deptMappingDeactivated: 'ORG_DEPARTMENT_MAPPING_DEACTIVATED',
    deptMappingReactivated: 'ORG_DEPARTMENT_MAPPING_REACTIVATED',
    sweepVerified: 'ORG_MANAGEMENT_MUTATION_SWEEP_VERIFIED',
  },
  communication: {
    mediaAssetCreated: 'COMM_MEDIA_ASSET_CREATED',
    mediaAssetUpdated: 'COMM_MEDIA_ASSET_UPDATED',
    mediaAssetDeactivated: 'COMM_MEDIA_ASSET_DEACTIVATED',
    mediaAssetReactivated: 'COMM_MEDIA_ASSET_REACTIVATED',
    letterheadCreated: 'COMM_LETTERHEAD_CREATED',
    letterheadUpdated: 'COMM_LETTERHEAD_UPDATED',
    letterheadDeactivated: 'COMM_LETTERHEAD_DEACTIVATED',
    letterheadReactivated: 'COMM_LETTERHEAD_REACTIVATED',
    letterheadPublished: 'COMM_LETTERHEAD_PUBLISHED',
    letterheadUnpublished: 'COMM_LETTERHEAD_UNPUBLISHED',
    signatureCreated: 'COMM_SIGNATURE_CREATED',
    signatureUpdated: 'COMM_SIGNATURE_UPDATED',
    signatureDeactivated: 'COMM_SIGNATURE_DEACTIVATED',
    signatureReactivated: 'COMM_SIGNATURE_REACTIVATED',
    headerFooterCreated: 'COMM_HEADER_FOOTER_CREATED',
    headerFooterUpdated: 'COMM_HEADER_FOOTER_UPDATED',
    headerFooterDeactivated: 'COMM_HEADER_FOOTER_DEACTIVATED',
    headerFooterReactivated: 'COMM_HEADER_FOOTER_REACTIVATED',
    disclaimerCreated: 'COMM_DISCLAIMER_CREATED',
    disclaimerUpdated: 'COMM_DISCLAIMER_UPDATED',
    disclaimerDeactivated: 'COMM_DISCLAIMER_DEACTIVATED',
    disclaimerReactivated: 'COMM_DISCLAIMER_REACTIVATED',
    portalBrandingUpdated: 'COMM_PORTAL_BRANDING_UPDATED',
    documentAssetCreated: 'COMM_DOCUMENT_ASSET_CREATED',
    documentAssetUpdated: 'COMM_DOCUMENT_ASSET_UPDATED',
    documentAssetDeactivated: 'COMM_DOCUMENT_ASSET_DEACTIVATED',
    documentAssetReactivated: 'COMM_DOCUMENT_ASSET_REACTIVATED',
    assetCategoryCreated: 'COMM_ASSET_CATEGORY_CREATED',
    assetCategoryUpdated: 'COMM_ASSET_CATEGORY_UPDATED',
    assetCategoryDeactivated: 'COMM_ASSET_CATEGORY_DEACTIVATED',
    assetCategoryReactivated: 'COMM_ASSET_CATEGORY_REACTIVATED',
    templateCreated: 'COMM_TEMPLATE_CREATED',
    templateUpdated: 'COMM_TEMPLATE_UPDATED',
    templateDeactivated: 'COMM_TEMPLATE_DEACTIVATED',
    templateReactivated: 'COMM_TEMPLATE_REACTIVATED',
    templatePublished: 'COMM_TEMPLATE_PUBLISHED',
    templateUnpublished: 'COMM_TEMPLATE_UNPUBLISHED',
    notificationTemplateCreated: 'COMM_NOTIFICATION_TEMPLATE_CREATED',
    notificationTemplateUpdated: 'COMM_NOTIFICATION_TEMPLATE_UPDATED',
    notificationTemplateDeactivated: 'COMM_NOTIFICATION_TEMPLATE_DEACTIVATED',
    notificationTemplateReactivated: 'COMM_NOTIFICATION_TEMPLATE_REACTIVATED',
    textBlockCreated: 'COMM_TEXT_BLOCK_CREATED',
    textBlockUpdated: 'COMM_TEXT_BLOCK_UPDATED',
    textBlockDeactivated: 'COMM_TEXT_BLOCK_DEACTIVATED',
    textBlockReactivated: 'COMM_TEXT_BLOCK_REACTIVATED',
    tokenCreated: 'COMM_TOKEN_CREATED',
    tokenUpdated: 'COMM_TOKEN_UPDATED',
    tokenDeactivated: 'COMM_TOKEN_DEACTIVATED',
    tokenReactivated: 'COMM_TOKEN_REACTIVATED',
    channelCreated: 'COMM_CHANNEL_CREATED',
    channelUpdated: 'COMM_CHANNEL_UPDATED',
    channelDeactivated: 'COMM_CHANNEL_DEACTIVATED',
    channelReactivated: 'COMM_CHANNEL_REACTIVATED',
    languageCreated: 'COMM_LANGUAGE_CREATED',
    languageUpdated: 'COMM_LANGUAGE_UPDATED',
    languageDeactivated: 'COMM_LANGUAGE_DEACTIVATED',
    languageReactivated: 'COMM_LANGUAGE_REACTIVATED',
    configAssignmentCreated: 'COMM_CONFIGURATION_ASSIGNMENT_CREATED',
    configAssignmentUpdated: 'COMM_CONFIGURATION_ASSIGNMENT_UPDATED',
    configAssignmentDeactivated: 'COMM_CONFIGURATION_ASSIGNMENT_DEACTIVATED',
    configAssignmentReactivated: 'COMM_CONFIGURATION_ASSIGNMENT_REACTIVATED',
    configTestResolveRun: 'COMM_CONFIGURATION_TEST_RESOLVE_RUN',
    usageValidationRun: 'COMM_USAGE_VALIDATION_RUN',
    impactAnalysisRun: 'COMM_IMPACT_ANALYSIS_RUN',
    brokenReferenceScanRun: 'COMM_BROKEN_REFERENCE_SCAN_RUN',
    healthCheckRun: 'COMM_HEALTH_CHECK_RUN',
    exportCreated: 'COMM_EXPORT_CREATED',
  },
  domainSplit: {
    orgRouteRegistered: 'ORG_DOMAIN_SPLIT_ROUTE_REGISTERED',
    orgMenuUpdated: 'ORG_DOMAIN_SPLIT_MENU_UPDATED',
    commTemplateRouteRegistered: 'COMM_TEMPLATE_MANAGEMENT_ROUTE_REGISTERED',
    commTemplateMenuRegistered: 'COMM_TEMPLATE_MANAGEMENT_MENU_REGISTERED',
    navigationRegrouped: 'ORG_DOMAIN_NAVIGATION_REGROUPED',
    verified: 'ORG_DOMAIN_SPLIT_VERIFIED',
  },
  documentTemplate: {
    created: 'DOCUMENT_TEMPLATE_CREATED',
    updated: 'DOCUMENT_TEMPLATE_UPDATED',
    deactivated: 'DOCUMENT_TEMPLATE_DEACTIVATED',
    reactivated: 'DOCUMENT_TEMPLATE_REACTIVATED',
    published: 'DOCUMENT_TEMPLATE_PUBLISHED',
    unpublished: 'DOCUMENT_TEMPLATE_UNPUBLISHED',
    cloned: 'DOCUMENT_TEMPLATE_CLONED',
    letterheadLinked: 'DOCUMENT_TEMPLATE_LETTERHEAD_LINKED',
    tokenValidated: 'DOCUMENT_TEMPLATE_TOKEN_VALIDATED',
    previewed: 'DOCUMENT_TEMPLATE_PREVIEWED',
    compatibilityLoaded: 'DOCUMENT_TEMPLATE_COMPATIBILITY_LOADED',
    legacyLetterheadCompatibilityMarked: 'LEGACY_LETTERHEAD_TEMPLATE_COMPATIBILITY_MARKED',
    compatibilityCopied: 'DOCUMENT_TEMPLATE_COMPATIBILITY_COPIED',
    modelSeparationVerified: 'TEMPLATE_MODEL_SEPARATION_VERIFIED',
  },
  // Epic OM-6 — Settings inheritance & override alignment.
  inheritance: {
    overrideEnabled:      'DEPARTMENT_SETTING_OVERRIDE_ENABLED',
    overrideDisabled:     'DEPARTMENT_SETTING_OVERRIDE_DISABLED',
    resetToOrgDefault:    'DEPARTMENT_SETTING_RESET_TO_ORG_DEFAULT',
    settingUpdated:       'DEPARTMENT_SETTING_UPDATED',
    deptEffectivePreview: 'DEPARTMENT_EFFECTIVE_SETTINGS_PREVIEWED',
    orgEffectivePreview:  'ORG_EFFECTIVE_SETTINGS_PREVIEWED',
    effectiveResolved:    'EFFECTIVE_SETTINGS_RESOLVED',
    healthCheckRun:       'INHERITANCE_HEALTH_CHECK_RUN',
    mismatchDetected:     'INHERITANCE_MISMATCH_DETECTED',
    modelVerified:        'INHERITANCE_MODEL_VERIFIED',
  },
  // Epic OM-7 — Configuration Center v2.
  configurationCenter: {
    guidedCreated:     'CONFIG_GUIDED_ASSIGNMENT_CREATED',
    guidedUpdated:     'CONFIG_GUIDED_ASSIGNMENT_UPDATED',
    guidedDeactivated: 'CONFIG_GUIDED_ASSIGNMENT_DEACTIVATED',
    guidedReactivated: 'CONFIG_GUIDED_ASSIGNMENT_REACTIVATED',
    guidedValidated:   'CONFIG_GUIDED_ASSIGNMENT_VALIDATED',
    conflictDetected:  'CONFIG_ASSIGNMENT_CONFLICT_DETECTED',
    advancedViewed:    'CONFIG_ASSIGNMENT_ADVANCED_VIEWED',
    advancedUpdated:   'CONFIG_ASSIGNMENT_ADVANCED_UPDATED',
    testResolveRun:    'CONFIG_TEST_RESOLVE_RUN',
    testResolveFailed: 'CONFIG_TEST_RESOLVE_FAILED',
    verified:          'CONFIG_CENTER_V2_VERIFIED',
  },
  // Epic OM-8 — Scoped notification templates, text blocks, retention policy, remaining setting resources.
  scopedResourceSettings: {
    notificationTemplateAssigned:    'NOTIFICATION_TEMPLATE_SETTING_ASSIGNED',
    notificationTemplateUpdated:     'NOTIFICATION_TEMPLATE_SETTING_UPDATED',
    notificationTemplateDeactivated: 'NOTIFICATION_TEMPLATE_SETTING_DEACTIVATED',
    textBlockAssigned:               'TEXT_BLOCK_SETTING_ASSIGNED',
    textBlockUpdated:                'TEXT_BLOCK_SETTING_UPDATED',
    textBlockDeactivated:            'TEXT_BLOCK_SETTING_DEACTIVATED',
    retentionPolicyCreated:          'RETENTION_POLICY_CREATED',
    retentionPolicyUpdated:          'RETENTION_POLICY_UPDATED',
    retentionPolicyDeactivated:      'RETENTION_POLICY_DEACTIVATED',
    retentionPolicySettingAssigned:  'RETENTION_POLICY_SETTING_ASSIGNED',
    retentionPolicySettingUpdated:   'RETENTION_POLICY_SETTING_UPDATED',
    retentionPolicySettingDeactivated:'RETENTION_POLICY_SETTING_DEACTIVATED',
    approvalWorkflowAssigned:        'APPROVAL_WORKFLOW_SETTING_ASSIGNED',
    approvalWorkflowUpdated:         'APPROVAL_WORKFLOW_SETTING_UPDATED',
    approvalWorkflowDeactivated:     'APPROVAL_WORKFLOW_SETTING_DEACTIVATED',
    dmsFolderValidated:              'DMS_FOLDER_SETTING_VALIDATED',
    verified:                        'SCOPED_RESOURCE_SETTING_VERIFIED',
  },
  // Epic OM-9 — Location canonicalization & office/branch consumption model.
  locationCanonicalization: {
    started:                'LOCATION_CANONICALIZATION_STARTED',
    verified:               'LOCATION_CANONICALIZATION_VERIFIED',
    serviceUpdated:         'LOCATION_CANONICAL_SERVICE_UPDATED',
    mappingCreated:         'LOCATION_COMPATIBILITY_MAPPING_CREATED',
    mappingUpdated:         'LOCATION_COMPATIBILITY_MAPPING_UPDATED',
    mappingMissing:         'LOCATION_COMPATIBILITY_MAPPING_MISSING',
    contextResolved:        'LOCATION_CONTEXT_RESOLVED',
    contextResolveFailed:   'LOCATION_CONTEXT_RESOLVE_FAILED',
    healthCheckRun:         'LOCATION_HEALTH_CHECK_RUN',
    healthIssueDetected:    'LOCATION_HEALTH_ISSUE_DETECTED',
    routeAliasVerified:     'LOCATION_ROUTE_ALIAS_VERIFIED',
  },
  // Epic OM-9.5 — Organisation Default Seeding & UX Stabilisation.
  organizationDefaults: {
    seeded:                'ORG_DEFAULTS_SEEDED',
    updated:               'ORG_DEFAULTS_UPDATED',
    assignmentCreated:     'ORG_DEFAULT_ASSIGNMENT_CREATED',
    assignmentUpdated:     'ORG_DEFAULT_ASSIGNMENT_UPDATED',
    assignmentValidated:   'ORG_DEFAULT_ASSIGNMENT_VALIDATED',
    previewRun:            'ORG_DEFAULT_PREVIEW_RUN',
    previewFailed:         'ORG_DEFAULT_PREVIEW_FAILED',
    testResolveRun:        'ORG_DEFAULT_TEST_RESOLVE_RUN',
    healthCheckRun:        'ORG_DEFAULT_HEALTH_CHECK_RUN',
    healthIssueDetected:   'ORG_DEFAULT_HEALTH_ISSUE_DETECTED',
    uiStabilized:          'ORG_DEFAULT_UI_STABILIZED',
  },
  // Epic OM-9.6 — Location UX & Service Center definition.
  locationUx: {
    stabilized:              'LOCATION_UX_STABILIZED',
    typeUpdated:             'LOCATION_TYPE_UPDATED',
    serviceCenterEnabled:    'LOCATION_SERVICE_CENTER_ENABLED',
    serviceCenterDisabled:   'LOCATION_SERVICE_CENTER_DISABLED',
    publicFacingUpdated:     'LOCATION_PUBLIC_FACING_UPDATED',
    primaryUpdated:          'LOCATION_PRIMARY_UPDATED',
    seedVerified:            'LOCATION_SEED_VERIFIED',
    dialogValidationFailed:  'LOCATION_DIALOG_VALIDATION_FAILED',
    definitionVerified:      'SERVICE_CENTER_DEFINITION_VERIFIED',
  },
  // Epic OM-9.7 — Department Profile Inheritance UX & Preview Stabilization.
  departmentProfileUx: {
    stabilized:          'DEPARTMENT_PROFILE_UX_STABILIZED',
    configOpened:        'DEPARTMENT_PROFILE_CONFIG_OPENED',
    settingsUpdated:     'DEPARTMENT_PROFILE_SETTINGS_UPDATED',
    overrideEnabled:     'DEPARTMENT_PROFILE_OVERRIDE_ENABLED',
    overrideChanged:     'DEPARTMENT_PROFILE_OVERRIDE_CHANGED',
    overrideReset:       'DEPARTMENT_PROFILE_OVERRIDE_RESET',
    allOverridesReset:   'DEPARTMENT_PROFILE_ALL_OVERRIDES_RESET',
    healthCheckRun:      'DEPARTMENT_PROFILE_HEALTH_CHECK_RUN',
    previewRun:          'DEPARTMENT_PROFILE_PREVIEW_RUN',
    previewFailed:       'DEPARTMENT_PROFILE_PREVIEW_FAILED',
    backfillRun:         'DEPARTMENT_PROFILE_BACKFILL_RUN',
    backfillCreated:     'DEPARTMENT_PROFILE_BACKFILL_CREATED',
    backfillSkippedExisting: 'DEPARTMENT_PROFILE_BACKFILL_SKIPPED_EXISTING',
    modelClassified:     'DEPARTMENT_PROFILE_MODEL_CLASSIFIED',
    seedVerified:        'DEPARTMENT_PROFILE_SEED_VERIFIED',
    scopedAssignmentCreated:     'DEPARTMENT_PROFILE_SCOPED_ASSIGNMENT_CREATED',
    scopedAssignmentUpdated:     'DEPARTMENT_PROFILE_SCOPED_ASSIGNMENT_UPDATED',
    scopedAssignmentDeactivated: 'DEPARTMENT_PROFILE_SCOPED_ASSIGNMENT_DEACTIVATED',
  },
  // Epic OM-9.8 — Module Ownership & Defaults + Designation & Approval Hierarchy.
  moduleProfile: {
    seedRun:                'MODULE_PROFILE_SEED_RUN',
    created:                'MODULE_PROFILE_CREATED',
    updated:                'MODULE_PROFILE_UPDATED',
    skippedExisting:        'MODULE_PROFILE_SKIPPED_EXISTING',
    healthCheckRun:         'MODULE_PROFILE_HEALTH_CHECK_RUN',
    healthIssueDetected:    'MODULE_PROFILE_HEALTH_ISSUE_DETECTED',
    ownershipUpdated:       'MODULE_PROFILE_OWNERSHIP_UPDATED',
    inheritanceUpdated:     'MODULE_PROFILE_INHERITANCE_UPDATED',
    ownershipVerified:      'MODULE_OWNERSHIP_DEFAULTS_VERIFIED',
  },
  designationHierarchy: {
    created:                'DESIGNATION_HIERARCHY_CREATED',
    updated:                'DESIGNATION_HIERARCHY_UPDATED',
    removed:                'DESIGNATION_HIERARCHY_REMOVED',
    validated:              'DESIGNATION_HIERARCHY_VALIDATED',
    healthCheckRun:         'DESIGNATION_HIERARCHY_HEALTH_CHECK_RUN',
    healthIssueDetected:    'DESIGNATION_HIERARCHY_HEALTH_ISSUE_DETECTED',
    cycleBlocked:           'DESIGNATION_HIERARCHY_CYCLE_BLOCKED',
    verified:               'DESIGNATION_HIERARCHY_VERIFIED',
  },
} as const;




