/**
 * Canonical audit event codes used across the platform.
 * Always import from here instead of hardcoding strings in pages/services.
 */
export const AUDIT_EVENTS = {
  adminRoute: {
    created: 'ADMIN_ROUTE_CREATED',
    updated: 'ADMIN_ROUTE_UPDATED',
    deactivated: 'ADMIN_ROUTE_DEACTIVATED',
    reactivated: 'ADMIN_ROUTE_REACTIVATED',
  },
  tableRegistry: {
    created: 'TABLE_REGISTRY_CREATED',
    updated: 'TABLE_REGISTRY_UPDATED',
    deactivated: 'TABLE_REGISTRY_DEACTIVATED',
    reactivated: 'TABLE_REGISTRY_REACTIVATED',
  },
  legacyMapping: {
    tableCreated: 'LEGACY_TABLE_MAP_CREATED',
    tableUpdated: 'LEGACY_TABLE_MAP_UPDATED',
    tableDeactivated: 'LEGACY_TABLE_MAP_DEACTIVATED',
    tableReactivated: 'LEGACY_TABLE_MAP_REACTIVATED',
    approved: 'LEGACY_TABLE_MAP_APPROVED',
    columnCreated: 'LEGACY_COLUMN_MAP_CREATED',
    columnUpdated: 'LEGACY_COLUMN_MAP_UPDATED',
    columnDeactivated: 'LEGACY_COLUMN_MAP_DEACTIVATED',
    valueCreated: 'LEGACY_VALUE_MAP_CREATED',
    valueUpdated: 'LEGACY_VALUE_MAP_UPDATED',
    valueDeactivated: 'LEGACY_VALUE_MAP_DEACTIVATED',
  },
  referenceGovernance: {
    sourceCreated: 'REFERENCE_SOURCE_CREATED',
    sourceUpdated: 'REFERENCE_SOURCE_UPDATED',
    sourceDeactivated: 'REFERENCE_SOURCE_DEACTIVATED',
    sourceReactivated: 'REFERENCE_SOURCE_REACTIVATED',
    consumerCreated: 'REFERENCE_CONSUMER_CREATED',
    consumerUpdated: 'REFERENCE_CONSUMER_UPDATED',
    consumerDeactivated: 'REFERENCE_CONSUMER_DEACTIVATED',
    consumerReactivated: 'REFERENCE_CONSUMER_REACTIVATED',
    dependencyCreated: 'REFERENCE_DEPENDENCY_CREATED',
    dependencyUpdated: 'REFERENCE_DEPENDENCY_UPDATED',
    dependencyDeactivated: 'REFERENCE_DEPENDENCY_DEACTIVATED',
    dependencyReactivated: 'REFERENCE_DEPENDENCY_REACTIVATED',
    policyCreated: 'REFERENCE_POLICY_CREATED',
    policyUpdated: 'REFERENCE_POLICY_UPDATED',
    policyDeactivated: 'REFERENCE_POLICY_DEACTIVATED',
    policyReactivated: 'REFERENCE_POLICY_REACTIVATED',
  },
  permissionRegistry: {
    created: 'PERMISSION_REGISTRY_CREATED',
    updated: 'PERMISSION_REGISTRY_UPDATED',
    deactivated: 'PERMISSION_REGISTRY_DEACTIVATED',
    reactivated: 'PERMISSION_REGISTRY_REACTIVATED',
    syncStarted: 'PERMISSION_REGISTRY_SYNC_STARTED',
    syncCompleted: 'PERMISSION_REGISTRY_SYNC_COMPLETED',
    syncFailed: 'PERMISSION_REGISTRY_SYNC_FAILED',
  },
  identity: {
    userProfileUpdated: 'USER_PROFILE_UPDATED',
    staffProfileCreated: 'STAFF_PROFILE_CREATED',
    staffProfileUpdated: 'STAFF_PROFILE_UPDATED',
    staffAssignmentCreated: 'STAFF_ASSIGNMENT_CREATED',
    staffAssignmentUpdated: 'STAFF_ASSIGNMENT_UPDATED',
    staffAssignmentDeactivated: 'STAFF_ASSIGNMENT_DEACTIVATED',
    staffAssignmentReactivated: 'STAFF_ASSIGNMENT_REACTIVATED',
    staffAssignmentSetPrimary: 'STAFF_ASSIGNMENT_SET_PRIMARY',
    userSecurityStateUpdated: 'USER_SECURITY_STATE_UPDATED',
    userLocked: 'USER_LOCKED',
    userUnlocked: 'USER_UNLOCKED',
    userSuspended: 'USER_SUSPENDED',
    userDisabled: 'USER_DISABLED',
    userEnabled: 'USER_ENABLED',
    passwordResetRequired: 'USER_PASSWORD_RESET_REQUIRED',
    delegationCreated: 'USER_DELEGATION_CREATED',
    delegationUpdated: 'USER_DELEGATION_UPDATED',
    delegationRevoked: 'USER_DELEGATION_REVOKED',
    roleAssigned: 'USER_ROLE_ASSIGNED',
    roleRemoved: 'USER_ROLE_REMOVED',
  },
  organization: {
    officeCreated: 'OFFICE_CREATED',
    officeUpdated: 'OFFICE_UPDATED',
    officeDeactivated: 'OFFICE_DEACTIVATED',
    officeReactivated: 'OFFICE_REACTIVATED',
    departmentCreated: 'DEPARTMENT_CREATED',
    departmentUpdated: 'DEPARTMENT_UPDATED',
    departmentDeactivated: 'DEPARTMENT_DEACTIVATED',
    departmentReactivated: 'DEPARTMENT_REACTIVATED',
    designationCreated: 'DESIGNATION_CREATED',
    designationUpdated: 'DESIGNATION_UPDATED',
    designationDeactivated: 'DESIGNATION_DEACTIVATED',
    designationReactivated: 'DESIGNATION_REACTIVATED',
    profileUpdated: 'ORGANIZATION_PROFILE_UPDATED',
    officeLocationCreated: 'OFFICE_LOCATION_CREATED',
    officeLocationUpdated: 'OFFICE_LOCATION_UPDATED',
    officeLocationDeactivated: 'OFFICE_LOCATION_DEACTIVATED',
    officeLocationReactivated: 'OFFICE_LOCATION_REACTIVATED',
    holidayCreated: 'CALENDAR_HOLIDAY_CREATED',
    holidayUpdated: 'CALENDAR_HOLIDAY_UPDATED',
    holidayDeactivated: 'CALENDAR_HOLIDAY_DEACTIVATED',
    holidayReactivated: 'CALENDAR_HOLIDAY_REACTIVATED',
  },
  security: {
    loginSuccess: 'LOGIN_SUCCESS',
    loginFailure: 'LOGIN_FAILURE',
    accessDenied: 'ACCESS_DENIED',
    sensitiveDataViewed: 'SENSITIVE_DATA_VIEWED',
    exportCreated: 'EXPORT_CREATED',
    reportViewed: 'REPORT_VIEWED',
  },
  employer: {
    registry: {
      created: 'EMPLOYER_REGISTRY_CREATED',
      updated: 'EMPLOYER_REGISTRY_UPDATED',
      deactivated: 'EMPLOYER_REGISTRY_DEACTIVATED',
      reactivated: 'EMPLOYER_REGISTRY_REACTIVATED',
      statusChanged: 'EMPLOYER_STATUS_CHANGED',
      sensitiveViewed: 'EMPLOYER_SENSITIVE_VIEWED',
      exportCreated: 'EMPLOYER_EXPORT_CREATED',
      legacyMappingUsed: 'EMPLOYER_LEGACY_MAPPING_USED',
    },
  },
} as const;
