/**
 * EPIC 2B — Dispatch Register. Official register of all communications
 * generated by the Communication Hub. Read-only.
 */
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import { ArrowRight, Download, RefreshCw } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

import OperationsShell from "../utils/OperationsShell";
import { maskEmail, maskPhone } from "../utils/mask";
import { listDispatchRegister, type DeliveryFilter } from "../utils/operationsService";

const CHANNELS = ["email", "sms", "push", "in_app", "letter", "print", "whatsapp"];
const STATUSES = ["pending", "queued", "sending", "sent", "delivered", "failed", "bounced", "cancelled"];

function toCsv(rows: any[]): string {
  if (!rows.length) return "";
  const cols = [
    "request_no", "module_code", "event_code", "entity_type", "entity_id", "reference_no",
    "recipient_masked", "channel", "template_version_id", "test_mode",
    "request_status", "message_status", "requested_by", "created_at", "sent_at", "delivered_at",
  ];
  const escape = (v: any) => v == null ? "" : `"${String(v).replace(/"/g, '""')}"`;
  const header = cols.join(",");
  const body = rows.map(r => cols.map(c => escape((r as any)[c])).join(",")).join("\n");
  return `${header}\n${body}`;
}

export default function DispatchRegisterPage() {
  const [moduleCode, setModuleCode] = useState("");
  const [eventCode, setEventCode] = useState("");
  const [referenceNo, setReferenceNo] = useState("");
  const [requestNo, setRequestNo] = useState("");
  const [channel, setChannel] = useState("all");
  const [status, setStatus] = useState("all");
  const [testMode, setTestMode] = useState<"all" | "test" | "live">("all");
  const [createdFrom, setCreatedFrom] = useState("");
  const [createdTo, setCreatedTo] = useState("");
  const [applied, setApplied] = useState<DeliveryFilter>({ limit: 100 });

  const q = useQuery({
    queryKey: ["comm-hub", "dispatch-register", applied, referenceNo],
    queryFn: () => listDispatchRegister(applied),
  });

  const apply = () => setApplied({
    limit: 100,
    moduleCode: moduleCode.trim() || undefined,
    eventCode: eventCode.trim() || undefined,
    channel: channel !== "all" ? channel : undefined,
    status: status !== "all" ? status : undefined,
    testMode,
    requestNo: requestNo.trim() || undefined,
    createdFrom: createdFrom ? new Date(createdFrom).toISOString() : undefined,
    createdTo: createdTo ? new Date(createdTo).toISOString() : undefined,
  });

  const rows = useMemo(() => {
    const all = q.data ?? [];
    if (!referenceNo.trim()) return all;
    const needle = referenceNo.trim().toLowerCase();
    return all.filter(r => (r.reference_no ?? "").toLowerCase().includes(needle));
  }, [q.data, referenceNo]);

  const csvRows = rows.map(r => ({
    ...r,
    recipient_masked: maskEmail(r.recipient_email) + (r.recipient_phone ? ` | ${maskPhone(r.recipient_phone)}` : ""),
  }));

  const downloadCsv = () => {
    const csv = toCsv(csvRows);
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dispatch-register-${format(new Date(), "yyyyMMdd-HHmm")}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <OperationsShell title="Dispatch Register" subtitle="Official register of every communication issued by the Hub">
      <Card>
        <CardHeader className="pb-3"><CardTitle className="text-base">Filters</CardTitle></CardHeader>
        <CardContent className="grid gap-3 md:grid-cols-4">
          <div><Label>Module</Label><Input value={moduleCode} onChange={e => setModuleCode(e.target.value)} /></div>
          <div><Label>Event</Label><Input value={eventCode} onChange={e => setEventCode(e.target.value)} /></div>
          <div><Label>Reference no.</Label><Input value={referenceNo} onChange={e => setReferenceNo(e.target.value)} placeholder="ER-…" /></div>
          <div><Label>Request no.</Label><Input value={requestNo} onChange={e => setRequestNo(e.target.value)} placeholder="CR-…" /></div>
          <div><Label>Channel</Label>
            <Select value={channel} onValueChange={setChannel}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent><SelectItem value="all">All</SelectItem>{CHANNELS.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent>
            </Select>
          </div>
          <div><Label>Status</Label>
            <Select value={status} onValueChange={setStatus}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent><SelectItem value="all">All</SelectItem>{STATUSES.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
            </Select>
          </div>
          <div><Label>Mode</Label>
            <Select value={testMode} onValueChange={(v) => setTestMode(v as any)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent><SelectItem value="all">All</SelectItem><SelectItem value="test">Test</SelectItem><SelectItem value="live">Live</SelectItem></SelectContent>
            </Select>
          </div>
          <div><Label>From</Label><Input type="datetime-local" value={createdFrom} onChange={e => setCreatedFrom(e.target.value)} /></div>
          <div><Label>To</Label><Input type="datetime-local" value={createdTo} onChange={e => setCreatedTo(e.target.value)} /></div>
          <div className="md:col-span-4 flex gap-2">
            <Button onClick={apply}>Apply</Button>
            <Button variant="outline" onClick={() => q.refetch()}><RefreshCw className="h-4 w-4 mr-1" />Refresh</Button>
            <Button variant="outline" onClick={downloadCsv} disabled={!rows.length}><Download className="h-4 w-4 mr-1" />Export CSV</Button>
            <div className="ml-auto text-sm text-muted-foreground self-center">{rows.length} entries</div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="p-0 overflow-x-auto">
          {q.isLoading ? (
            <div className="p-6 space-y-2">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-8 w-full" />)}</div>
          ) : rows.length === 0 ? (
            <div className="p-6 text-sm text-muted-foreground">No dispatch entries.</div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Request</TableHead>
                  <TableHead>Module / Event</TableHead>
                  <TableHead>Entity</TableHead>
                  <TableHead>Ref</TableHead>
                  <TableHead>Recipient</TableHead>
                  <TableHead>Channel</TableHead>
                  <TableHead>Template v.</TableHead>
                  <TableHead>Mode</TableHead>
                  <TableHead>Req Status</TableHead>
                  <TableHead>Msg Status</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead>Sent</TableHead>
                  <TableHead></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {rows.map(r => (
                  <TableRow key={r.request_id}>
                    <TableCell className="font-mono text-xs">{r.request_no}</TableCell>
                    <TableCell className="text-xs"><div>{r.module_code}</div><div className="text-muted-foreground">{r.event_code}</div></TableCell>
                    <TableCell className="text-xs">{r.entity_type ?? "—"}<div className="font-mono text-[10px] text-muted-foreground">{r.entity_id ? r.entity_id.slice(0, 8) : ""}</div></TableCell>
                    <TableCell className="text-xs">{r.reference_no ?? "—"}</TableCell>
                    <TableCell className="text-xs">
                      <div>{maskEmail(r.recipient_email)}</div>
                      {r.recipient_phone && <div className="text-muted-foreground">{maskPhone(r.recipient_phone)}</div>}
                    </TableCell>
                    <TableCell>{r.channel ? <Badge variant="outline">{r.channel}</Badge> : "—"}</TableCell>
                    <TableCell className="font-mono text-[10px]">{r.template_version_id ? r.template_version_id.slice(0, 8) : "—"}</TableCell>
                    <TableCell>{r.test_mode == null ? "—" : <Badge variant={r.test_mode ? "secondary" : "default"}>{r.test_mode ? "test" : "live"}</Badge>}</TableCell>
                    <TableCell><Badge variant="secondary">{r.request_status}</Badge></TableCell>
                    <TableCell>{r.message_status ? <Badge variant="outline">{r.message_status}</Badge> : "—"}</TableCell>
                    <TableCell className="text-xs">{format(new Date(r.created_at), "yyyy-MM-dd HH:mm")}</TableCell>
                    <TableCell className="text-xs">{r.sent_at ? format(new Date(r.sent_at), "yyyy-MM-dd HH:mm") : "—"}</TableCell>
                    <TableCell>
                      <Button asChild variant="ghost" size="sm">
                        <Link to={`/admin/communication-hub/requests/${r.request_id}`}>Open<ArrowRight className="h-3 w-3 ml-1" /></Link>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </OperationsShell>
  );
}
